### ISSUE TITLE
Update scalapb version to 0.5.47

### ISSUE THREAD

**Issue by drewrobb** [combust/mleap#133]
When using mleap as a dependency in a project that uses the newest version of scalapb (0.5.47) I encounter the following error:

```
[error] Exception in thread "main" java.lang.NoClassDefFoundError: com/trueaccord/lenses/package$Updatable
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[error] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[error] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at ml.combust.bundle.dsl.Value$.basicDataType(Value.scala:206)
[error] 	at ml.combust.bundle.dsl.Value$.<init>(Value.scala:224)
[error] 	at ml.combust.bundle.dsl.Value$.<clinit>(Value.scala)
...

```

Pinning my project to also use the outdated `"com.trueaccord.scalapb" %% "scalapb-runtime" % "0.5.42"` solves the problem, but a better solution would be to use a version of mleap compiled against the latest scalapb. I believe the issue is related to this issue: https://github.com/scalapb/Lenses/issues/2.

**Comment by hollinwilkins** [comment]
Hey there,

Will take a look at this for the next release. We will also be updating Scala ARM to a non-RC version.

**Comment by drewrobb** [comment]
@hollinwilkins thanks! I made this change locally and it only required that one line change, tests pass etc. So I'm happy to make make a PR.

**Comment by hollinwilkins** [comment]
Please do so and we can get it in to 0.6.0 even
