### ISSUE TITLE
empty OneHotEncoder.node in root folder

### ISSUE THREAD

**Issue by kaixinyan** [combust/mleap#135]
when I'm including oneHotEncoder in machine learning pipeline, fitting data using the pipeline, and then saving the model as a zip file, "oneHot_4cde23ce6de5.node" is an empty folder, all other folders, say "strIdx_0dc5e14fb06e.node", have two files, "model.json" and "node.json" inside. Also, the unzipped file is a folder called "root", there is no "bundle.json". If I remove oneHotEncoder transformer, everything is fine.

The code is attached below. Any help is appreciated.

import org.apache.spark.ml.{Pipeline, PipelineModel}
import org.apache.spark.ml.classification.LogisticRegression
import org.apache.spark.ml.feature.{HashingTF, Tokenizer, OneHotEncoder, VectorAssembler}
import org.apache.spark.ml.linalg.Vector
import org.apache.spark.sql.Row

val training = spark.createDataFrame(Seq(
  (0L, 1, 1.0),
  (1L, 1, 0.0),
  (2L, 0, 1.0),
  (3L, 0, 0.0)
)).toDF("id", "gender", "label")

val oneHotEncoder = new OneHotEncoder()
     .setInputCol("gender")
     .setOutputCol("genderVectored")

val featAssembler = new VectorAssembler()
      .setInputCols(Array("genderVectored"))
      .setOutputCol("features")

val lr = new LogisticRegression()
  .setMaxIter(10)
  .setRegParam(0.001)

val pipeline = new Pipeline()
  .setStages(Array(oneHotEncoder, featAssembler, lr))

val model = pipeline.fit(training)

**Comment by hollinwilkins** [comment]
Because OneHotEncoder operates on meta data in the DataFrame to know how large the output arrays are, you need to provide a transformed DataFrame when saving a pipeline with a one hot encoder. I'll put up an example on the docs for tomorrow. In the meantime, you can have a look here where we provide a transformed data frame to the SparkBundleContext before serializing:

https://github.com/combust/mleap/blob/master/mleap-spark-testkit/src/main/scala/org/apache/spark/ml/parity/SparkParityBase.scala#L109

Note: When you do this, the transform is not actually being performed, you are just generating the schema of the data frame, so it is low cost.

**Comment by kaixinyan** [comment]
thanks Hollin. After adding StringIndexer and using (context) defined below, it now works fine.

implicit val context = SparkBundleContext().withDataset(sparkTransformed)

for(modelFile <- managed(BundleFile("jar:file:/tmp/mleap_test.zip"))) {
 model.writeBundle.
    //save our pipeline to a zip file
    //we can save a file to any supported java.nio.FileSystem
   save(modelFile)(context)
}

**Comment by kaixinyan** [comment]
Hi Hollin,

when I'm including Tokenizer and HashingTF, the zipped model cannot be unzipped properly again, only root folder is there, and lr folder does not have model.json, node.json, rather, it is a model.pb(0 bites). It seems the problem has something to do with setNumFeatures(100). It is working when I'm changing 100 to 10. The path tree and code are as follows. Thank you very much!

<exported_model>.zip 
—> exported_model
  |— bundle.json
  |— root 
    |— model.json
    |— node.json
    |— tok_xxx.node
      |— model.json
      |— node.json
    |— tok_yyy.node
      |— model.json
      |— node.json
    |— hashingTF_xxxx.node
      |— model.json
      |— node.json
    |— hashingTF_yyyy.node
      |— model.json
      |— node.json
    |— vecAssembler_zzz.node
      |— model.json
      |— node.json
    |— logreg_zzzz.node
      |— model.json
      |— node.json


<exported_model>.zip 
—> root 
  |— tok_xxx.node
    |— model.json
    |— node.json
  |— tok_yyy.node
    |— model.json
    |— node.json
  |— hashingTF_xxxx.node
    |— model.json
    |— node.json
  |— hashingTF_yyyy.node
    |— model.json
    |— node.json
  |— vecAssembler_zzz.node
    |— model.json
    |— node.json
  |— logreg_zzzz.node
    |— model.pb (0 bites)

import org.apache.spark.ml.{Pipeline, PipelineModel}
import org.apache.spark.ml.classification.LogisticRegression
import org.apache.spark.ml.feature.{HashingTF, Tokenizer, OneHotEncoder, VectorAssembler, StringIndexer}
import org.apache.spark.ml.linalg.Vector
import org.apache.spark.sql.Row
import org.apache.spark.ml.bundle.SparkBundleContext

val training = spark.createDataFrame(Seq(
  ("0L", "M", 1.0),
  ("1L", "M", 0.0),
  ("2L", "F", 1.0),
  ("3L", "F", 0.0)
)).toDF("id", "gender", "label")

val hashFeatColNames = Array("id", "gender")

val featTokenizer = hashFeatColNames.map { 
  colName => new Tokenizer()
        .setInputCol(colName)
        .setOutputCol(colName + "Tokenized")
    }

val featHasher = hashFeatColNames.map { 
    colName => new HashingTF()
        .setInputCol(colName + "Tokenized")
        .setOutputCol(colName + "Tokenized" + "Hashed")
        .setNumFeatures(100)
}

val featAssembler = new VectorAssembler()
      .setInputCols(Array("idTokenizedHashed", "genderTokenizedHashed"))
      .setOutputCol("features")

val lr = new LogisticRegression()
      .setLabelCol("label")
      .setFeaturesCol("features")
      .setMaxIter(10)
      .setRegParam(0.001)

val steps: Array[org.apache.spark.ml.PipelineStage] = featTokenizer ++ featHasher ++ Array(featAssembler, lr)
val pipeline = new Pipeline().setStages(steps)

val model = pipeline.fit(training)
val sparkTransformed = model.transform(training)

import ml.combust.bundle.BundleFile
import ml.combust.mleap.spark.SparkSupport._
import resource._

implicit val context = SparkBundleContext().withDataset(sparkTransformed)

for(modelFile <- managed(BundleFile("jar:file:/tmp/mleap_test12.zip"))) {
 model.writeBundle.
    //save our pipeline to a zip file
    //we can save a file to any supported java.nio.FileSystem
   save(modelFile)(context)
}

**Comment by hollinwilkins** [comment]
Hey, can you modify your code slightly so we can get at the underlying error? Thank you!

```
for(modelFile <- managed(BundleFile("jar:file:/tmp/mleap_test12.zip"))) {
model.writeBundle.
//save our pipeline to a zip file
//we can save a file to any supported java.nio.FileSystem
save(modelFile)(context).get
}.tried.get
```

**Comment by kaixinyan** [comment]
this is the error we are getting

at ml.bundle.TensorType.TensorType.__computeSerializedValue(TensorType.scala:18)
    at ml.bundle.TensorType.TensorType.serializedSize(TensorType.scala:24)
    at ml.bundle.DataType.DataType.__computeSerializedValue(DataType.scala:20)
    at ml.bundle.DataType.DataType.serializedSize(DataType.scala:27)
    at ml.bundle.Attribute.Attribute.__computeSerializedValue(Attribute.scala:19)
    at ml.bundle.Attribute.Attribute.serializedSize(Attribute.scala:26)
    at ml.bundle.AttributeList.AttributeList$AttributesEntry.__computeSerializedValue(AttributeList.scala:96)
    at ml.bundle.AttributeList.AttributeList$AttributesEntry.serializedSize(AttributeList.scala:102)
    at ml.bundle.AttributeList.AttributeList$$anonfun$__computeSerializedValue$1.apply(AttributeList.scala:18)
    at ml.bundle.AttributeList.AttributeList$$anonfun$__computeSerializedValue$1.apply(AttributeList.scala:18)
    at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
    at ml.bundle.AttributeList.AttributeList.__computeSerializedValue(AttributeList.scala:18)
    at ml.bundle.AttributeList.AttributeList.serializedSize(AttributeList.scala:24)
    at com.trueaccord.scalapb.GeneratedMessage$class.writeTo(GeneratedMessageCompanion.scala:34)
    at ml.bundle.AttributeList.AttributeList.writeTo(AttributeList.scala:11)
    at ml.combust.bundle.serializer.attr.AttributeListSerializer$$anonfun$writeProto$2.apply(AttributeListSerializer.scala:55)
    at ml.combust.bundle.serializer.attr.AttributeListSerializer$$anonfun$writeProto$2.apply(AttributeListSerializer.scala:54)
    at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
    at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
    at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
    at scala.util.control.Exception$Catch.apply(Exception.scala:102)
    at scala.util.control.Exception$Catch.either(Exception.scala:124)
    at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
    at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
    at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
    at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
    at scala.util.Try$.apply(Try.scala:161)
    at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
    at ml.combust.bundle.serializer.attr.AttributeListSerializer.writeProto(AttributeListSerializer.scala:56)
    at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1$$anonfun$apply$1.apply(ModelSerializer.scala:100)
    at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1$$anonfun$apply$1.apply(ModelSerializer.scala:98)
    at scala.Option.map(Option.scala:145)
    at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:98)
    at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:88)
    at scala.util.Try$.apply(Try.scala:161)
    at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:88)
    at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:88)
    at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:84)
    at scala.util.Try$.apply(Try.scala:161)
    at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:84)
    at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:34)
    at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:30)
    at scala.util.Try$.apply(Try.scala:161)
    at ml.combust.bundle.serializer.GraphSerializer.writeNode(GraphSerializer.scala:30)
    at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
    at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
    at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
    at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
    at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
    at ml.combust.bundle.serializer.GraphSerializer.write(GraphSerializer.scala:20)
    at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:21)
    at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:14)
    at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:92)
    at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:88)
    at scala.util.Try$.apply(Try.scala:161)
    at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:88)
    at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:88)
    at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:84)
    at scala.util.Try$.apply(Try.scala:161)
    at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:84)
    at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:34)
    at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:29)
    at scala.util.Try$.apply(Try.scala:161)
    at ml.combust.bundle.serializer.BundleSerializer.write(BundleSerializer.scala:29)
    at ml.combust.bundle.BundleWriter.save(BundleWriter.scala:27)
    at Notebook$$anonfun$4.apply(<console>:124)
    at Notebook$$anonfun$4.apply(<console>:120)
    at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
    at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
    at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:124)
    at scala.util.control.Exception$Catch.apply(Exception.scala:102)
    at scala.util.control.Exception$Catch.either(Exception.scala:124)
    at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
    at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
    at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
    at resource.ManagedResourceOperations$class.acquireAndGet(ManagedResourceOperations.scala:25)
    at resource.AbstractManagedResource.acquireAndGet(AbstractManagedResource.scala:50)
    at resource.ManagedResourceOperations$class.foreach(ManagedResourceOperations.scala:53)
    at resource.AbstractManagedResource.foreach(AbstractManagedResource.scala:50)

**Comment by hollinwilkins** [comment]
What is the actual error message?

**Comment by kaixinyan** [comment]
(12) Spark Jobs
java.lang.NoSuchMethodError: ml.bundle.BasicType.BasicType.value()I

**Comment by hollinwilkins** [comment]
Okay, which version of MLeap are you using? Best way to get this info is to:

```
System.out.println(ml.combust.mleap.BuildInfo().gitSha)
System.out.println(ml.combust.mleap.BuildInfo().version)
```

**Comment by kaixinyan** [comment]
System.out.println(ml.combust.mleap.BuildInfo().gitSha)
System.out.println(ml.combust.mleap.BuildInfo().version)
>>
a99dff62f200aacb10c2711b7ee202fbbec2cd29
0.5.0

**Comment by hollinwilkins** [comment]
Hmmmmm... This is definitely an issue with storing tensors in protobuf files. I'll take a look at this tomorrow with logistic regression. Thanks for the bug find.
