### ISSUE TITLE
Question about MLeap Scikit-Learn integration

### ISSUE THREAD

**Issue by ancasarb** [combust/mleap#152]
Following the example from the section "MLeap Scikit-Learn Integration"

```
import sys
# Make sure to checkout the feature/scikit-v2 branch
sys.path.append('/Users/asarb/Documents/projects/mleap/python')

import mleap.sklearn.pipeline
from mleap.sklearn.preprocessing.data import FeatureExtractor

# Import Scikit Transformer(s)
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

df = pd.DataFrame(np.random.randn(10, 5), columns=['a', 'b', 'c', 'd', 'e'])

input_features = ['a', 'c', 'd']
output_vector_name = 'unscaled_continuous_features'
output_features = ["{}_scaled".format(x) for x in input_features]
feature_extractor_tf = FeatureExtractor(input_features,
                                        output_vector_name,
                                        output_features)

standard_scaler_tf = StandardScaler(with_mean=True,
                                    with_std=True)
standard_scaler_tf.mlinit(input_features=output_vector_name,
                          output_features=['scaled_continuous_features'])

standard_scaler_pipeline = Pipeline([(feature_extractor_tf.name, feature_extractor_tf),
                                     (standard_scaler_tf.name, standard_scaler_tf)])
standard_scaler_pipeline.mlinit()
standard_scaler_pipeline.fit_transform(df)
standard_scaler_pipeline.serialize_to_bundle('/Users/asarb/Documents/projects/python/ml/generated-model', 'scikit', init=True)
```

I've tried to use the deserialized model in the mleap-serving module (using the docker image), but get the following exception
```
[ERROR] [03/15/2017 07:08:07.141] [MleapServing-akka.actor.default-dispatcher-4] [MleapResource] error with request
spray.json.DeserializationException: Expected Map as JsObject, but got [{"type":{"base":"string","type":"list"},"name":"nodes","value":["vector_assembler_1b60f602-094e-11e7-8fca-60f81dd1f51c","standard_scaler_1b61e4eb-094e-11e7-a4e7-60f81dd1f51c"]}]
	at spray.json.package$.deserializationError(package.scala:23)
	at spray.json.ProductFormats$class.fromField(ProductFormats.scala:62)
	at spray.json.DefaultJsonProtocol$.fromField(DefaultJsonProtocol.scala:30)
	at spray.json.ProductFormatsInstances$$anon$2.read(ProductFormatsInstances.scala:56)
	at spray.json.ProductFormatsInstances$$anon$2.read(ProductFormatsInstances.scala:46)
	at spray.json.JsValue.convertTo(JsValue.scala:31)
	at ml.combust.bundle.serializer.JsonFormatModelSerializer.read(ModelSerializer.scala:58)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:124)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:123)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at scala.util.control.Exception$Catch.either(Exception.scala:125)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.bundle.serializer.ModelSerializer.readWithModel(ModelSerializer.scala:125)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$3.apply(NodeSerializer.scala:110)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$3.apply(NodeSerializer.scala:109)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.NodeSerializer.read(NodeSerializer.scala:108)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$read$2.apply(BundleSerializer.scala:56)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$read$2.apply(BundleSerializer.scala:49)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.BundleSerializer.read(BundleSerializer.scala:49)
	at ml.combust.bundle.BundleFile.load(BundleFile.scala:87)
	at ml.combust.mleap.runtime.MleapSupport$MleapBundleFileOps.loadMleapBundle(MleapSupport.scala:18)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$2.apply(MleapService.scala:28)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$2.apply(MleapService.scala:27)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at scala.util.control.Exception$Catch.either(Exception.scala:125)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:29)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:29)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [03/15/2017 07:08:07.145] [MleapServing-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(MleapServing)] Error during processing of request: 'Expected Map as JsObject, but got [{"type":{"base":"string","type":"list"},"name":"nodes","value":["vector_assembler_1b60f602-094e-11e7-8fca-60f81dd1f51c","standard_scaler_1b61e4eb-094e-11e7-a4e7-60f81dd1f51c"]}]'. Completing with 500 Internal Server Error response.
```

I can see the difference in my serialized model.json

```
{
   "attributes": [
      {
         "type": {
            "base": "string", 
            "type": "list"
         }, 
         "name": "nodes",
         "value": [
            "vector_assembler_e15e920f-094e-11e7-9113-60f81dd1f51c", 
            "standard_scaler_e15f62bd-094e-11e7-9413-60f81dd1f51c"
         ]
      }
   ], 
   "op": "pipeline"
} 
```

as opposed to the airbnb.model.lr-0.6.0-SNAPSHOT model.json I was previously using

```
{
  "op": "pipeline",
  "attributes": {
    "nodes": {
      "type": {
        "type": "list",
        "base": "string"
      },
      "value": ["feature_pipeline", "linear_regression"]
    }
  }
}
```

but not sure how to fix this entirely.

**Comment by ancasarb** [comment]
Not sure if this change https://github.com/combust/bundle-protobuf/commit/c1185f52e60343c4ccd33d3d0165a220eb61bf28 is related. I'm attaching the zipped serialized model for reference as well. 
[scikit.zip](https://github.com/combust/mleap/files/844019/scikit.zip)

**Comment by ancasarb** [comment]
Update: I've pushed to this branch https://github.com/combust/mleap/compare/feature/scikit-v2...ancasarb:feature/scikit-v2_updates?expand=1 the updates I've had to make in order to get this example working http://mleap-docs.combust.ml/scikit-learn/.

**Comment by seme0021** [comment]
Hi @ancasarb,

Thank you for the note and the fix - I'll have time to review on Friday. If you're interested in contributing to Scikit<>MLeap integration, it would be great to talk about the design with you and @hollinwilkins before we finalize and merge scikit into master - let us know if you have some availability next week.

Best,
M

**Comment by ancasarb** [comment]
Hi @seme0021,

Sounds good, I am keen to learn & contribute to Mleap (it's a great project!) in general and to the Scikit integration in particular, because most of the models at work are written using Scikit library and we're looking at the moment of using Mleap for serialization of our models and scoring. Any day apart for Wednesday next week is good for me.

Thank you,
Anca

**Comment by seme0021** [comment]
@ancasarb,

Can you shoot me and Hollin an email at mikhail@combust.com and hollin@combust.com and we'll find a time on Wednesday that works for us?

Thanks!
M

**Comment by ancasarb** [comment]
@seme0021 I've sent an email to your and Hollin's @combust.ml emails, because I got an undelivered email error using @combust.com. I wasn't too clear above, but I am available this week any day, except Wednesday.

**Comment by ancasarb** [comment]
@seme0021 and @hollinwilkins thank you for your help on this, think we can close this now.
