### ISSUE TITLE
Key not found for VectorIndexer models after serialization from Spark

### ISSUE THREAD

**Issue by joyceqli** [combust/mleap#153]
I had problem when deserializing a Mleap bundle which is saved from Spark VectorIndexer. Such as:

```
val data = spark.read.format("libsvm").load("/tmp/sampe_libsvm_data.txt")
val featureIndexer = new VectorIndexer().setInputCol("features").setOutputCol("indexedFeatures").setMaxCategories(4).fit(data)
val dt = new DecisionTreeRegressor().setLabelCol("label").setFeaturesCol("indexedFeatures")
val pipeline = new Pipeline().setStages(Array(featureIndexer, dt))
val model = pipeline.fit(data)
val leapPipeline = SparkUtil.createPipelineModel(uid = "ibmpipeline", Array(model))
for(bf <- managed(BundleFile("jar:file:/tmp/models/dectrreg.zip"))) {
    leapPipeline.writeBundle.format(SerializationFormat.Json).save(bf)
}
```
And then when I de-serialized the bundle, bundleFile.loadMleapBundle() is still a Failure(java.util.NoSuchElementException: key not found: 645_keys)

The stack trace is
java.util.NoSuchElementException: key not found: 645_keys
at scala.collection.MapLike$class.default(MapLike.scala:228)
at scala.collection.AbstractMap.default(Map.scala:59)
at scala.collection.MapLike$class.apply(MapLike.scala:141)
at scala.collection.AbstractMap.apply(Map.scala:59)
at ml.combust.bundle.dsl.AttributeList.attr(AttributeList.scala:176)
at ml.combust.bundle.dsl.AttributeList.apply(AttributeList.scala:167)
at ml.combust.bundle.dsl.HasAttributeList$class.attr(AttributeList.scala:21)
at ml.combust.bundle.dsl.Model.attr(Model.scala:31)
at ml.combust.bundle.dsl.HasAttributeList$class.value(AttributeList.scala:37)
at ml.combust.bundle.dsl.Model.value(Model.scala:31)
at ml.combust.mleap.bundle.ops.feature.VectorIndexerOp$$anon$1$$anonfun$4.apply(VectorIndexerOp.scala:41)

I looked into memory and the map being looked up has keys with "key_" prefixes, e.g. "key_645_keys". 

@hollinwilkins 
Solution confirmed: 
ml.combust.mleap.bundle.ops.feature.VectorIndexerOp line 41&42 change to
```
val kKeys = model.value(s"key_${key}_keys").getDoubleList
val kValues = model.value(s"key_${key}_values").getLongList.map(_.toInt)
```
org.apache.spark.ml.bundle.ops.feature.VectorIndexerOp line 40&41 change to
```
  val kKeys = model.value(s"key_${key}_keys").getDoubleList
  val kValues = model.value(s"key_${key}_values").getLongList.map(_.toInt)
```

**Comment by yourspuru007** [comment]
is this fixed in spark 2.2.0? 
because I'm getting the same error
