### ISSUE TITLE
Binarizer does not accept double input

### ISSUE THREAD

**Issue by joyceqli** [combust/mleap#171]
Spark Binarizer accept both double and vector input. Mleap BinarizerModel also handles both:
```
def apply(value: Double): Double = {
    if (value > threshold) 1.0 else 0.0
  }

  def apply(value: Vector): Vector = {
    val indices = mutable.ArrayBuilder.make[Int]
    val values = mutable.ArrayBuilder.make[Double]
....
```
But the udf in Binarizer only accepts Tensor[Double] as input
```
case class Binarizer(override val uid: String = Transformer.uniqueName("binarizer"),
                     override val inputCol: String,
                     override val outputCol: String,
                     model: BinarizerModel) extends FeatureTransformer {
  override val exec: UserDefinedFunction = (value: Tensor[Double]) => model(value): Tensor[Double]
}
```
Exception stack when input is double:

```
field feature data type DoubleType(false) does not match TensorType(DoubleType(false),false)
java.lang.IllegalArgumentException: field feature data type DoubleType(false) does not match TensorType(DoubleType(false),false)
	at ml.combust.mleap.runtime.RowUtil$$anonfun$createRowSelector$1.apply(RowUtil.scala:50)
	at ml.combust.mleap.runtime.RowUtil$$anonfun$createRowSelector$1.apply(RowUtil.scala:45)
	at scala.util.Success.flatMap(Try.scala:230)
	at ml.combust.mleap.runtime.RowUtil$.createRowSelector(RowUtil.scala:45)
	at ml.combust.mleap.runtime.RowUtil$$anonfun$createRowSelectors$2.apply(RowUtil.scala:26)
	at ml.combust.mleap.runtime.RowUtil$$anonfun$createRowSelectors$2.apply(RowUtil.scala:24)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:48)
	at ml.combust.mleap.runtime.RowUtil$.createRowSelectors(RowUtil.scala:24)
	at ml.combust.mleap.runtime.LeapFrame$class.withField(LeapFrame.scala:67)
	at ml.combust.mleap.runtime.DefaultLeapFrame.withField(DefaultLeapFrame.scala:10)
	at ml.combust.mleap.runtime.LeapFrame$class.withOutput(LeapFrame.scala:108)
	at ml.combust.mleap.runtime.DefaultLeapFrame.withOutput(DefaultLeapFrame.scala:10)
	at ml.combust.mleap.runtime.transformer.builder.TransformBuilder$class.withOutput(TransformBuilder.scala:16)
	at ml.combust.mleap.runtime.DefaultLeapFrame.withOutput(DefaultLeapFrame.scala:10)
	at ml.combust.mleap.runtime.transformer.FeatureTransformer$class.transform(Transformer.scala:45)
	at ml.combust.mleap.runtime.transformer.feature.Binarizer.transform(Binarizer.scala:12)
	at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:13)
	at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:13)
	at scala.util.Success.flatMap(Try.scala:230)
	at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:13)
	at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:13)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at ml.combust.mleap.runtime.transformer.Pipeline.transform(Pipeline.scala:13)
	at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:13)
	at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:13)
	at scala.util.Success.flatMap(Try.scala:230)
	at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:13)
	at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:13)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at ml.combust.mleap.runtime.transformer.Pipeline.transform(Pipeline.scala:13)
```

**Comment by joyceqli** [comment]
Sample fix for ml.combust.,leap.runtime.transformer.feature.Binarizer
```
case class Binarizer(override val uid: String = Transformer.uniqueName("binarizer"),
                     override val inputCol: String,
                     override val outputCol: String,
                     model: BinarizerModel) extends FeatureTransformer {
  override val exec: UserDefinedFunction = (value: Tensor[Double]) => model(value): Tensor[Double]
  val execDouble: UserDefinedFunction = (value: Double) => model(value): Double

  override def transform[TB <: TransformBuilder[TB]](builder: TB): Try[TB] = {
    val result = builder.withOutput(outputCol, inputCol)(exec)
    if(result.isFailure && result.failed.get != null && result.failed.get.isInstanceOf[IllegalArgumentException]) {
      builder.withOutput(outputCol, inputCol)(execDouble)
    }
    else {
      result
    }
  }
}
```
