### ISSUE TITLE
Deserialized Spark Pipeline error

### ISSUE THREAD

**Issue by manugarri** [combust/mleap#183]
Trying to get deserialized Spark pipelines to work.

I follow the example in the [docs](http://mleap-docs.combust.ml/mleap-runtime/create-leap-frame.html) to create a leapframe. Then perform the transformation the same way as stated in this [example](https://github.com/combust/mleap-demo/blob/master/notebooks/airbnb-price-regression.ipynb) (output [30])

The code is as follows:

```

import ml.combust.mleap.runtime._
import ml.combust.mleap.runtime.types._

// RELOAD Pipeline
val mleapTransformerRf = (for(bf <- managed(BundleFile("jar:file:/tmp/test.zip"))) yield {
      bf.loadMleapBundle().get.root
    }).tried.get

//datasetImputedFiltered is the original spark dataframe used to train the pipeline

val dataset: LocalDataset = LocalDataset(Row(datasetImputedFiltered.drop("target").take(1)(0)), Row(datasetImputedFiltered.drop("target").take(2)(1)))

//to create the schema, i just printed the datasetImputedFiltered.schema and used it as a guideline
// Ideally i would cast the mleap StructType from spark's dataset schema structype. That didnt work.  
val schema = StructType(StructField("pais",StringType()), StructField("device_make",StringType()), StructField("device_os",StringType())).get

//create the leapframe
val leapFrame: DefaultLeapFrame = LeapFrame(schema, dataset)

//perform transformation
mleapTransformerRf.sparkTransform(datasetImputedFiltered)
```

This is giving me the error:

```
org.apache.spark.SparkException: ml.combust.mleap.tensor.Tensor is not annotated with SQLUserDefinedType nor registered with UDTRegistration.}
  at org.apache.spark.sql.catalyst.encoders.RowEncoder$$anonfun$1.apply(RowEncoder.scala:84)
  at org.apache.spark.sql.catalyst.encoders.RowEncoder$$anonfun$1.apply(RowEncoder.scala:84)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.sql.catalyst.encoders.RowEncoder$.org$apache$spark$sql$catalyst$encoders$RowEncoder$$serializerFor(RowEncoder.scala:83)
  at org.apache.spark.sql.catalyst.encoders.RowEncoder$$anonfun$2.apply(RowEncoder.scala:157)
  at org.apache.spark.sql.catalyst.encoders.RowEncoder$$anonfun$2.apply(RowEncoder.scala:156)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
  at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:186)
  at org.apache.spark.sql.catalyst.encoders.RowEncoder$.org$apache$spark$sql$catalyst$encoders$RowEncoder$$serializerFor(RowEncoder.scala:156)
  at org.apache.spark.sql.catalyst.encoders.RowEncoder$.apply(RowEncoder.scala:61)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:65)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withPlan(Dataset.scala:2603)
  at org.apache.spark.sql.Dataset.select(Dataset.scala:969)
  at org.apache.spark.sql.Dataset.withColumn(Dataset.scala:1697)
  at ml.combust.mleap.spark.SparkTransformBuilder$$anonfun$withOutput$1.apply(SparkTransformBuilder.scala:19)
  at ml.combust.mleap.spark.SparkTransformBuilder$$anonfun$withOutput$1.apply(SparkTransformBuilder.scala:16)
  at scala.util.Try$.apply(Try.scala:192)
  at ml.combust.mleap.spark.SparkTransformBuilder.withOutput(SparkTransformBuilder.scala:16)
  at ml.combust.mleap.runtime.transformer.builder.TransformBuilder$class.withOutput(TransformBuilder.scala:16)
  at ml.combust.mleap.spark.SparkTransformBuilder.withOutput(SparkTransformBuilder.scala:14)
  at ml.combust.mleap.runtime.transformer.FeatureTransformer$class.transform(Transformer.scala:45)
  at ml.combust.mleap.runtime.transformer.feature.OneHotEncoder.transform(OneHotEncoder.scala:12)
  at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:13)
  at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:13)
  at scala.util.Success.flatMap(Try.scala:231)
  at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:13)
  at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:13)
  at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
  at scala.collection.immutable.List.foldLeft(List.scala:84)
  at ml.combust.mleap.runtime.transformer.Pipeline.transform(Pipeline.scala:13)
  at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:13)
  at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:13)
  at scala.util.Success.flatMap(Try.scala:231)
  at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:13)
  at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:13)
  at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
  at scala.collection.immutable.List.foldLeft(List.scala:84)
  at ml.combust.mleap.runtime.transformer.Pipeline.transform(Pipeline.scala:13)
  at ml.combust.mleap.spark.SparkSupport$MleapSparkTransformerOps.sparkTransform(SparkSupport.scala:28)

```

Am I doing it right? Not sure what's failling here.

**Comment by manugarri** [comment]
Confirmed that the example shown in [here](https://github.com/combust/mleap-demo/blob/master/notebooks/airbnb-price-regression.ipynb) produces the same error when doing `val sparkDataframe = mleapTransformerRf.sparkTransform(datasetImputedFiltered)`


I am using spark 2.1.0 and scala 2.11.8.

**Comment by hollinwilkins** [comment]
@manugarri Hey, did you make sure to run this line?

```
// Register the Tensor UDT with Spark
org.apache.spark.sql.mleap.TensorUDT
```

It looks like a no-op, but is actually quite important as it loads the TensorUDT into Spark, so that you can then transform a Spark DataFrame with an MLeap transformer. This is also usage that is not needed most of the time, as you can just deserialize an MLeap Bundle directly into a Spark transformer to transform DataFrames.

**Comment by hollinwilkins** [comment]
Closing this for now, reopen if you are still having issues.
