### ISSUE TITLE
java.lang.NoSuchMethodError: ml.bundle.BasicType.BasicType.value()I

### ISSUE THREAD

**Issue by clocklear** [combust/mleap#195]
I'm trying to serialize SparkML logistic regression model and associated pipeline using the PySpark bindings and I'm getting the below error:

```
> pipelineModel.serializeToBundle("jar:file:/dbfs/FileStore/blah2.lr.zip", dataset=rawdata)
```

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-14-cdb52356885f> in <module>()
      3 #ss = SimpleSparkSerializer()
      4 # ss.serializeToBundle(pipelineModel, "jar:file:/dbfs/FileStore/blah.lr.zip", dataset=rawdata)
----> 5 pipelineModel.serializeToBundle("jar:file:/dbfs/FileStore/blah2.lr.zip", dataset=rawdata)

/opt/libs/mleap/python/mleap/pyspark/spark_support.py in serializeToBundle(self, path, dataset)
     23 def serializeToBundle(self, path, dataset=None):
     24     serializer = SimpleSparkSerializer()
---> 25     serializer.serializeToBundle(self, path, dataset=dataset)
     26 
     27 

/opt/libs/mleap/python/mleap/pyspark/spark_support.py in serializeToBundle(self, transformer, path, dataset)
     40 
     41     def serializeToBundle(self, transformer, path, dataset):
---> 42         self._java_obj.serializeToBundle(transformer._to_java(), path, dataset._jdf)
     43 
     44     def deserializeFromBundle(self, path):

/databricks/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    317                 raise Py4JJavaError(
    318                     "An error occurred while calling {0}{1}{2}.\n".
--> 319                     format(target_id, ".", name), value)
    320             else:
    321                 raise Py4JError(

Py4JJavaError: An error occurred while calling o2671.serializeToBundle.
: java.lang.NoSuchMethodError: ml.bundle.BasicType.BasicType.value()I
	at ml.bundle.TensorType.TensorType.__computeSerializedValue(TensorType.scala:18)
	at ml.bundle.TensorType.TensorType.serializedSize(TensorType.scala:24)
	at ml.bundle.DataType.DataType.__computeSerializedValue(DataType.scala:20)
	at ml.bundle.DataType.DataType.serializedSize(DataType.scala:27)
	at ml.bundle.Attribute.Attribute.__computeSerializedValue(Attribute.scala:19)
	at ml.bundle.Attribute.Attribute.serializedSize(Attribute.scala:26)
	at ml.bundle.AttributeList.AttributeList$AttributesEntry.__computeSerializedValue(AttributeList.scala:96)
	at ml.bundle.AttributeList.AttributeList$AttributesEntry.serializedSize(AttributeList.scala:102)
	at ml.bundle.AttributeList.AttributeList$$anonfun$__computeSerializedValue$1.apply(AttributeList.scala:18)
	at ml.bundle.AttributeList.AttributeList$$anonfun$__computeSerializedValue$1.apply(AttributeList.scala:18)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at ml.bundle.AttributeList.AttributeList.__computeSerializedValue(AttributeList.scala:18)
	at ml.bundle.AttributeList.AttributeList.serializedSize(AttributeList.scala:24)
	at com.trueaccord.scalapb.GeneratedMessage$class.writeTo(GeneratedMessageCompanion.scala:34)
	at ml.bundle.AttributeList.AttributeList.writeTo(AttributeList.scala:11)
	at ml.combust.bundle.serializer.attr.AttributeListSerializer$$anonfun$writeProto$2.apply(AttributeListSerializer.scala:55)
	at ml.combust.bundle.serializer.attr.AttributeListSerializer$$anonfun$writeProto$2.apply(AttributeListSerializer.scala:54)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at scala.util.control.Exception$Catch.either(Exception.scala:125)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.bundle.serializer.attr.AttributeListSerializer.writeProto(AttributeListSerializer.scala:56)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1$$anonfun$apply$1.apply(ModelSerializer.scala:100)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1$$anonfun$apply$1.apply(ModelSerializer.scala:98)
	at scala.Option.map(Option.scala:146)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:98)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:88)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:88)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:88)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:84)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:84)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:34)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:30)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.GraphSerializer.writeNode(GraphSerializer.scala:30)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35)
	at ml.combust.bundle.serializer.GraphSerializer.write(GraphSerializer.scala:20)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:21)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:14)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:92)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:88)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:88)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:88)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:84)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:84)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:34)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:29)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.BundleSerializer.write(BundleSerializer.scala:29)
	at ml.combust.bundle.BundleWriter.save(BundleWriter.scala:27)
	at ml.combust.mleap.spark.SimpleSparkSerializer$$anonfun$serializeToBundle$2.apply(SimpleSparkSerializer.scala:21)
	at ml.combust.mleap.spark.SimpleSparkSerializer$$anonfun$serializeToBundle$2.apply(SimpleSparkSerializer.scala:20)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at scala.util.control.Exception$Catch.either(Exception.scala:125)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.mleap.spark.SimpleSparkSerializer.serializeToBundle(SimpleSparkSerializer.scala:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
```
I'm using the `feature/scikit-v2` branch for the PySpark mleap libraries, Spark 2.1, and Scala 2.11.  I'm also using `mleap-spark-base_2.11-0.6.0` and `mleap-spark_2.11-0.6.0`. 

```
System.out.println(ml.combust.mleap.BuildInfo().gitSha)
System.out.println(ml.combust.mleap.BuildInfo().version)
> c522a9dd6d701d44871c85562371eda3e0dfda19
> 0.6.0-SNAPSHOT
```

Do you see anything blatently obvious that I'm missing?

**Comment by seme0021** [comment]
@clocklear,

`scikit-v2` branch is still on `0.5.0-SNAPSHOT`, which is likely the issue. I'm going to merge master into `feature/scikit-v2` which will bring it to `0.7.0-SNAPSHOT`

We'll be releasing `0.7.0` this week in case you don't want to use snapshot versions. Going forward,  MLeap Spark/PySpark/Scikit will be supported.

**Comment by clocklear** [comment]
Thanks for the quick response!

**Comment by seme0021** [comment]
K, just pushed - do you mind giving `0.7.0-SNAPSHOT` from `feature/scikit-v2` a try?

**Comment by clocklear** [comment]
I'm using Databricks to run my code and if I load the mleap libraries from Maven, dependency resolution works just fine (which is how I got 0.6.0).  However if I upload my JARs directly, none of the dependencies are automagically resolved -- tl;dr, until 0.7.0 is available in Maven, testing this (for me) is going to be a PITA.

**Comment by hollinwilkins** [comment]
@clocklear Hey there. If you are willing to use a snapshot version until the official release is out, we have it hosted on OSS Sonatype Snapshots (Maven snapshots). There should be a way to add the snapshot repo to your notebook and then have the dependencies resolve for you.

https://oss.sonatype.org/content/repositories/snapshots/ml/combust/mleap/

Let us know if this still doesn't work for you.

**Comment by clocklear** [comment]
Thanks guys. I'll check in the morning.

**Comment by clocklear** [comment]
Alright, I've managed to load `mlead-spark_2.11-0.7.0-SNAPSHOT` from Sonatype, and I'm using the latest commit from the `feature/scikit-v2` branch, but it's still failing with the same error: 

```
System.out.println(ml.combust.mleap.BuildInfo().gitSha)
System.out.println(ml.combust.mleap.BuildInfo().version)
> eacd06b8d3a755cccff0246db1329db5e034d3c0
> 0.7.0-SNAPSHOT
```

```
# Serialize the model to Bundle.ML
pipelineModel.serializeToBundle("jar:file:/dbfs/FileStore/blah2.lr.zip", dataset=rawdata)
```

```
java.lang.NoSuchMethodError: ml.bundle.BasicType.BasicType.value()I
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-27-8783bae58cc7> in <module>()
      1 # Serialize the model to Bundle.ML
----> 2 pipelineModel.serializeToBundle("jar:file:/dbfs/FileStore/blah2.lr.zip", dataset=rawdata)

/opt/libs/mleap/python/mleap/pyspark/spark_support.py in serializeToBundle(self, path, dataset)
     23 def serializeToBundle(self, path, dataset=None):
     24     serializer = SimpleSparkSerializer()
---> 25     serializer.serializeToBundle(self, path, dataset=dataset)
     26 
     27 

/opt/libs/mleap/python/mleap/pyspark/spark_support.py in serializeToBundle(self, transformer, path, dataset)
     40 
     41     def serializeToBundle(self, transformer, path, dataset):
---> 42         self._java_obj.serializeToBundle(transformer._to_java(), path, dataset._jdf)
     43 
     44     def deserializeFromBundle(self, path):

/databricks/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    317                 raise Py4JJavaError(
    318                     "An error occurred while calling {0}{1}{2}.\n".
--> 319                     format(target_id, ".", name), value)
    320             else:
    321                 raise Py4JError(

Py4JJavaError: An error occurred while calling o5306.serializeToBundle.
: java.lang.NoSuchMethodError: ml.bundle.BasicType.BasicType.value()I
	at ml.bundle.TensorType.TensorType.__computeSerializedValue(TensorType.scala:18)
	at ml.bundle.TensorType.TensorType.serializedSize(TensorType.scala:24)
	at ml.bundle.DataType.DataType.__computeSerializedValue(DataType.scala:20)
	at ml.bundle.DataType.DataType.serializedSize(DataType.scala:27)
	at ml.bundle.Attribute.Attribute.__computeSerializedValue(Attribute.scala:19)
	at ml.bundle.Attribute.Attribute.serializedSize(Attribute.scala:26)
	at ml.bundle.AttributeList.AttributeList$AttributesEntry.__computeSerializedValue(AttributeList.scala:96)
	at ml.bundle.AttributeList.AttributeList$AttributesEntry.serializedSize(AttributeList.scala:102)
	at ml.bundle.AttributeList.AttributeList$$anonfun$__computeSerializedValue$1.apply(AttributeList.scala:18)
	at ml.bundle.AttributeList.AttributeList$$anonfun$__computeSerializedValue$1.apply(AttributeList.scala:18)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at ml.bundle.AttributeList.AttributeList.__computeSerializedValue(AttributeList.scala:18)
	at ml.bundle.AttributeList.AttributeList.serializedSize(AttributeList.scala:24)
	at com.trueaccord.scalapb.GeneratedMessage$class.writeTo(GeneratedMessageCompanion.scala:34)
	at ml.bundle.AttributeList.AttributeList.writeTo(AttributeList.scala:11)
	at ml.combust.bundle.serializer.attr.AttributeListSerializer$$anonfun$writeProto$2.apply(AttributeListSerializer.scala:55)
	at ml.combust.bundle.serializer.attr.AttributeListSerializer$$anonfun$writeProto$2.apply(AttributeListSerializer.scala:54)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at scala.util.control.Exception$Catch.either(Exception.scala:125)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.bundle.serializer.attr.AttributeListSerializer.writeProto(AttributeListSerializer.scala:56)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1$$anonfun$apply$2.apply(ModelSerializer.scala:96)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1$$anonfun$apply$2.apply(ModelSerializer.scala:94)
	at scala.Option.map(Option.scala:146)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:94)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:84)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:84)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:86)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:82)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:82)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:34)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:30)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.GraphSerializer.writeNode(GraphSerializer.scala:30)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35)
	at ml.combust.bundle.serializer.GraphSerializer.write(GraphSerializer.scala:20)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:21)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:14)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:88)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:84)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:84)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:86)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:82)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:82)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:34)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:29)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.BundleSerializer.write(BundleSerializer.scala:29)
	at ml.combust.bundle.BundleWriter.save(BundleWriter.scala:27)
	at ml.combust.mleap.spark.SimpleSparkSerializer$$anonfun$serializeToBundle$2.apply(SimpleSparkSerializer.scala:21)
	at ml.combust.mleap.spark.SimpleSparkSerializer$$anonfun$serializeToBundle$2.apply(SimpleSparkSerializer.scala:20)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at scala.util.control.Exception$Catch.either(Exception.scala:125)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.mleap.spark.SimpleSparkSerializer.serializeToBundle(SimpleSparkSerializer.scala:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by seme0021** [comment]
Hrm ... I just went through the [demo code](https://github.com/combust/mleap-demo/blob/master/notebooks/PySpark%20-%20AirBnb.ipynb) with Logistic Regression and it worked for me.

Can you share a bit more code on what `pipelineModel` is, if you're fun `.fit()` on it before calling `.serializeToBundle()` and what feature transformers you're using?

**Comment by clocklear** [comment]
Here's our code.  Apologies for the verbosity!

```
# All of the imports we need and read in the rawdata
import jpmml_sparkml as jpmml
import math
import pandas as pd
from pyspark import SparkContext
from pyspark.sql import SQLContext
from pyspark.ml.feature import OneHotEncoder, StringIndexer, StandardScaler, VectorAssembler
from pyspark.ml import Pipeline, PipelineModel
from pyspark.ml.classification import RandomForestClassifier, LogisticRegression
from pyspark.ml.regression import RandomForestRegressor
from pyspark.ml.feature import VectorIndexer
from pyspark.ml.evaluation import RegressionEvaluator
from pyspark.sql.functions import col, avg, when, count
from pyspark.sql.types import DoubleType, DataType
rawdata = sqlContext.read.format('csv').options(header='true', inferSchema='true').load('data.csv')
rawdata = rawdata.persist()

# Drop ignore columns
responsevariable = 'HasOrdered'
ignorecolumns = ['CallID', 'CallDateTime', 'PredictedLTV', 'ZipCode_GeoIP', 'BAUPriority']
for column in ignorecolumns:
  rawdata = rawdata.drop(column)

# clean up missing values in rawdata
for column in rawdata.schema.fields:
    columntype = str(column.dataType)
    if columntype != 'StringType':
        rawdata = rawdata.na.fill(rawdata.na.drop().agg(avg(column.name)).first()[0], [column.name])
    else:
        rawdata = rawdata.na.fill('Unknown', [column.name])

# Create vectors of categorical and numeric columns
categoricalcolumns = []
numericcolumns = []
for i in range(rawdata.columns.__len__()):
  column = rawdata.schema.fields[i]
  columnname = rawdata.columns[i]
  columntype = str(column.dataType)
  if columntype == 'StringType':
    categoricalcolumns.append(columnname)
  elif columnname != responsevariable:
    numericcolumns.append(columnname)
  else:
    continue

# Code taken from Databricks with the purpose of building a pipeline. This part handles categoricals
cols = rawdata.columns
categoricalColumns = categoricalcolumns
stages = [] # stages in our Pipeline
for categoricalCol in categoricalColumns:
  # Category Indexing with StringIndexer
  stringIndexer = StringIndexer(inputCol=categoricalCol, outputCol=categoricalCol+"Index")
  # Use OneHotEncoder to convert categorical variables into binary SparseVectors
  encoder = OneHotEncoder(inputCol=categoricalCol+"Index", outputCol=categoricalCol+"classVec")
  # Add stages.  These are not run here, but will run all at once later on.
  stages += [stringIndexer, encoder]

label_stringIdx = StringIndexer(inputCol = responsevariable, outputCol = "label")
stages += [label_stringIdx]

# Transform all features into a vector using VectorAssembler
numericCols = numericcolumns
assemblerInputs = map(lambda c: c + "classVec", categoricalColumns) + numericCols
assembler = VectorAssembler(inputCols=assemblerInputs, outputCol="features")
stages += [assembler]

# Split data into training / test
(trainingdata, testdata) = rawdata.randomSplit([0.7, 0.3], seed=15)

# Create initial LogisticRegression model
lr = LogisticRegression(labelCol="label", featuresCol="features", maxIter=10)
stages += [lr]
pipeline = Pipeline(stages=stages)

# Fit the model
pipelineModel = pipeline.fit(trainingdata)
```

```
%sh
mkdir -p /opt/libs
if [ ! -d /opt/libs/mleap ]; then
  git clone https://github.com/combust/mleap.git /opt/libs/mleap
fi
echo "Changing to mleap source directory..."
cd /opt/libs/mleap
echo "Fetching remote branches..."
git fetch
echo "Checking out feature/scikit-v2..."
git checkout feature/scikit-v2
echo "Pulling repo updates..."
git pull
echo "Done"
```

```
# Include newly downloaded mleap lib into python environment
import sys
sys.path.append('/opt/libs/mleap/python')
import mleap.pyspark

from mleap.pyspark.spark_support import SimpleSparkSerializer

# Serialize the model to Bundle.ML
pipelineModel.serializeToBundle("jar:file:/dbfs/FileStore/blah2.lr.zip", dataset=rawdata)
```

**Comment by seme0021** [comment]
Thanks for the code, we'll take a look later today!

**Comment by clocklear** [comment]
@seme0021 Once I was able to find a working copy of the airbnb dataset, I ran through the airbnb pyspark example, and while it doesn't throw any errors, it doesn't produce a valid zipfile.  The bundle artifact is only 22 bytes -- empty.

**Comment by seme0021** [comment]
I'm going to try running on Databricks to see if we can replicate the issue.

@hollinwilkins can you take another look at the original `ava.lang.NoSuchMethodError: ml.bundle.BasicType.BasicType.value()I` error?

**Comment by seme0021** [comment]
@clocklear How did you add `0.7.0-SNAPSHOT` to databricks? I'm not able to figure it out.

However, I did get it to run with `0.6.0` and get a non-empty bundle file - [here](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/4490057271505260/2409125929381347/3746798320046689/latest.html) is a public version of that notebook

**Comment by seme0021** [comment]
Never mind, figured out how to add `0.7.0-SNAPSHOTS`

**Comment by seme0021** [comment]
@clocklear we're planning on releasing 0.7.0 today, but would like to be able to resolve your issue. Can you shoot me and Hollin an email and we can set up sometime to video conference and try to debug live. 

mikhail at combust.ml and hollin at combust.ml

**Comment by clocklear** [comment]
Thanks for the support guys.  I'll send you an email.

**Comment by clocklear** [comment]
For anyone wandering down this road, this was caused by my Spark environment (Databricks) running an earlier version of scalapb than what MLeap needs, so I needed to build a fat JAR with a shaded version of scalapb baked into it, which allowed me to work past the version differences.
