### ISSUE TITLE
Issue with scoring the Pyspark Airbnb example

### ISSUE THREAD

**Issue by clocklear** [combust/mleap#209]
We utilized the Airbnb Pyspark example [here](https://github.com/combust/mleap-demo/blob/master/notebooks/PySpark%20-%20AirBnb.ipynb), and were able to produce a MLeap model (as a zipfile).  We took that MLeap model over to our in-house Scala scoring application, got it loaded up, were able to create a LeapFrame from the sample JSON (located [here](https://s3-us-west-2.amazonaws.com/mleap-demo/frame.airbnb.json)), but we're getting an exception when we attempt to transform the frame:

```
"java.lang.ArrayIndexOutOfBoundsException: 1",
      "at scala.collection.mutable.WrappedArray$ofRef.apply(WrappedArray.scala:127)",
      "at ml.combust.mleap.runtime.ArrayRow.get(Row.scala:277)",
      "at ml.combust.mleap.runtime.RowUtil$$anonfun$createRowSelector$2$$anonfun$apply$4$$anonfun$apply$5.apply(RowUtil.scala:58)",
      "at ml.combust.mleap.runtime.RowUtil$$anonfun$createRowSelector$2$$anonfun$apply$4$$anonfun$apply$5.apply(RowUtil.scala:58)",
      "at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)",
      "at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)",
      "at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)",
      "at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)",
      "at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)",
      "at scala.collection.AbstractTraversable.map(Traversable.scala:104)",
      "at ml.combust.mleap.runtime.RowUtil$$anonfun$createRowSelector$2$$anonfun$apply$4.apply(RowUtil.scala:58)",
      "at ml.combust.mleap.runtime.RowUtil$$anonfun$createRowSelector$2$$anonfun$apply$4.apply(RowUtil.scala:58)",
      "at ml.combust.mleap.runtime.Row$class.udfValue(Row.scala:223)",
      "at ml.combust.mleap.runtime.ArrayRow.udfValue(Row.scala:274)",
      "at ml.combust.mleap.runtime.Row$class.withValue(Row.scala:208)",
      "at ml.combust.mleap.runtime.ArrayRow.withValue(Row.scala:274)",
      "at ml.combust.mleap.runtime.Dataset$$anonfun$withValue$1.apply(Dataset.scala:32)",
      "at ml.combust.mleap.runtime.Dataset$$anonfun$withValue$1.apply(Dataset.scala:32)",
      "at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)",
      "at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)",
      "at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:73)",
      "at scala.collection.mutable.MutableList.foreach(MutableList.scala:30)",
      "at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)",
      "at scala.collection.AbstractTraversable.map(Traversable.scala:104)",
      "at ml.combust.mleap.runtime.LocalDataset.update(LocalDataset.scala:19)",
      "at ml.combust.mleap.runtime.LocalDataset.update(LocalDataset.scala:13)",
      "at ml.combust.mleap.runtime.Dataset$class.withValue(Dataset.scala:32)",
      "at ml.combust.mleap.runtime.LocalDataset.withValue(LocalDataset.scala:13)",
      "at ml.combust.mleap.runtime.LeapFrame$$anonfun$withField$1$$anonfun$apply$2.apply(LeapFrame.scala:74)",
      "at ml.combust.mleap.runtime.LeapFrame$$anonfun$withField$1$$anonfun$apply$2.apply(LeapFrame.scala:73)",
      "at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)",
      "at scala.util.Try$.apply(Try.scala:192)",
      "at scala.util.Success.map(Try.scala:237)",
      "at ml.combust.mleap.runtime.LeapFrame$$anonfun$withField$1.apply(LeapFrame.scala:72)",
      "at ml.combust.mleap.runtime.LeapFrame$$anonfun$withField$1.apply(LeapFrame.scala:71)",
      "at scala.util.Success.flatMap(Try.scala:231)",
      "at ml.combust.mleap.runtime.LeapFrame$class.withField(LeapFrame.scala:70)",
      "at ml.combust.mleap.runtime.DefaultLeapFrame.withField(DefaultLeapFrame.scala:10)",
      "at ml.combust.mleap.runtime.LeapFrame$class.withOutput(LeapFrame.scala:127)",
      "at ml.combust.mleap.runtime.DefaultLeapFrame.withOutput(DefaultLeapFrame.scala:10)",
      "at ml.combust.mleap.runtime.transformer.feature.VectorAssembler.transform(VectorAssembler.scala:21)",
      "at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:13)",
      "at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:13)",
      "at scala.util.Success.flatMap(Try.scala:231)",
      "at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:13)",
      "at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:13)",
      "at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)",
      "at scala.collection.immutable.List.foldLeft(List.scala:84)",
      "at ml.combust.mleap.runtime.transformer.Pipeline.transform(Pipeline.scala:13)",
      "at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:13)",
      "at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:13)",
      "at scala.util.Success.flatMap(Try.scala:231)",
      "at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:13)",
      "at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:13)",
      "at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)",
      "at scala.collection.immutable.List.foldLeft(List.scala:84)",
      "at ml.combust.mleap.runtime.transformer.Pipeline.transform(Pipeline.scala:13)",
      "at com.redventures.databroker.models.MleapLibrary.evaluate(MleapLibrary.scala:148)",
      "at com.redventures.databroker.controllers.MleapController$$anonfun$evaluateScoringRequest$1.apply(MleapController.scala:77)",
      "at com.redventures.databroker.controllers.MleapController$$anonfun$evaluateScoringRequest$1.apply(MleapController.scala:42)",
      "at scalaz.$bslash$div.fold(Either.scala:57)",
      "at scalaz.EitherT$$anonfun$fold$1.apply(EitherT.scala:31)",
      "at scalaz.EitherT$$anonfun$fold$1.apply(EitherT.scala:31)",
      "at scalaz.Monad$$anonfun$map$1$$anonfun$apply$2.apply(Monad.scala:14)",
      "at scalaz.concurrent.Task$.Try(Task.scala:403)",
      "at scalaz.concurrent.Task$$anon$1$$anonfun$point$1.apply(Task.scala:237)",
      "at scalaz.concurrent.Task$$anon$1$$anonfun$point$1.apply(Task.scala:237)",
      "at scalaz.concurrent.Future$$anonfun$delay$1.apply(Future.scala:350)",
      "at scalaz.concurrent.Future$$anonfun$delay$1.apply(Future.scala:350)",
      "at scalaz.concurrent.Future.step(Future.scala:110)",
      "at scalaz.concurrent.Future.listen(Future.scala:75)",
      "at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79)",
      "at scalaz.concurrent.Future$$anonfun$listen$1$$anonfun$apply$4.apply(Future.scala:79)",
      "at scalaz.Free$$anonfun$map$1.apply(Free.scala:53)",
      "at scalaz.Free$$anonfun$map$1.apply(Free.scala:53)",
      "at scalaz.Free.scalaz$Free$$fastFlatMap(Free.scala:72)",
      "at scalaz.Free$$anonfun$resume$1.apply(Free.scala:88)",
      "at scalaz.Free$$anonfun$resume$1.apply(Free.scala:88)",
      "at scalaz.std.FunctionInstances$$anon$1$$anonfun$map$1.apply(Function.scala:56)",
      "at scalaz.Free$$anonfun$run$1.apply(Free.scala:187)",
      "at scalaz.Free$$anonfun$run$1.apply(Free.scala:187)",
      "at scalaz.Free.go2$1(Free.scala:134)",
      "at scalaz.Free.go(Free.scala:137)",
      "at scalaz.Free.run(Free.scala:187)",
      "at scalaz.concurrent.Future$$anonfun$apply$15$$anon$4.call(Future.scala:380)",
      "at scalaz.concurrent.Future$$anonfun$apply$15$$anon$4.call(Future.scala:380)",
      "at java.util.concurrent.FutureTask.run(FutureTask.java:266)",
      "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)",
      "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)",
      "at java.lang.Thread.run(Thread.java:745)"
```

Any ideas?

**Comment by clocklear** [comment]
Here's the model we built:
[pyspark-mleap-airbnb.lr.zip](https://github.com/combust/mleap/files/994188/pyspark-mleap-airbnb.lr.zip)

**Comment by hollinwilkins** [comment]
@clocklear It looks like the LeapFrame may not have loaded properly. Can you debug it with a .show() and see what happens? What JSON file are you using?

**Comment by hollinwilkins** [comment]
NM, I see you linked to the file. Let me look closer at this.

**Comment by clocklear** [comment]
We stepped into where the exception is being thrown -- at that point in the execution, it has narrowed the scope down to a single row (the collection has a single row in it), but for some reason it's trying to access the element at index 1 (so, position 2).

**Comment by jacobfoard** [comment]
I was able to score the AirBnB Row, the way we were creating our LeapFrame to score wasn't using the ml.combust.mleap.runtime.serialization.FrameReader, I added that in and passed the LeapFrame generated by it and was able to score the model. We still have an issue with a model we've built, however that is probably a different issue.

**Comment by jacobfoard** [comment]
Following back up on this we were able to use our scoring method and what ended up happening was we were creating a `Row()` with a `Seq[Object]` and it in turn created an `ArrayRow[Row[Any]]` when what we really needed to happen was create a single `ArrayRow` with the values from that sequence.

**Comment by hollinwilkins** [comment]
@jacobfoard Sounds like this issue was resolved? And just to understand, the issue was because the constructor for a Row expects splat arguments instead of a Seq, but you were passing a Seq?

**Comment by jacobfoard** [comment]
Yep this issue is a resolved, and yea the problem was that I couldn't pass the values in the Seq to the Row constructor, so passing in the Seq to ArrayRow fix the issue we were having where the values were nested.

**Comment by hollinwilkins** [comment]
@jacobfoard Great! I will close this issue then.
