### ISSUE TITLE
input leapframe only supports double type for number?

### ISSUE THREAD

**Issue by gm3000** [combust/mleap#212]
hi,
Just successfully went through serializing and serializing my spark trained model, and serve it.
Love your work and thumb!
Anyway, I still met something I don`t understand, which is probably an issue:
1. loaded my bundle to the official docker [combustml/mleap-serving   0.8.0-SNAPSHOT].
2. Post my data.json, which contans fields with "integer" type
500 server error:
`[ERROR] [05/24/2017 08:12:22.431] [MleapServing-akka.actor.default-dispatcher-115] [MleapResource] error with request
scala.MatchError: 0 (of class java.lang.Integer)
        at ml.combust.mleap.core.feature.VectorAssemblerModel$$anonfun$apply$3.apply(VectorAssemblerModel.scala:33)
        at ml.combust.mleap.core.feature.VectorAssemblerModel$$anonfun$apply$3.apply(VectorAssemblerModel.scala:33)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at ml.combust.mleap.core.feature.VectorAssemblerModel.apply(VectorAssemblerModel.scala:33)
        at ml.combust.mleap.runtime.transformer.feature.VectorAssembler$$anonfun$1.apply(VectorAssembler.scala:20)
        at ml.combust.mleap.runtime.transformer.feature.VectorAssembler$$anonfun$1.apply(VectorAssembler.scala:20)
        at ml.combust.mleap.runtime.Row$class.udfValue(Row.scala:223)
        at ml.combust.mleap.runtime.ArrayRow.udfValue(Row.scala:274)
        at ml.combust.mleap.runtime.Row$class.withValue(Row.scala:208)
        at ml.combust.mleap.runtime.ArrayRow.withValue(Row.scala:274)
        at ml.combust.mleap.runtime.Dataset$$anonfun$withValue$1.apply(Dataset.scala:32)
        at ml.combust.mleap.runtime.Dataset$$anonfun$withValue$1.apply(Dataset.scala:32)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at ml.combust.mleap.runtime.LocalDataset.update(LocalDataset.scala:19)
        at ml.combust.mleap.runtime.LocalDataset.update(LocalDataset.scala:13)
        at ml.combust.mleap.runtime.Dataset$class.withValue(Dataset.scala:32)
        at ml.combust.mleap.runtime.LocalDataset.withValue(LocalDataset.scala:13)
        at ml.combust.mleap.runtime.LeapFrame$$anonfun$withField$1$$anonfun$apply$2.apply(LeapFrame.scala:74)
        at ml.combust.mleap.runtime.LeapFrame$$anonfun$withField$1$$anonfun$apply$2.apply(LeapFrame.scala:73)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at ml.combust.mleap.runtime.LeapFrame$$anonfun$withField$1.apply(LeapFrame.scala:72)
        at ml.combust.mleap.runtime.LeapFrame$$anonfun$withField$1.apply(LeapFrame.scala:71)
        at scala.util.Success.flatMap(Try.scala:231)
        at ml.combust.mleap.runtime.LeapFrame$class.withField(LeapFrame.scala:70)
        at ml.combust.mleap.runtime.DefaultLeapFrame.withField(DefaultLeapFrame.scala:10)
        at ml.combust.mleap.runtime.LeapFrame$class.withOutput(LeapFrame.scala:127)
        at ml.combust.mleap.runtime.DefaultLeapFrame.withOutput(DefaultLeapFrame.scala:10)
        at ml.combust.mleap.runtime.transformer.feature.VectorAssembler.transform(VectorAssembler.scala:23)
        at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:14)
        at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:14)
        at scala.util.Success.flatMap(Try.scala:231)
        at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:14)
        at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:14)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at ml.combust.mleap.runtime.transformer.Pipeline.transform(Pipeline.scala:14)
        at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:14)
        at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:14)
        at scala.util.Success.flatMap(Try.scala:231)
        at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:14)
        at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:14)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at ml.combust.mleap.runtime.transformer.Pipeline.transform(Pipeline.scala:14)
        at ml.combust.mleap.serving.MleapService$$anonfun$transform$1.apply(MleapService.scala:42)
        at ml.combust.mleap.serving.MleapService$$anonfun$transform$1.apply(MleapService.scala:42)
        at scala.Option.map(Option.scala:146)
        at ml.combust.mleap.serving.MleapService.transform(MleapService.scala:41)
        at ml.combust.mleap.serving.MleapResource$$anonfun$1$$anonfun$apply$1$$anonfun$apply$5$$anonfun$apply$14$$anonfun$apply$15$$anonfun$apply$16$$anonfun$apply$17.apply(MleapResource.scala:52)
        at ml.combust.mleap.serving.MleapResource$$anonfun$1$$anonfun$apply$1$$anonfun$apply$5$$anonfun$apply$14$$anonfun$apply$15$$anonfun$apply$16$$anonfun$apply$17.apply(MleapResource.scala:52)
        at akka.http.scaladsl.server.directives.RouteDirectives$$anonfun$complete$1.apply(RouteDirectives.scala:47)
        at akka.http.scaladsl.server.directives.RouteDirectives$$anonfun$complete$1.apply(RouteDirectives.scala:47)
        at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
        at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
        at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$mapRouteResult$1$$anonfun$apply$3.apply(BasicDirectives.scala:61)
        at akka.http.scaladsl.server.directives.BasicDirectives$$anonfun$mapRouteResult$1$$anonfun$apply$3.apply(BasicDirectives.scala:61)
        at akka.http.scaladsl.server.directives.FutureDirectives$$anonfun$onComplete$1$$anonfun$apply$1$$anonfun$apply$2.apply(FutureDirectives.scala:37)
        at akka.http.scaladsl.server.directives.FutureDirectives$$anonfun$onComplete$1$$anonfun$apply$1$$anonfun$apply$2.apply(FutureDirectives.scala:37)
        at akka.http.scaladsl.util.FastFuture$$anonfun$transformWith$extension0$1.apply(FastFuture.scala:37)
        at akka.http.scaladsl.util.FastFuture$$anonfun$transformWith$extension0$1.apply(FastFuture.scala:37)
        at akka.http.scaladsl.util.FastFuture$.akka$http$scaladsl$util$FastFuture$$strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$$anonfun$transformWith$extension1$1.apply(FastFuture.scala:51)
        at akka.http.scaladsl.util.FastFuture$$anonfun$transformWith$extension1$1.apply(FastFuture.scala:50)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

Then I found that in VectorAssemblerModel:33
there is not Match/Case for Integer.
Then I change the data.json with updating all "integer" to "double", and pass with 200 OK.

Is this an issue? or by design which was not mentioned in the doc or some where.

**Comment by hollinwilkins** [comment]
Hey, I think that MLeap does only support a certain set of inputs for the VectorAssembler. Spark VectorAssembler casts all numeric types to Double first, but MLeap doesn't have that capability yet.

Here are the supported types at the moment:
Double
MLeap Tensor
Spark Vector
Option[Double]
BigDecimal

I think MLeap is at a point where casting would be very useful. I already added in the ability to get access to the schema during transformation, which is the first step in this process.

Once we have casting, we can cast any numeric inputs to a double before sending it into the vector assembler.

**Comment by hollinwilkins** [comment]
This should be fixed with automatic casting. VectorAssembler should be able to take boolean, short, int, byte, long, float, double and string even.
