### ISSUE TITLE
NoSuchElementException: key not found: org.apache.spark.ml.feature.OneHotEncoder

### ISSUE THREAD

**Issue by smaxwellstewart** [combust/mleap#220]
I am getting this error when trying to serialize my spark pipeline. I am working in databricks with scala 2.11. Am i missing a library or something? 

```scala
import org.apache.spark.ml.{Pipeline, PipelineStage}
import org.apache.spark.ml.feature.{OneHotEncoder, StringIndexer, VectorAssembler}
import org.apache.spark.sql._
import spark.implicits._

// categorical cols
val stringCols = Array("countryCode",  "referrer_domain", "browser")
val indexCols = Array("siteId", "adv_id")

// numeric cols
val numericCols = Array("position", "position_squared", "position_inverse")

// transform dataframe...
var stages = Array[PipelineStage]()


// index the string columns
for(c <- stringCols) {
  stages = stages :+ new StringIndexer()
                    .setInputCol(c)
                    .setOutputCol(c+"Index")
                    .setHandleInvalid("skip")
}

// One hot encode the index cols into vectors
val encodeCols = stringCols.map(name => name + "Index") ++ indexCols
for(c <- encodeCols) {
  stages = stages :+ new OneHotEncoder()
                    .setInputCol(c)
                    .setOutputCol(c+"Vec")
}

// assemble the different cols into a feature vector
stages = stages :+ new VectorAssembler()
                  .setInputCols(numericCols ++ encodeCols.map(x => x+"Vec"))
                  .setOutputCol("features")

// create pipeline of all the trasformers to our features
val featurePipeline = new Pipeline()
                      .setStages(stages)
                      .fit(training)

// train a model
import org.apache.spark.ml.classification.LogisticRegression

val lr = new LogisticRegression()
  .setLabelCol("clicked")
  .setFeaturesCol("features")
  .setMaxIter(1) // TODO! Increase when in prod
  .setRegParam(0.05) // NOTE! value supplied by data science
  .setElasticNetParam(0.01) // NOTE! value supplied by data science

val lrModel = lr.fit(featurePipeline.transform(training))

// serialize to tmp storage
import org.apache.spark.ml.bundle.SparkBundleContext
import ml.combust.bundle.BundleFile
import ml.combust.bundle.serializer.SerializationFormat
import org.apache.spark.ml.mleap.SparkUtil
import ml.combust.mleap.spark.SparkSupport._
import resource._

// create MLeap pipeline that will transform data
val pipeline = SparkUtil.createPipelineModel(Array(featurePipeline, lrModel))

implicit val context = SparkBundleContext().withDataset(featurePipeline.transform(training))

// serialize pipeline to tmp storage
(for(bundle <- managed(BundleFile("jar:file:/tmp/model.zip"))) yield {
  pipeline.writeBundle.format(SerializationFormat.Json).save(bundle)(context).get
}).tried.get
```

This is the error i get:

```
java.util.NoSuchElementException: key not found: org.apache.spark.ml.feature.OneHotEncoder
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at ml.combust.bundle.BundleRegistry.opForObj(BundleRegistry.scala:100)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:31)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:30)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.GraphSerializer.writeNode(GraphSerializer.scala:30)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35)
	at ml.combust.bundle.serializer.GraphSerializer.write(GraphSerializer.scala:20)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:21)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:14)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:88)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:84)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:84)
        ...
```

**Comment by hollinwilkins** [comment]
@smaxwellstewart Can you please provide the following information:

1. MLeap version
2. Spark version
3. How you are loading your dependencies (if you are on databricks, just a snapshot of your dependencies on the cluster would suffice)

Thank you!

**Comment by smaxwellstewart** [comment]
1. MLeap 2.11
2. Spark 2.1
3. See image
<img width="1165" alt="screen shot 2017-06-01 at 2 28 23 pm" src="https://cloud.githubusercontent.com/assets/4520386/26694800/ab0e004a-46d6-11e7-908c-baa7f0394190.png">

**Comment by hollinwilkins** [comment]
@smaxwellstewart Because you are using MLeap spark extension, we have our own one hot encoder that you need to use.

If you still want to use the builtin OneHotEncoder, then you would need to configure the Bundle registry to use that builtin one hot encoder instead of the one provided in mleap spark extensions.

I know that's probably as clear as mud, but an easy fix (if you aren't using anything in MLeap Spark extension) is to just use mleap-spark instead of mleap-spark-extension.

**Comment by smaxwellstewart** [comment]
Ok yeah I have no issue using your one hot encoder, but could you give clear instructions on how to use it. Do i simply detach the spark exension? Do I need to import your One Hot Encoder from a special place.

**Comment by hollinwilkins** [comment]
@smaxwellstewart Hey, our one hot encoder can be found at: org.apache.spark.ml.mleap.feature.OneHotEncoder

This is good feedback, we will build a section into our docs about this problem. Also, moving forward I would like MLeap to support multiple serializers for the same model, so this would be a non-issue to begin with.

Let us know if you run into anything else!

**Comment by smaxwellstewart** [comment]
Ahhhhh thank you!

I think it's working now.

**Comment by Gaurav7296** [comment]
> @smaxwellstewart Because you are using MLeap spark extension, we have our own one hot encoder that you need to use.
> 
> If you still want to use the builtin OneHotEncoder, then you would need to configure the Bundle registry to use that builtin one hot encoder instead of the one provided in mleap spark extensions.
> 
> I know that's probably as clear as mud, but an easy fix (if you aren't using anything in MLeap Spark extension) is to just use mleap-spark instead of mleap-spark-extension.

@hollinwilkins tried this, I am using built-in oneHotEncoder , still getting the same error.
