### ISSUE TITLE
FatalError in scala-reflect when using MLeap in a Jupyter notebook

### ISSUE THREAD

**Issue by matw** [combust/mleap#238]
Hi. Great project! I enjoyed seeing your joint presentation with Pachyderm at Spark Summit this past June.

I'm getting a FatalError when I try to use MLeap 0.7.0 in a Jupyter notebook with SparkMagic on an Azure HDInsight 3.6 cluster (Livy 0.3.0, Spark 2.1.0).

More details below, but at a high level, is it possible that MLeap depends on an earlier version of scala-reflect?

Some specifics:

- Happens regardless of whether I use the Jupyter notebook hosted locally or remotely on the HDInsight cluster
- Does NOT happen, however, if instead I assemble a JAR using SBT and submit that through Livy (i.e. I'm then able to import from MLeap)
- So the issue seems specific to using a Jupyter notebook, where blocks of code gets submitted to Livy

Here's the first cell of my notebook:

```
%%configure -f
{"conf": {"spark.jars.packages": "ml.combust.mleap:mleap-spark_2.11:0.7.0"}}
```

After running a simple 1 + 1 example in the next cell, which attempts to start the Spark session, the job fails due to a fatal error. Crucially, I don't get the error when I either (1) don't specify any dependencies, or (2) specify a different dependency (e.g. OpenNLP).

From the YARN log: 

```
ERROR ApplicationMaster: User class threw exception: scala.reflect.internal.FatalError: object Predef does not have a member classOf
```

The logs indicate that the various MLeap JARs were downloaded.

I found some discussion in the HDInsight and Livy projects that appears relevant.

Azure HDInsight discussion thread:
https://github.com/hdinsight/spark-eventhubs/issues/80

Issue in Livy:
https://issues.cloudera.org/browse/LIVY-323

Commit with workaround coming in Livy 0.4.0:
https://github.com/cloudera/livy/commit/07f6072f9d90ec970a1f9fbaccf0452f3a783538

The comment in at that last link is this:

> Some Spark packages are depending on scala-reflect 2.11.0 and it conflicts with Spark's scala version 2.11.8. This's not Livy's fault actually but doesn't hurt to make Livy more fault tolerant.

For what it's worth, here's the stack trace from my YARN log:

```
17/07/06 19:44:50 ERROR ApplicationMaster: User class threw exception: scala.reflect.internal.FatalError: object Predef does not have a member classOf
scala.reflect.internal.FatalError: object Predef does not have a member classOf
	at scala.reflect.internal.Definitions$DefinitionsClass.scala$reflect$internal$Definitions$DefinitionsClass$$fatalMissingSymbol(Definitions.scala:1186)
	at scala.reflect.internal.Definitions$DefinitionsClass.getMember(Definitions.scala:1203)
	at scala.reflect.internal.Definitions$DefinitionsClass.getMemberMethod(Definitions.scala:1238)
	at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.Predef_classOf$lzycompute(Definitions.scala:1469)
	at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.Predef_classOf(Definitions.scala:1469)
	at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.isPredefClassOf(Definitions.scala:1459)
	at scala.tools.nsc.typechecker.Typers$Typer.typedIdent$2(Typers.scala:4885)
	at scala.tools.nsc.typechecker.Typers$Typer.typedIdentOrWildcard$1(Typers.scala:4908)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5340)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5360)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5472)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5480)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5012)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5312)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5359)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5448)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:440)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:431)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:440)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1501)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1486)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
	at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:435)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compileAndSaveRun(IMain.scala:855)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:813)
	at scala.tools.nsc.interpreter.IMain.bind(IMain.scala:675)
	at com.cloudera.livy.repl.SparkInterpreter$$anonfun$bind$1.apply(SparkInterpreter.scala:129)
	at com.cloudera.livy.repl.SparkInterpreter$$anonfun$bind$1.apply(SparkInterpreter.scala:129)
	at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:214)
	at com.cloudera.livy.repl.SparkInterpreter.bind(SparkInterpreter.scala:128)
	at com.cloudera.livy.repl.SparkContextInitializer$class.spark2CreateContext(SparkContextInitializer.scala:109)
	at com.cloudera.livy.repl.SparkContextInitializer$class.createSparkContext(SparkContextInitializer.scala:34)
	at com.cloudera.livy.repl.SparkInterpreter.createSparkContext(SparkInterpreter.scala:36)
	at com.cloudera.livy.repl.SparkInterpreter$$anonfun$start$1.apply$mcV$sp(SparkInterpreter.scala:89)
	at com.cloudera.livy.repl.SparkInterpreter$$anonfun$start$1.apply(SparkInterpreter.scala:68)
	at com.cloudera.livy.repl.SparkInterpreter$$anonfun$start$1.apply(SparkInterpreter.scala:68)
	at com.cloudera.livy.repl.AbstractSparkInterpreter.restoreContextClassLoader(AbstractSparkInterpreter.scala:256)
	at com.cloudera.livy.repl.SparkInterpreter.start(SparkInterpreter.scala:68)
	at com.cloudera.livy.repl.Session$$anonfun$1.apply(Session.scala:76)
	at com.cloudera.livy.repl.Session$$anonfun$1.apply(Session.scala:74)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
17/07/06 19:44:50 INFO ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: scala.reflect.internal.FatalError: object Predef does not have a member classOf)
```

**Comment by hollinwilkins** [comment]
@matw Thank you for the issue report. Would this be solved simply by updating our scala-reflect dependency? This is the first time seeing this error on any environment.

**Comment by prianna** [comment]
@hollinwilkins This seems to be the same issue we encountered in our environment.

**Comment by prianna** [comment]
@hollinwilkins Seems that we resolved this by excluding `"org.scala-lang:scala-reflect,org.apache.spark:spark-tags_2.11"` in Livy.

**Comment by matw** [comment]
@hollinwilkins @prianna Turns out if I build MLeap 0.7.0 locally, then I no longer get the error -- even without changing any dependencies. I use the resulting artifacts by specifying the packaged JARs in the first Jupyter cell like so:

```
%%configure -f
{"conf": {
  "spark.jars": "wasbs://<container-name>@<account-name>.blob.core.windows.net/bundle-ml_2.11-0.7.0.jar,wasbs://<container-name>@<account-name>.blob.core.windows.net/mleap-base_2.11-0.7.0.jar,wasbs://<container-name>@<account-name>.blob.core.windows.net/mleap-core_2.11-0.7.0.jar,wasbs://<container-name>@<account-name>.blob.core.windows.net/mleap-runtime_2.11-0.7.0.jar,wasbs://<container-name>@<account-name>.blob.core.windows.net/mleap-spark_2.11-0.7.0.jar,wasbs://<container-name>@<account-name>.blob.core.windows.net/mleap-spark-base_2.11-0.7.0.jar"
}}
```

(The above approach requires uploading those JARs to a container in my Azure storage account. I haven't tried building an uber-JAR to avoid listing the various artifacts, but I assume that would work too.)

So this gives me another workaround. Alternatively, I can download the necessary artifacts from https://mvnrepository.com/artifact/ml.combust.mleap and then upload those to my Azure storage account. That appears to work as well.

To clarify, then, I only get the error when allowing Livy to obtain the dependencies. Unfortunately that's the most convenient way for me to use MLeap in Jupyter. (Since I'm using an Azure HDInsight cluster, I'm at the mercy of their version of Livy.) That said, the workarounds mentioned here are good enough for me for now.

I'm not clear on where Livy gets their MLeap artifacts from. Looking at the top-level POM in the Livy project, I see they get third-party libraries from the JBoss repository. But http://repository.jboss.org/nexus/content/groups/public/ml/combust/mleap/ only has MLeap versions 0.6.0 and 0.8.0, not 0.7.0.

**Comment by matw** [comment]
@prianna I just revisited this. I now see what you were suggesting. Indeed I can bring MLeap into a Jupyter notebook without error by excluding the scala-reflect and spark-tags artifacts.

Specifically, my first cell includes:

```
%%configure -f
{"conf": {  
  "spark.jars.packages": "ml.combust.mleap:mleap-spark_2.11:0.7.0",
  "spark.jars.excludes": "org.scala-lang:scala-reflect,org.apache.spark:spark-tags_2.11"
}}
```

Once Livy 0.4 is released (and, for those on Azure, when HDInsight starts using it), then I believe this exclusion will no longer be necessary.

**Comment by hollinwilkins** [comment]
@matw Closing this issue as resolved for now. Reopen if you think it should still be open!

**Comment by spaszek** [comment]
Has anyone been albe to tackle this issue(the Scala exception in scala-reflect)? Was it fixed in the newest version of Livy?

I'm running into the same problem using Spark 2.2 and Livy 0.3 (with different package though - I'm trying to add `ml.dmlc.xgdboost-jvm`). I uploaded jars to HDFS and Livy correctly adds them on session startup. That however triggers the `scala.reflect.internal.FatalError: object Predef does not have a member classOf` and Spark Session fails to initialize.

**Comment by david-espinosa** [comment]
I'm having this error using Spark 2.2.1, scala 2.11.12 and Livy 0.5
Anybody was successful on fixing this?

**Comment by ikiw** [comment]
@spaszek : were you able to resolve it ? i too get the same issue on adding xgdboost.

**Comment by a524631266** [comment]
I have solved it by adding the jar package of  scala-library-2.11.12.jar into the LivyConfig
such as:
in $LIVY_HOME/conf
livy.repl.jars = ****.jar(some jars),~/spark-2.4.0-bin-hadoop2.6/jars/scala-library-2.11.12.jar
