### ISSUE TITLE
Got an exception when using mleapModel to transform a spark dataframe

### ISSUE THREAD

**Issue by wyFTD** [combust/mleap#243]
According to the tutorial，I made a simple project. However I got a `org.apache.spark.sql.AnalysisException`
This is my code:
```
import org.apache.spark.sql.SparkSession

val spark = SparkSession.builder.master("local").appName("Simple Application").getOrCreate()

// Step l, Load DataFrame, just 2 classes [0, 1]
val data = spark.read.format("libsvm").load("src/data/sample_libsvm_data.txt") // you can find the data in spark
val Array(trainingData, testData, testData_) = data.randomSplit(Array(0.8, 0.1, 0.1))
println("trainingData size is: " + trainingData.count + ", testData size is:" + testData.count)


// Step 2, Feature Selection, Classification Model and make a pipeline
import org.apache.spark.ml.feature.PCA
val pca = new PCA(uid = "pca").setInputCol("features").setK(50).setOutputCol("pca_features")

import org.apache.spark.ml.classification.LogisticRegression
val lr = new LogisticRegression(uid = "lr").setMaxIter(10).setRegParam(0.3).setElasticNetParam(0.8).setFeaturesCol("pca_features").setLabelCol("label")

import org.apache.spark.ml.Pipeline
val pipeline = new Pipeline(uid = "pipeline").setStages(Array(pca, lr))
val pipelineModel = pipeline.fit(trainingData)


// step 3, Save PipelineModel Transformer
import ml.combust.bundle.BundleFile
import ml.combust.mleap.spark.SparkSupport._
import resource._
for(modelFile <- managed(BundleFile("jar:file:/tmp/pca-lr-pipeline.zip"))) {
  pipelineModel.writeBundle.save(modelFile)
}


// step 4, Load the PipelineModel
import ml.combust.mleap.runtime.MleapSupport._
val mleapPipelineModel = (for(bf <- managed(BundleFile("jar:file:/tmp/pca-lr-pipeline.zip"))) yield {
  bf.loadMleapBundle().get.root
}).tried.get


// step 5, Predict
org.apache.spark.sql.mleap.TensorUDT
val sparkDataframe = mleapPipelineModel.sparkTransform(testData) // An exception occurred
```

And this is my exception:
```
scala> val sparkDataframe = mleapPipelineModel.sparkTransform(testData)
org.apache.spark.sql.AnalysisException: cannot resolve 'UDF(features)' due to data type mismatch: argument 1 requires te
nsor type, however, '`features`' is of vector type.;;
'Project [label#0, features#1, UDF(features#1) AS pca_features#121]
+- Sample 0.8, 0.9, false, -6770897999572677705
   +- Sort [label#0 ASC NULLS FIRST, features#1 ASC NULLS FIRST], false
      +- Relation[label#0,features#1] libsvm

  at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAna
lysis.scala:93)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAna
lysis.scala:85)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:289)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:288)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:306)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:304)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:286)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:268)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:268)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:279)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(Q
ueryPlan.scala:289)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTran
sform$1$1.apply(QueryPlan.scala:293)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(Q
ueryPlan.scala:293)
  at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$6.apply(QueryPlan.scala:298)
  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:298)
  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:268)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:85)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:78)
  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:127)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:78)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:91)
  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:52)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:66)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withPlan(Dataset.scala:2872)
  at org.apache.spark.sql.Dataset.select(Dataset.scala:1153)
  at org.apache.spark.sql.Dataset.withColumn(Dataset.scala:1908)
  at ml.combust.mleap.spark.SparkTransformBuilder$$anonfun$withOutput$1.apply(SparkTransformBuilder.scala:38)
  at ml.combust.mleap.spark.SparkTransformBuilder$$anonfun$withOutput$1.apply(SparkTransformBuilder.scala:35)
  at scala.util.Try$.apply(Try.scala:192)
  at ml.combust.mleap.spark.SparkTransformBuilder.withOutput(SparkTransformBuilder.scala:35)
  at ml.combust.mleap.runtime.transformer.builder.TransformBuilder$class.withOutput(TransformBuilder.scala:17)
  at ml.combust.mleap.spark.SparkTransformBuilder.withOutput(SparkTransformBuilder.scala:16)
  at ml.combust.mleap.runtime.transformer.FeatureTransformer$class.transform(Transformer.scala:45)
  at ml.combust.mleap.runtime.transformer.feature.Pca.transform(Pca.scala:12)
  at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:13)
  at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:13)
  at scala.util.Success.flatMap(Try.scala:231)
  at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:13)
  at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:13)
  at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
  at scala.collection.immutable.List.foldLeft(List.scala:84)
  at ml.combust.mleap.runtime.transformer.Pipeline.transform(Pipeline.scala:13)
  at ml.combust.mleap.spark.SparkSupport$MleapSparkTransformerOps.sparkTransform(SparkSupport.scala:28)
  ... 42 elided

scala>
```

I can run the demo in Mleap, can anyone help me to solve this problem?

**Comment by seme0021** [comment]
@wyFTD -

We need to update our demo, but to get it to work you'll need to load the MLeap model back int the Spark Transformer (MLeap transformers operate on Tensors and Spark TFs opperate on Vectors):

Here is how you would do that:

```scala
val zipBundle = (for(bundle <- managed(BundleFile("jar:file:/tmp/pca-lr-pipeline.zip"))) yield {
  bundle.loadSparkBundle().get
}).opt.get
```

Then
```scala
zipBundle.root.transform(TestData)
```

Docs: http://mleap-docs.combust.ml/spark/

Let us know if you run into other issues!

Best
M

**Comment by wyFTD** [comment]
@seme0021 

Thanks for your replying!

I am sorry the solution you gave does not work. 

I tracked the exception. The type of `trainingData`  in above code is `org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] = [label: double, features: vector]` and the exception is `data type mismatch`. 

Then I converted the data `sample_libsvm_data.txt` into dense format `sample_libsvm_data.csv` as the data `mnist_train.csv` of MLeap demo and the the data type of `trainingData` is `org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] = [label: int, x0: int ... 691 more fields]`. Then I got a similar exception.

Finally I convert the data into `Double` and the data type of `trainingData` is `org.apache.spark.sql.Dataset[org.apache.spark.sql.Row] = [label: double, x0: double ... 691 more fields]`. The above code ran well.

So I think the probable problem is that the data type of `trainingData` should be `Double` other than any other data types such as `Int`, `Vector` and so on. 

Could you help me confirm it?

--------------------------------------------------------------------------

What I want to do is to train the pipeline including feature processing and machine learning model in spark and save the pipeline transformer locally. Then I can load the saved pipeline transformer in single computer and predict mleap dataframe without spark context or predict spark dataframe.

Looking forward your replying! Thank you!

Best, 
Yang

**Comment by hollinwilkins** [comment]
@wyFTD Recently overhauled the Spark transformer integration. This should be fixed with this PR: https://github.com/combust/mleap/pull/260

However, if you are transforming a Spark DataFrame, the recommendation would be to use Spark tranasformers. You can load a Spark ML pipeline from a Bundle.ML file instead of loading an MLeap pipeline and then using it to transform a Spark DataFrame.

**Comment by hollinwilkins** [comment]
Closing this issue. Please reopen if the error persists even with changes in MLeap 0.8.0.
