### ISSUE TITLE
OneHotEncoder issue

### ISSUE THREAD

**Issue by fatihtekin** [combust/mleap#246]
When I am using onehotencoder i am getting below exception after calling fit() on the crossvalidation. Spark version is 2.2.0 scala is 2.11 and mleap is 0.7.0

val encoder = new org.apache.spark.ml.mleap.feature.OneHotEncoder()
        .setInputCol(categoryColumn+"_INDEX")
        .setOutputCol(categoryColumn + "_VEC")
        .setDropLast(false)

2017-08-09 16:18:05,501 [main] WARN  com.github.fommil.netlib.BLAS - Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
2017-08-09 16:18:05,502 [main] WARN  com.github.fommil.netlib.BLAS - Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS
Exception in thread "main" java.lang.NoSuchMethodException: org.apache.spark.ml.mleap.feature.OneHotEncoderModel.<init>(java.lang.String)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.apache.spark.ml.param.Params$class.defaultCopy(params.scala:718)
	at org.apache.spark.ml.PipelineStage.defaultCopy(Pipeline.scala:42)
	at org.apache.spark.ml.mleap.feature.OneHotEncoderModel.copy(OneHotEncoder.scala:49)
	at org.apache.spark.ml.mleap.feature.OneHotEncoderModel.copy(OneHotEncoder.scala:35)
	at org.apache.spark.ml.PipelineModel$$anonfun$copy$1.apply(Pipeline.scala:315)
	at org.apache.spark.ml.PipelineModel$$anonfun$copy$1.apply(Pipeline.scala:315)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.ml.PipelineModel.copy(Pipeline.scala:315)
	at org.apache.spark.ml.PipelineModel.copy(Pipeline.scala:292)
	at org.apache.spark.ml.Pipeline$$anonfun$1.apply(Pipeline.scala:175)
	at org.apache.spark.ml.Pipeline$$anonfun$1.apply(Pipeline.scala:175)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.ml.Pipeline.copy(Pipeline.scala:175)
	at org.apache.spark.ml.Pipeline.copy(Pipeline.scala:96)
	at org.apache.spark.ml.tuning.ValidatorParams$class.transformSchemaImpl(ValidatorParams.scala:77)
	at org.apache.spark.ml.tuning.CrossValidator.transformSchemaImpl(CrossValidator.scala:65)
	at org.apache.spark.ml.tuning.CrossValidator.transformSchema(CrossValidator.scala:140)
	at org.apache.spark.ml.PipelineStage.transformSchema(Pipeline.scala:74)
	at org.apache.spark.ml.tuning.CrossValidator.fit(CrossValidator.scala:97)
	at org.apache.spark.ml.trustedpayments.MleapPipeline$.main(MleapPipeline.scala:136)
	at org.apache.spark.ml.trustedpayments.MleapPipeline.main(MleapPipeline.scala)

**Comment by hgiddens** [comment]
I believe this was fixed by #219. You should be able to test this by building a local snapshot; there is no release incorporating the fix yet.

**Comment by hollinwilkins** [comment]
I'll close this for now. If you are still experiencing the issue, please reopen.
