### ISSUE TITLE
Write bundle with spark-submit fails.

### ISSUE THREAD

**Issue by sethah** [combust/mleap#252]
I'm just trying to serialize a vanilla Spark pipeline to a BundleFile using spark-submit. The main method of the application looks like:

````scala
    val training: DataFrame = ACMEData.readData()
    val pipeline: PipelineModel = ACMEModel.buildModel() // train a spark pipeline
    val sbc = SparkBundleContext().withDataset(pipeline.transform(training))
    for(bf <- managed(BundleFile("jar:file:/tmp/acme-detection.zip"))) {
      pipeline.writeBundle.format(SerializationFormat.Json).save(bf)(sbc).get
    }
````

I get the following error:

````
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'ml.combust.mleap.spark'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
        at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
        at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:258)
        at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:264)
        at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:37)
        at ml.combust.bundle.BundleRegistry$.apply(BundleRegistry.scala:34)
        at ml.combust.bundle.BundleRegistry$.apply(BundleRegistry.scala:27)
        at org.apache.spark.ml.bundle.SparkBundleContext$.apply(SparkBundleContext.scala:17)
        at org.apache.spark.ml.bundle.SparkBundleContext$.defaultContext$lzycompute(SparkBundleContext.scala:11)
        at org.apache.spark.ml.bundle.SparkBundleContext$.defaultContext(SparkBundleContext.scala:11)
````

This happens when it tries to create the `SparkBundleContext()`. Any ideas what I'm doing wrong here?

**Comment by hollinwilkins** [comment]
@sethah Are you making an assembly? Make sure that the reference.conf files are making it into your JAR file. Verify this by looking at your JAR file and see if that key made it in. If the key is in there and you still get this error, it has something to do with the class loader and we can take it from there.

**Comment by sethah** [comment]
Thanks for the quick reply. Here's what I see:

````
$ jar -tf target/acme-serving-1.0.0.jar | grep "\.conf"
reference.conf
````

**Comment by hollinwilkins** [comment]
@sethah If you look inside the reference.conf, can you verify that the expected keys are there? You should have something in there that looks like this: https://github.com/combust/mleap/blob/master/mleap-spark/src/main/resources/reference.conf

**Comment by sethah** [comment]
There's nothing with the `ml.combust.mleap.spark` prefix in there. Only 

````
ml.combust.mleap.registry.builtin = {
  ops = ["ml.combust.mleap.builtin-ops"]
  custom-types = []
}
ml.combust.mleap.registry.default = ${ml.combust.mleap.registry.builtin}

ml.combust.mleap.builtin-ops = [
  ...
]

````

So, yes this seems to be the problem. Seems `mleap-spark-extension` and `mleap-spark` reference.conf files are missing?

**Comment by hollinwilkins** [comment]
@sethah Make sure your assembly is including the mleap-spark jars and that you are merging, not overwriting the reference.conf file when you build the assembly jar.

**Comment by sethah** [comment]
Thanks for your help, @hollinwilkins. Adding the following to the maven shade plugin fixed it:

````
<transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
    <resource>reference.conf</resource>
</transformer>
````

This seems to be the same problem discussed here: https://stackoverflow.com/questions/28555174/running-akka-with-runnable-jar

**Comment by hollinwilkins** [comment]
Perfect! Glad that this helped you. If you feel like it, make a pull request to add this to our documentation somewhere:

https://github.com/combust/mleap-docs

**Comment by PowerToThePeople111** [comment]
For Scala with the assembly plugin 0.8, you can now also use MergeStrategy.concat:

assemblyMergeStrategy in assembly := {
    case n if n.startsWith("reference.conf") => MergeStrategy.concat
//rest
  }

taken from http://letitcrash.com/post/21025950392/howto-sbt-assembly-vs-referenceconf

**Comment by yairdata** [comment]
i am getting the below error:
> java.lang.NoClassDefFoundError: resource/package$
i wonder why the shading is not part of the release, for companies that from security policies have access only pypi , it will be great that all dependencies will be fetched from there and maven , and won't involve changes in maven/sbt files and building fat jars.
alternatives can also be be building a spark+mleap docker for the train & export part , and not just the mleap-serving part.
