### ISSUE TITLE
Spark shell with packages is not working

### ISSUE THREAD

**Issue by eduarger** [combust/mleap#295]
when I tried to use the package on spark-shell (Spark 2.1), using `spark-shell --packages ml.combust.mleap:mleap-spark_2.11:0.8.1` the following error occurs :

`Exception in thread "main" java.lang.RuntimeException: problem during retrieve of org.apache.spark#spark-submit-parent: java.lang.RuntimeException: Multiple artifacts of the module net.sourceforge.f2j#arpack_combined_all;0.1 are retrieved to the same file! Update the retrieve pattern  to fix this error.
	at org.apache.ivy.core.retrieve.RetrieveEngine.retrieve(RetrieveEngine.java:249)
	at org.apache.ivy.core.retrieve.RetrieveEngine.retrieve(RetrieveEngine.java:83)
	at org.apache.ivy.Ivy.retrieve(Ivy.java:551)
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1081)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:296)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:160)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.RuntimeException: Multiple artifacts of the module net.sourceforge.f2j#arpack_combined_all;0.1 are retrieved to the same file! Update the retrieve pattern  to fix this error.
	at org.apache.ivy.core.retrieve.RetrieveEngine.determineArtifactsToCopy(RetrieveEngine.java:417)
	at org.apache.ivy.core.retrieve.RetrieveEngine.retrieve(RetrieveEngine.java:118)
	... 7 more`

**Comment by hollinwilkins** [comment]
@eduarger This is usually a problem with your local maven/ivy repository. Try clearing them and then try again.

**Comment by eduarger** [comment]
@hollinwilkins thanks very much for the answer. For future reference, in the logs of the `spark-shell` command,  I could check where the `spark-shell` storages the cache of the repositories, the default  path is: `$HOME/.ivy2`, then I removed all their contents: `rm -rf  $HOME/.ivy2`. After the packages were loaded properly.
