### ISSUE TITLE
MLeap server barfs with airbnb example

### ISSUE THREAD

**Issue by colingoldberg** [combust/mleap#296]
Hi,

I have followed the instructions on http://mleap-docs.combust.ml/mleap-serving/, at this point only trying to test the airbnb random forest example - nothing else.

This is on an aws t2.small ec2 instance.

My steps were:
`
- mkdir /tmp/models
- cd /tmp/models
- https://github.com/combust/mleap/blob/master/mleap-benchmark/src/main/resources/models/airbnb.model.rf.zip
- service docker start
- docker pull combustml/mleap-serving:0.8.0
- docker run -p 65327:65327 -v /tmp/models:/models combustml/mleap-serving:0.8.0 &
- // I opened up port 65327 for the ec2 instance
- curl -v -XPUT -H "content-type: application/json" -d '{"path":"/models/airbnb.model.rf.zip"}' http://localhost:65327/model
`
The error output was:
`
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 65327 (#0)
> PUT /model HTTP/1.1
> Host: localhost:65327
> User-Agent: curl/7.53.1
> Accept: */*
> content-type: application/json
> Content-Length: 38
> 
* upload completely sent off: 38 out of 38 bytes
[ERROR] [SECURITY][11/01/2017 20:25:52.110] [MleapServing-akka.actor.default-dispatcher-7] [akka.actor.ActorSystemImpl(MleapServing)] Uncaught error from thread [MleapServing-akka.actor.default-dispatcher-7] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabledUncaught error from thread [MleapServing-akka.actor.default-dispatcher-7] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[MleapServing]
java.util.zip.ZipError: zip END header not found

	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1605)
	at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1021)
	at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1030)
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at ml.combust.bundle.BundleFile$.apply(BundleFile.scala:43)
	at ml.combust.bundle.BundleFile$.apply(BundleFile.scala:33)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$1.apply(MleapService.scala:28)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$1.apply(MleapService.scala:28)
	at resource.DefaultManagedResource.open(AbstractManagedResource.scala:110)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:87)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:30)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:30)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
`

I hope this is an easy one for you. Is there perhaps a version issue with the airbnb model and the server?

Also, your documentation does not show the -p 65327:65327 docker option, which made a difference between getting a response and no response.

Regards

Colin Goldberg

**Comment by ancasarb** [comment]
@colingoldberg 

I've just tried with a 0.8.0 docker container and the model you linked and was able to get a 200 OK response when uploading a model

```
curl -v -XPUT -H "content-type: application/json" -d '{"path":"/models/airbnb.model.rf.zip"}' http://localhost:65327/model
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 65327 (#0)
> PUT /model HTTP/1.1
> Host: localhost:65327
> User-Agent: curl/7.52.1
> Accept: */*
> content-type: application/json
> Content-Length: 38
> 
* upload completely sent off: 38 out of 38 bytes
< HTTP/1.1 200 OK
< Server: akka-http/10.0.3
< Date: Wed, 01 Nov 2017 22:34:07 GMT
< Content-Type: application/json
< Content-Length: 2
< 
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```
so I am inclined to think that it's not a versioning issue between the model serving and the model itself.

Do you get the same issue with another model, "airbnb.model.lr.zip" model for example?

I'll raise a PR shortly to add the docker option in our documentation, thanks for the suggestion!

**Comment by ancasarb** [comment]
Can you check the model zip looks fine inside your container?

docker exec -it <your_container> bash
cd /models

**Comment by colingoldberg** [comment]
I found the reason.

My wget of the model:
`
wget https://github.com/combust/mleap/blob/master/mleap-benchmark/src/main/resources/models/airbnb.model.rf.zip
`
should have been
`
wget https://github.com/combust/mleap/raw/master/mleap-benchmark/src/main/resources/models/airbnb.model.rf.zip
`

It now works as expected! Thank you!

Colin Goldberg
