### ISSUE TITLE
How to specify mandatory MLEAP model input columns?

### ISSUE THREAD

**Issue by janisit** [combust/mleap#336]
Hi,

I was very happy to find the mleap library, however I have a small problem that I hope you will be able to help me with :)

I've trained an Apache spark model based on a dataset with structure [text, type]. The objective of the model is to predict the type based on the text.

After training I've exported it, imported into MLEAP program and it seems like the "type" column is a mandatory one, although it was only needed for the training phase in Spark. If I specify any random label that my model has previously seen it works fine and I get the prediction. If I omit the label column, I get an error:

```
Exception in thread "main" java.lang.IllegalArgumentException: invalid field: type
	at ml.combust.mleap.core.types.StructType.indexOf(StructType.scala:194)
	at ml.combust.mleap.core.types.StructType.indexedField(StructType.scala:204)
	at ml.combust.mleap.runtime.frame.RowUtil$.createRowSelector(RowUtil.scala:43)
	at ml.combust.mleap.runtime.frame.RowUtil$$anonfun$createRowSelectors$2.apply(RowUtil.scala:25)
	at ml.combust.mleap.runtime.frame.RowUtil$$anonfun$createRowSelectors$2.apply(RowUtil.scala:23)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35)
	at ml.combust.mleap.runtime.frame.RowUtil$.createRowSelectors(RowUtil.scala:23)
	at ml.combust.mleap.runtime.frame.DefaultLeapFrame.withColumn(DefaultLeapFrame.scala:48)
	at ml.combust.mleap.runtime.transformer.feature.StringIndexer.transform(StringIndexer.scala:27)
	at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:28)
	at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2$$anonfun$apply$1.apply(Pipeline.scala:28)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:28)
	at ml.combust.mleap.runtime.transformer.Pipeline$$anonfun$transform$2.apply(Pipeline.scala:28)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at ml.combust.mleap.runtime.transformer.Pipeline.transform(Pipeline.scala:28)
	at lv.vitk.receipts.Test$.main(Test.scala:40)
	at lv.vitk.receipts.Test.main(Test.scala)
```

And here is how my program looks like

```
package lv.vitk


import ml.combust.bundle.BundleFile
import ml.combust.mleap.runtime.MleapSupport._
import resource._

// create a simple LeapFrame to transform
import ml.combust.mleap.runtime.frame.{DefaultLeapFrame, Row}
import ml.combust.mleap.core.types._

object Test {

  def main(args: Array[String]) = {

    // load the Spark pipeline we saved in the previous section
    val bundle = (for (bundleFile <- managed(BundleFile("jar:file:/tmp/simple-spark-pipeline.zip"))) yield {
      bundleFile.loadMleapBundle().get
    }).opt.get


    // MLeap makes extensive use of monadic types like Try
    val schema = StructType(
      StructField("text", ScalarType.String)
      //,StructField("type", ScalarType.String)
    ).get
    val data = Seq(
      Row(
        "let's have a breakfast"
        //,"Other"
      )
    )
    val frame = DefaultLeapFrame(schema, data)

    // transform the dataframe using our pipeline
    val mleapPipeline = bundle.root

    val frame2 = mleapPipeline.transform(frame).get
    val data2 = frame2.dataset

    System.out.print(data2)

  }
}
```

**Comment by hollinwilkins** [comment]
@janisit The accepted solution to this problem is to remove the StringIndexer acting on your prediction column from the pipeline. I usually add in the ReverseStringIndexer (created with the labels from the StringIndexer) back at the end of the pipeline for categorical string data.
