### ISSUE TITLE
`NoSuchElementException: key not found: intercept` when deserialising multinomial LogisticRegression model

### ISSUE THREAD

**Issue by bwieliczko** [combust/mleap#346]
I'm trying to deserialize an mleap model created with the below code and I'm getting the above exception. Could you please suggest a solution? This is run from Java, with spark 2.2 and mleap 0.9.3. 

The model is serialized like this:
```
PipelineModel model = new Pipeline().setStages(new PipelineStage[]{
new StandardScaler().setInputCol("features")
                                    .setOutputCol("scaled"),
 
new LogisticRegression()
        .setFamily("multinomial")
        .setFeaturesCol("scaled")
}).fit(training);

new SimpleSparkSerializer().serializeToBundle(model, model.transform(training).limit(1));
```

I then use the same `SimpleSparkSerializer.deserializeFromBundle`

Full exception: 
```
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at ml.combust.bundle.dsl.Attributes.value(Attributes.scala:130)
	at ml.combust.bundle.dsl.Attributes.apply(Attributes.scala:121)
	at ml.combust.bundle.dsl.HasAttributes$class.value(Attributes.scala:19)
	at ml.combust.bundle.dsl.Model.value(Model.scala:28)
	at org.apache.spark.ml.bundle.ops.classification.LogisticRegressionOpV21$$anon$1.load(LogisticRegressionOpV21.scala:46)
	at org.apache.spark.ml.bundle.ops.classification.LogisticRegressionOpV21$$anon$1.load(LogisticRegressionOpV21.scala:15)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:106)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:104)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at ml.combust.bundle.serializer.ModelSerializer.readWithModel(ModelSerializer.scala:103)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$2.apply(NodeSerializer.scala:102)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$2.apply(NodeSerializer.scala:101)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.NodeSerializer.read(NodeSerializer.scala:100)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$readNode$2.apply(GraphSerializer.scala:57)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$readNode$2.apply(GraphSerializer.scala:57)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.GraphSerializer.readNode(GraphSerializer.scala:56)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$read$1.apply(GraphSerializer.scala:44)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$read$1.apply(GraphSerializer.scala:44)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.combust.bundle.serializer.GraphSerializer.read(GraphSerializer.scala:44)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.load(PipelineOp.scala:27)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.load(PipelineOp.scala:14)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:106)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:104)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at ml.combust.bundle.serializer.ModelSerializer.readWithModel(ModelSerializer.scala:103)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$2.apply(NodeSerializer.scala:102)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$2.apply(NodeSerializer.scala:101)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.NodeSerializer.read(NodeSerializer.scala:100)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$readNode$2.apply(GraphSerializer.scala:57)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$readNode$2.apply(GraphSerializer.scala:57)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.GraphSerializer.readNode(GraphSerializer.scala:56)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$read$1.apply(GraphSerializer.scala:44)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$read$1.apply(GraphSerializer.scala:44)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.combust.bundle.serializer.GraphSerializer.read(GraphSerializer.scala:44)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.load(PipelineOp.scala:27)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.load(PipelineOp.scala:14)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:106)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:104)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at ml.combust.bundle.serializer.ModelSerializer.readWithModel(ModelSerializer.scala:103)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$2.apply(NodeSerializer.scala:102)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$2.apply(NodeSerializer.scala:101)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.NodeSerializer.read(NodeSerializer.scala:100)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$read$2.apply(BundleSerializer.scala:55)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$read$2.apply(BundleSerializer.scala:49)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.BundleSerializer.read(BundleSerializer.scala:49)
	at ml.combust.bundle.BundleFile.load(BundleFile.scala:95)
	at ml.combust.mleap.spark.SparkSupport$SparkBundleFileOps.loadSparkBundle(SparkSupport.scala:26)
	at ml.combust.mleap.spark.SimpleSparkSerializer$$anonfun$deserializeFromBundle$2.apply(SimpleSparkSerializer.scala:34)
	at ml.combust.mleap.spark.SimpleSparkSerializer$$anonfun$deserializeFromBundle$2.apply(SimpleSparkSerializer.scala:33)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at scala.util.control.Exception$Catch.either(Exception.scala:125)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.mleap.spark.SimpleSparkSerializer.deserializeFromBundle(SimpleSparkSerializer.scala:35)
```

**Comment by ancasarb** [comment]
@bwieliczko this PR will have fixed this issue https://github.com/combust/mleap/pull/342.

@hollinwilkins I was thinking that there would be a 0.9.4 version available, after the merge of that PR, but that doesn't seem to have been uploaded to maven?

**Comment by ancasarb** [comment]
@bwieliczko @hollinwilkins closing this issue as 0.9.5 version available on maven contains fix for it.

**Comment by bwieliczko** [comment]
Thank you! It does indeed solve the problem.
