### ISSUE TITLE
when I custom transformers，should spark or mleap opclass be packaged into mleap serving deamon？ should i rebuild mleap whole project

### ISSUE THREAD

**Issue by WusamX** [combust/mleap#361]
[ERROR] [05/07/2018 12:50:18.123] [MleapServing-akka.actor.default-dispatcher-51] [akka.actor.ActorSystemImpl(MleapServing)] Error during
[ERROR] [05/07/2018 12:50:21.275] [MleapServing-akka.actor.default-dispatcher-51] [MleapResource] error with request
java.util.NoSuchElementException: key not found: my_string_map
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at ml.combust.bundle.BundleRegistry.model(BundleRegistry.scala:93)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:105)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:104)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at ml.combust.bundle.serializer.ModelSerializer.readWithModel(ModelSerializer.scala:103)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$2.apply(NodeSerializer.scala:102)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$2.apply(NodeSerializer.scala:101)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.NodeSerializer.read(NodeSerializer.scala:100)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$readNode$2.apply(GraphSerializer.scala:57)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$readNode$2.apply(GraphSerializer.scala:57)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.GraphSerializer.readNode(GraphSerializer.scala:56)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$read$1.apply(GraphSerializer.scala:44)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$read$1.apply(GraphSerializer.scala:44)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at ml.combust.bundle.serializer.GraphSerializer.read(GraphSerializer.scala:44)
	at ml.combust.mleap.bundle.ops.PipelineOp$$anon$1.load(PipelineOp.scala:28)
	at ml.combust.mleap.bundle.ops.PipelineOp$$anon$1.load(PipelineOp.scala:15)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:106)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:104)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)

**Comment by koldkoder** [comment]
@WusamX did you find answer to your question? I am struggling to serialized my custom transfomer in mleap using python. it is serializing fine using scala.
