### ISSUE TITLE
MLEAP custom spark transformers in pyspark

### ISSUE THREAD

**Issue by pratyushsharma** [combust/mleap#369]
Using mleap binary transformers in pyspark for serializing bundles. Couldn't figure out a way to expose mleap transformers to spark.

```
  File "/tmp/zeppelin_pyspark-4137066935698165824.py", line 297, in <module>
    exec(code)
  File "<stdin>", line 2, in <module>
  File "/usr/lib/envs/env-58-ver-196-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/mleap/pyspark/spark_support.py", line 25, in serializeToBundle
    serializer.serializeToBundle(self, path, dataset=dataset)
  File "/usr/lib/envs/env-58-ver-196-a-4.2.9-py-3.5.3/lib/python3.5/site-packages/mleap/pyspark/spark_support.py", line 42, in serializeToBundle
    self._java_obj.serializeToBundle(transformer._to_java(), path, dataset._jdf)
  File "/usr/lib/spark/python/pyspark/ml/pipeline.py", line 249, in _to_java
    java_stages[idx] = stage._to_java()
AttributeError: 'VariablesTransfomer' object has no attribute '_to_java'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-4137066935698165824.py", line 299, in <module>
    raise Exception(traceback.format_exc())
Exception: Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-4137066935698165824.py", line 297, in <module>
```

**Comment by cfespinoza** [comment]
I think it is not possible by the moment, I have faced the same issue and reading the documentation, it is necessary to define your transformer with its backend in Scala. Take a look to the doc:
http://mleap-docs.combust.ml/mleap-runtime/custom-transformer.html

hope that helps!

**Comment by ancasarb** [comment]
There are quite a few duplicates on this question, I am going to close this issue and keep #495 open as a reference ticket for this enhancement.
