### ISSUE TITLE
Mleap 0.10.1 exception with Spark 2.2.1

### ISSUE THREAD

**Issue by stefanm7** [combust/mleap#374]
Due to adaption of Mleap to Spark 2.3.0 in pull request #364  this error occurs when executing the with Spark 2.2.1 Spark-Example shown in the readme.md of this repository.

`Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.ml.feature.StringIndexerModel.getStringOrderType()Ljava/lang/String;
	at org.apache.spark.ml.bundle.ops.feature.StringIndexerOp$$anon$1.store(StringIndexerOp.scala:23)
	at org.apache.spark.ml.bundle.ops.feature.StringIndexerOp$$anon$1.store(StringIndexerOp.scala:14)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:87)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:83)`

**Comment by Khiem-Tran** [comment]
I am also facing with this error recently when trying to dump a pipeline that contains StringIndexer.

**Comment by ancasarb** [comment]
@stefanm7 @Khiem-Tran I've picked up this issue, will keep you posted. Thanks for the issue report.

**Comment by ancasarb** [comment]
Once merged, https://github.com/combust/mleap/pull/383 should fix this issue, thank you!

**Comment by ancasarb** [comment]
Closing, as PRs has been merged to master.

**Comment by liaosimin** [comment]
how could I solved this problem?
