### ISSUE TITLE
Docker examples 

### ISSUE THREAD

**Issue by mengxr** [combust/mleap#375]
I followed the serving example at http://mleap-docs.combust.ml/mleap-serving/ but hit the following error when I tried to upload the model. I tried the latest (0.10.0, 0.11.0) docker images at https://hub.docker.com/r/combustml/mleap-serving/tags/ but neither worked. Verified that the model files were mounted inside the docker container.

~~~
[ERROR] [06/19/2018 19:23:04.983] [MleapServing-akka.actor.default-dispatcher-12] [MleapResource] error with request
java.nio.file.NoSuchFileException: bundle.json
	at com.sun.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:636)
	at com.sun.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:739)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:255)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at ml.combust.bundle.BundleFile$$anonfun$readInfo$1.apply(BundleFile.scala:79)
	at ml.combust.bundle.BundleFile$$anonfun$readInfo$1.apply(BundleFile.scala:79)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.BundleFile.readInfo(BundleFile.scala:79)
	at ml.combust.bundle.serializer.BundleSerializer.read(BundleSerializer.scala:49)
	at ml.combust.bundle.BundleFile.load(BundleFile.scala:104)
	at ml.combust.mleap.runtime.MleapSupport$MleapBundleFileOps.loadMleapBundle(MleapSupport.scala:22)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$2.apply(MleapService.scala:28)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$2.apply(MleapService.scala:27)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at scala.util.control.Exception$Catch.either(Exception.scala:125)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:29)
	at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:29)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
~~~

**Comment by akarsh3007** [comment]
I came across the same issue, Could you please check when you serialize your Model, it was successfully serialized (it is wrapped by a Try method and returns success and failure.) After success, it returns a Bundle object which is Mleap Bundle. If there is an error in this step,  you will see the above error. Also, can you export the zip file of your model and see if it has bundle.json at root level or not?

**Comment by mengxr** [comment]
It is the Airbnb model provided in that MLeap example. And I can load it using MLeap API directly. Just the serving layer doesn't work.

**Comment by akarsh3007** [comment]
Can you try it with mleap-serving:0.7 version, there was apparently some changes, I also tried to use the Airbnb model provided in the documentation, it worked with 0.7 version but was not working in the later versions.

**Comment by mengxr** [comment]
I didn't try. Even it works with 0.7, we should still fix master or user guide.

**Comment by akarsh3007** [comment]
Yes, I agree on that point.

**Comment by ancasarb** [comment]
@mengxr @akarsh3007 Could I please ask how you've downloaded the airbnb zip file? I just want to make sure you're not seeing the same issue as here (https://github.com/combust/mleap/issues/296), which can be resolved by just correcting the download url, because I've just issued load & transform requests using the docker images 0.8.1-SNAPSHOT, 0.9.0-SNAPSHOT, 0.10.0-SNAPSHOT, 0.11.0-SNAPSHOT without any issues.

**Comment by akarsh3007** [comment]
@ancasarb We followed the steps from the [documentation](http://mleap-docs.combust.ml/mleap-serving/ ). We downloaded this [model]( https://github.com/combust/mleap/raw/master/mleap-benchmark/src/main/resources/models/airbnb.model.rf.zip) and followed the steps. This model seems to have the correct url which was resolved in issue (#296). But i have worked with my models and serialzed and loaded my models which works fine on  0.10.0-SNAPSHOT, 0.11.0-SNAPSHOT. I have not tested on lower versions.

**Comment by ancasarb** [comment]
Okay, I followed the same steps. It looks like it may not be an issue any longer then, I'll wait for @mengxr to confirm as well.

**Comment by Neiraj** [comment]
1) Make sure your Volume is mounted correctly 
2) Make sure to call the API to Load the Model before running Transform

I tried with Snapshot 0.9.0-snapshot, and it works fine. 
as a note i did host the Docker Image on Kubernetes!

**Comment by ancasarb** [comment]
We've re-implemented the serving layer, using either grpc or http (spring boot).

Could you please take a look at 
https://github.com/combust/mleap/tree/master/mleap-serving
https://github.com/combust/mleap/tree/master/mleap-executor
https://github.com/combust/mleap/tree/master/mleap-spring-boot

and let us know if there are any issues? Thanks!

Will close this issue for now, as it's related to the older serving layer, could you please reopen if you still see an issue? Thanks!
