### ISSUE TITLE
Spark ML LinearSVC serialization Error

### ISSUE THREAD

**Issue by mleida-stratio** [combust/mleap#384]
Hi, I am migrating from version 0.7.0 to Version 0.10.2
I am using Spark 2.2.0 and a Python 3.5 kernel with Py4J 0.10.4 
MLeap python package is 0.9.4

I have a set of python and scala notebooks that I use to test MLeap serialization and deserialization.
With the new version, the serialization of the Linear Support Vector Machine classifier is returning the following exception, while with the version 0.7.0 this is working fine.

The pipeline is defined as follows (it is merely for testing the library):

```
import org.apache.spark.ml.classification.LinearSVC
import org.apache.spark.ml.Pipeline 
import org.apache.spark.ml.feature.{Binarizer, HashingTF, NGram, IDF, Tokenizer, Word2Vec, 
VectorAssembler, StringIndexer, StopWordsRemover, MinMaxScaler, IndexToString}
import org.apache.spark.ml.evaluation.{MulticlassClassificationEvaluator, BinaryClassificationEvaluator, RegressionEvaluator}
import org.apache.spark.ml.tuning.{CrossValidator, ParamGridBuilder}

val tk = new Tokenizer().setInputCol("text").setOutputCol("words")
val rm = new StopWordsRemover().setInputCol(tk.getOutputCol).setOutputCol("filtered")
val ngram = new NGram().setN(2).setInputCol("words")setOutputCol("ngrams")
val wv = new Word2Vec().setInputCol(ngram.getOutputCol).setOutputCol("wordVec").setVectorSize(5)
val scaler_wv = new MinMaxScaler().setInputCol(wv.getOutputCol).setOutputCol("scaledFeaturesvt")
val ht = new HashingTF().setInputCol(rm.getOutputCol).setOutputCol("hashingTF").setNumFeatures(20)
val idf = new IDF().setInputCol(ht.getOutputCol).setOutputCol("TF-IDF").setMinDocFreq(1)
val va = new VectorAssembler().setInputCols(Array(scaler_wv.getOutputCol, idf.getOutputCol)).setOutputCol("features") 
val si = new StringIndexer().setInputCol("original_category").setOutputCol("label").setHandleInvalid("skip").fit(training)
val cc = new IndexToString().setInputCol("prediction").setOutputCol("predicted_category").setLabels(si.labels)
val stages_fe = Array(tk, rm, ngram, ht, idf, wv, scaler_wv, va)
val svm = new LinearSVC().setMaxIter(10).setRegParam(0.01)
val nsi = new StringIndexer().setInputCol("original_category").setOutputCol("label_multi")
nsi.fit(training)
val binlab = new Binarizer().setThreshold(7).setInputCol(nsi.getOutputCol).setOutputCol("label")
val pipeline_svm = new Pipeline().setStages(stages_fe ++ Array(nsi, binlab, svm))
val paramGrid = new ParamGridBuilder().addGrid(svm.regParam, Array(0.1, 1.00)).build()
val binary_eval = new RegressionEvaluator().setLabelCol("label").setPredictionCol("prediction").setMetricName("rmse")
val crossval_svm = new CrossValidator().setEstimator(pipeline_svm).setEvaluator(binary_eval).setEstimatorParamMaps(paramGrid).setNumFolds(3)  // Use 3+ in practice
val cvModel_lvm = crossval_svm.fit(training)
val bestModel_svm = cvModel_lvm.bestModel
```
And i get the following error:
```
/opt/conda/lib/python3.5/site-packages/mleap/pyspark/spark_support.py in serializeToBundle(self, path, dataset)
     23 def serializeToBundle(self, path, dataset=None):
     24     serializer = SimpleSparkSerializer()
---> 25     serializer.serializeToBundle(self, path, dataset=dataset)
     26 
     27 

/opt/conda/lib/python3.5/site-packages/mleap/pyspark/spark_support.py in serializeToBundle(self, transformer, path, dataset)
     40 
     41     def serializeToBundle(self, transformer, path, dataset):
---> 42         self._java_obj.serializeToBundle(transformer._to_java(), path, dataset._jdf)
     43 
     44     def deserializeFromBundle(self, path):

/opt/spark/dist/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/opt/spark/dist/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/opt/spark/dist/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    317                 raise Py4JJavaError(
    318                     "An error occurred while calling {0}{1}{2}.\n".
--> 319                     format(target_id, ".", name), value)
    320             else:
    321                 raise Py4JError(

Py4JJavaError: An error occurred while calling o35278.serializeToBundle.
: java.util.NoSuchElementException: key not found: org.apache.spark.ml.classification.LinearSVCModel
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at ml.combust.bundle.BundleRegistry.opForObj(BundleRegistry.scala:84)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:31)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:30)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.GraphSerializer.writeNode(GraphSerializer.scala:30)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35)
	at ml.combust.bundle.serializer.GraphSerializer.write(GraphSerializer.scala:20)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:21)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:14)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:87)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:83)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:83)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:85)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:81)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:81)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:34)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:29)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.BundleSerializer.write(BundleSerializer.scala:29)
	at ml.combust.bundle.BundleWriter.save(BundleWriter.scala:26)
	at ml.combust.mleap.spark.SimpleSparkSerializer$$anonfun$serializeToBundleWithFormat$2.apply(SimpleSparkSerializer.scala:26)
	at ml.combust.mleap.spark.SimpleSparkSerializer$$anonfun$serializeToBundleWithFormat$2.apply(SimpleSparkSerializer.scala:25)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at scala.util.control.Exception$Catch.either(Exception.scala:125)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.mleap.spark.SimpleSparkSerializer.serializeToBundleWithFormat(SimpleSparkSerializer.scala:27)
	at ml.combust.mleap.spark.SimpleSparkSerializer.serializeToBundle(SimpleSparkSerializer.scala:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```
Did something change in the way you serialize Spark objects?

**Comment by ancasarb** [comment]
support for LinearSVC model has been added, closing issue.
