### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by SrikantChari** [combust/mleap#390]
I am installing mleap from source. I have installed sbt version 0.13.9 with scala 2.10.5

Per instructions I cd in to mleap-master and the do an sbt compile. I get the following error

```
[warn] /var/YYY/ZZZ/ddd/002/bbb/XXX/mleap-master/project/Dependencies.scala:103: `<++=` operator is deprecated. Try `lhs ++= { x.value }`
[warn]   or see http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html.
[warn]       libraryDependencies <++= scalaVersion(version => modules.flatMap(m => m.modules(version)))
[warn]                           ^
[warn] there were 1 feature warning(s); re-run with -feature for details
[warn] two warnings found
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
usage: git ls-remote [--heads] [--tags]  [-u <exec> | --upload-pack <exec>] <repository> <refs>...
java.util.NoSuchElementException: head of empty stream
        at scala.collection.immutable.Stream$Empty$.head(Stream.scala:1028)
        at scala.collection.immutable.Stream$Empty$.head(Stream.scala:1026)
        at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$11.apply(SbtGit.scala:138)
        at com.typesafe.sbt.SbtGit$$anonfun$buildSettings$11.apply(SbtGit.scala:122)
        at sbt.Init$Value$$anonfun$apply$13.apply(Settings.scala:609)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$constant$1.apply(INode.scala:163)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
       at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
[error] java.util.NoSuchElementException: head of empty stream
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?```

Please advise how to address the above

**Comment by ancasarb** [comment]
Could you please try with sbt version 0.13.16 and scala version 2.11.8? We're in the process of adding support for scala 2.12.8 as well, please see https://github.com/combust/mleap/pull/496. Thank you!

**Comment by ancasarb** [comment]
Closing this, as we no longer support scala 2.10, please let me know if you have further questions.
