### ISSUE TITLE
StringIndexer Mleap Serialization Broken with Spark 2.3.x

### ISSUE THREAD

**Issue by tcoatale** [combust/mleap#419]
It is no longer possible to export a string indexer from mleap to spark 2.3.

The following sequence of operations fails
``` scala
 import ml.combust.bundle.BundleFile
    import ml.combust.mleap.spark.SparkSupport._
    import org.apache.spark.ml.Pipeline
    import org.apache.spark.ml.bundle.SparkBundleContext
    import org.apache.spark.ml.feature.StringIndexer
    import org.apache.spark.sql._
    import resource._
    import spark.implicits._

    val dataframe: DataFrame = Seq("a", "b", "c").toDF("test_string")

    // User out-of-the-box Spark transformers like you normally would
    val stringIndexer = new StringIndexer().
      setInputCol("test_string").
      setOutputCol("test_index")

    val pipelineEstimator = new Pipeline()
      .setStages(Array(stringIndexer))

    val pipeline = pipelineEstimator.fit(dataframe)

    // then serialize pipeline
    val sbc = SparkBundleContext().withDataset(pipeline.transform(dataframe))
    for(bf <- managed(BundleFile("jar:file:/tmp/simple-spark-pipeline.zip"))) {
      pipeline.writeBundle.save(bf)(sbc).get
    }

    import ml.combust.bundle.BundleFile
    import ml.combust.mleap.runtime.MleapSupport._
    import resource._

    val bundle = (for(bundleFile <- managed(BundleFile("jar:file:/tmp/simple-spark-pipeline.zip"))) yield {
      bundleFile.loadMleapBundle().get
    }).opt.get
    // transform the dataframe using our pipeline
    val mleapPipeline = bundle.root

    // then serialize pipeline
    for (bundle <- managed(BundleFile("jar:file:/tmp/simple-mleap-pipeline.zip"))) {
      mleapPipeline.writeBundle.format(SerializationFormat.Json).save(bundle)
    }

    val sparkBundle = (for(bf <- managed(BundleFile("jar:file:/tmp/simple-mleap-pipeline.zip"))) yield {
      bf.loadSparkBundle().get
    }).either

    sparkBundle.left.foreach(x => throw x.head)
```
with the following stacktrace:
```
java.util.NoSuchElementException: key not found: string_order_type
    at scala.collection.MapLike$class.default(MapLike.scala:228)
    at scala.collection.AbstractMap.default(Map.scala:59)
    at scala.collection.MapLike$class.apply(MapLike.scala:141)
    at scala.collection.AbstractMap.apply(Map.scala:59)
    at ml.combust.bundle.dsl.Attributes.value(Attributes.scala:130)
    at ml.combust.bundle.dsl.Attributes.apply(Attributes.scala:121)
    at ml.combust.bundle.dsl.HasAttributes$class.value(Attributes.scala:19)
    at ml.combust.bundle.dsl.Model.value(Model.scala:28)
    at org.apache.spark.ml.bundle.ops.feature.StringIndexerOpV23$$anon$1.load(StringIndexerOpV23.scala:29)
    at org.apache.spark.ml.bundle.ops.feature.StringIndexerOpV23$$anon$1.load(StringIndexerOpV23.scala:13)
    at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:106)
    at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:104)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
    at scala.util.Try$.apply(Try.scala:192)
    at scala.util.Success.map(Try.scala:237)
    at ml.combust.bundle.serializer.ModelSerializer.readWithModel(ModelSerializer.scala:103)
    at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$2.apply(NodeSerializer.scala:102)
    at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$2.apply(NodeSerializer.scala:101)
    at scala.util.Success.flatMap(Try.scala:231)
    at ml.combust.bundle.serializer.NodeSerializer.read(NodeSerializer.scala:100)
    at ml.combust.bundle.serializer.GraphSerializer$$anonfun$readNode$2.apply(GraphSerializer.scala:57)
    at ml.combust.bundle.serializer.GraphSerializer$$anonfun$readNode$2.apply(GraphSerializer.scala:57)
    at scala.util.Success.flatMap(Try.scala:231)
    at ml.combust.bundle.serializer.GraphSerializer.readNode(GraphSerializer.scala:56)
    at ml.combust.bundle.serializer.GraphSerializer$$anonfun$read$1.apply(GraphSerializer.scala:44)
    at ml.combust.bundle.serializer.GraphSerializer$$anonfun$read$1.apply(GraphSerializer.scala:44)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.immutable.List.foreach(List.scala:392)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.immutable.List.map(List.scala:296)
    at ml.combust.bundle.serializer.GraphSerializer.read(GraphSerializer.scala:44)
    at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.load(PipelineOp.scala:27)
    at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.load(PipelineOp.scala:14)
    at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:106)
    at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:104)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
    at scala.util.Try$.apply(Try.scala:192)
    at scala.util.Success.map(Try.scala:237)
    at ml.combust.bundle.serializer.ModelSerializer.readWithModel(ModelSerializer.scala:103)
    at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$2.apply(NodeSerializer.scala:102)
    at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$2.apply(NodeSerializer.scala:101)
    at scala.util.Success.flatMap(Try.scala:231)
    at ml.combust.bundle.serializer.NodeSerializer.read(NodeSerializer.scala:100)
    at ml.combust.bundle.serializer.BundleSerializer$$anonfun$read$2.apply(BundleSerializer.scala:55)
    at ml.combust.bundle.serializer.BundleSerializer$$anonfun$read$2.apply(BundleSerializer.scala:49)
    at scala.util.Success.flatMap(Try.scala:231)
    at ml.combust.bundle.serializer.BundleSerializer.read(BundleSerializer.scala:49)
    at ml.combust.bundle.BundleFile.load(BundleFile.scala:123)
    at ml.combust.mleap.spark.SparkSupport$SparkBundleFileOps.loadSparkBundle(SparkSupport.scala:29)
```

The issue likely comes from the discrepancy between the spark and mleap ops for the string indexer.

We can see that the spark op [(StringIndexerOpV23)](https://github.com/combust/mleap/blob/master/mleap-spark/src/main/scala/org/apache/spark/ml/bundle/ops/feature/StringIndexerOpV23.scala#L22) writes the model with a `string_order_type` and expects that value to exist when reading. On the other hand, the mleap operator [(StringIndexerOp)](https://github.com/combust/mleap/blob/master/mleap-runtime/src/main/scala/ml/combust/mleap/bundle/ops/feature/StringIndexerOp.scala#L23) does not store this `string_order_type` information. 

As far as I can see, this is the first time an op adds a parameter when changing spark version. The StringOrderType params of the spark StringIndexer was introduced in Spark 2.3.0.

**Comment by hollinwilkins** [comment]
We need to make string_order_type optional in the mleap-runtime op as it's not always available.

**Comment by ancasarb** [comment]
In the mleap-runtime op, we ignore string_order_type, as it's only used during fitting and has no impact at scoring time.

The stringOrderType should always be serialized by the StringIndexerOpV23 (it has a default value of 'frequencyDesc') but it's not happening, even though we're running it with Spark 2.3.0. It's not serialized even when provided explicitly. 

```
    val stringIndexer = new StringIndexer().
      setInputCol("test_string").
      setOutputCol("test_index")
      .setStringOrderType("frequencyAsc")
```

The odd part is that in our StringIndexerParitySpec, this works as expected. 

I'll keep looking at this.

**Comment by ancasarb** [comment]
Ah, I understand what's going on now. The example serializes the spark bundle, loads the mleap bundle, serialized the mleap bundle and then tries to load the spark bundle, so in the process we've lost the stringOrderType. 

Will be raising a PR shortly.
