### ISSUE TITLE
Unable to save serialized model to HDFS

### ISSUE THREAD

**Issue by AashimaYuthika** [combust/mleap#420]
I have written a basic script with pyspark for writing a serialized model to HDFS. Here's the code:
```import mleap.pyspark
from mleap.pyspark.spark_support import SimpleSparkSerializer
from pyspark import SparkContext
from pyspark.sql import SparkSession
from pyspark.ml.feature import VectorAssembler, StandardScaler, OneHotEncoder, StringIndexer
from pyspark.ml import Pipeline, PipelineModel
from pyspark.sql import Row

sc = SparkContext(appName='CTRPrediction')
spark = SparkSession(sc).builder.getOrCreate()

l = [('Alice', 1), ('Bob', 2)]
rdd = sc.parallelize(l)
Person = Row('name', 'age')
person = rdd.map(lambda r: Person(*r))
df2 = spark.createDataFrame(person)
df2.collect()

string_indexer = StringIndexer(inputCol='name', outputCol='name_string_index')

feature_assembler = VectorAssembler(inputCols=[string_indexer.getOutputCol()], outputCol="features")

feature_pipeline = [string_indexer, feature_assembler]

featurePipeline = Pipeline(stages=feature_pipeline)

fittedPipeline = featurePipeline.fit(df2)

fittedPipeline.serializeToBundle("jar:hdfs:///tmp/pyspark.example.zip", fittedPipeline.transform(df2))
```
Running it on a Yarn Cluster like this
`spark-submit --master yarn --deploy-mode cluster --conf spark.yarn.appMasterEnv.PYTHON_EGG_CACHE="/tmp/.cache/" --py-files mleap-0.11.0.dev0-py2.7.egg --jars mleap-spark-base_2.11-0.11.0.jar,mleap-spark_2.11-0.11.0.jar --packages ml.combust.mleap:mleap-spark_2.11:0.11.0 aashima/mleap_test.py`

This is the error that I am getting.
```Traceback (most recent call last):
  File "mleap_test.py", line 34, in <module>
    fittedPipeline.serializeToBundle("jar:hdfs:///tmp/pyspark.example.zip", fittedPipeline.transform(df2))
  File "/mnt/yarn/usercache/hadoop/appcache/application_1524545386558_0665/container_1524545386558_0665_02_000001/mleap-0.11.0.dev0-py2.7.egg/mleap/pyspark/spark_support.py", line 25, in serializeToBundle
  File "/mnt/yarn/usercache/hadoop/appcache/application_1524545386558_0665/container_1524545386558_0665_02_000001/mleap-0.11.0.dev0-py2.7.egg/mleap/pyspark/spark_support.py", line 42, in serializeToBundle
  File "/mnt/yarn/usercache/hadoop/appcache/application_1524545386558_0665/container_1524545386558_0665_02_000001/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 1160, in __call__
  File "/mnt/yarn/usercache/hadoop/appcache/application_1524545386558_0665/container_1524545386558_0665_02_000001/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/mnt/yarn/usercache/hadoop/appcache/application_1524545386558_0665/container_1524545386558_0665_02_000001/py4j-0.10.6-src.zip/py4j/protocol.py", line 320, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o122.serializeToBundle.
: java.nio.file.FileSystemNotFoundException: Provider "hdfs" not installed
	at java.nio.file.Paths.get(Paths.java:147)
	at com.sun.nio.zipfs.ZipFileSystemProvider.uriToPath(ZipFileSystemProvider.java:85)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:107)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at ml.combust.bundle.BundleFile$.apply(BundleFile.scala:70)
	at ml.combust.bundle.BundleFile$.apply(BundleFile.scala:40)
	at ml.combust.mleap.spark.SimpleSparkSerializer$$anonfun$serializeToBundleWithFormat$1.apply(SimpleSparkSerializer.scala:25)
	at ml.combust.mleap.spark.SimpleSparkSerializer$$anonfun$serializeToBundleWithFormat$1.apply(SimpleSparkSerializer.scala:25)
	at resource.DefaultManagedResource.open(AbstractManagedResource.scala:110)
	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:87)
	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.mleap.spark.SimpleSparkSerializer.serializeToBundleWithFormat(SimpleSparkSerializer.scala:27)
	at ml.combust.mleap.spark.SimpleSparkSerializer.serializeToBundle(SimpleSparkSerializer.scala:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ancasarb** [comment]
Raised a PR to fix this issue happening in pyspark here https://github.com/combust/mleap/pull/681, thank you!

**Comment by ancasarb** [comment]
Merged PR to master, will include in next release. Closing this.
