### ISSUE TITLE
Add serialization of LinearSVC model

### ISSUE THREAD

**Issue by samikrc** [combust/mleap#423]
When trying to save a bundle for a pipeline with quite a few steps, I get the following message: `An exception or error caused a run to abort: key not found: org.apache.spark.ml.classification.LinearSVCModel`
I am using Spark 2.3.1 and mleap 0.10.0 with Scala 2.11.8.

The complete code can be found here: [https://github.com/samikrc/try-mleap/blob/master/src/test/scala/com/tfs/test/MleapPipelineTest.scala](https://github.com/samikrc/try-mleap/blob/master/src/test/scala/com/tfs/test/MleapPipelineTest.scala) - in the code, I am trying to use the SVM model inside an OVR model.

The relevant part of the pipeline looks like this:
`new OneVsRest().setClassifier(new LinearSVC().setMaxIter(10).setRegParam(0.1))`

The exception stacktrace:
```
An exception or error caused a run to abort: key not found: org.apache.spark.ml.classification.LinearSVCModel 
java.util.NoSuchElementException: key not found: org.apache.spark.ml.classification.LinearSVCModel
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at ml.combust.bundle.BundleRegistry.modelForObj(BundleRegistry.scala:102)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:85)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:83)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:83)
	at org.apache.spark.ml.bundle.ops.classification.OneVsRestOp$$anon$1$$anonfun$store$1.apply(OneVsRestOp.scala:25)
	at org.apache.spark.ml.bundle.ops.classification.OneVsRestOp$$anon$1$$anonfun$store$1.apply(OneVsRestOp.scala:23)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.apache.spark.ml.bundle.ops.classification.OneVsRestOp$$anon$1.store(OneVsRestOp.scala:23)
	at org.apache.spark.ml.bundle.ops.classification.OneVsRestOp$$anon$1.store(OneVsRestOp.scala:15)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:87)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:83)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:83)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:85)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:81)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:81)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:34)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:30)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.GraphSerializer.writeNode(GraphSerializer.scala:30)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35)
	at ml.combust.bundle.serializer.GraphSerializer.write(GraphSerializer.scala:20)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:21)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:14)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:87)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:83)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:83)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:85)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:81)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:81)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:34)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:29)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.BundleSerializer.write(BundleSerializer.scala:29)
	at ml.combust.bundle.BundleWriter.save(BundleWriter.scala:26)
	at com.tfs.test.MleapPipelineTest$$anonfun$2.apply(MleapPipelineTest.scala:88)
	at com.tfs.test.MleapPipelineTest$$anonfun$2.apply(MleapPipelineTest.scala:87)
	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
        ...
```

This seems similar to the issue mentioned in (https://github.com/combust/mleap/issues/419), which was recently close. However another ticket (https://github.com/combust/mleap/issues/384) seems to talk about the exact same issue (getting the same error message) and is still open (as of this writing).

**Comment by samikrc** [comment]
Hi: any update on this?

**Comment by samikrc** [comment]
I am getting this error with Spark 2.4.0 as well, and without using OVR. I have now added a test in the repo to demonstrate this. The test is available at: https://github.com/samikrc/try-mleap/blob/master/src/test/scala/com/tfs/test/LinearSVCTest.scala
The failure happens at line 72, when trying to write the pipeline as mleap bundle.

**Comment by samikrc** [comment]
Hi @ancasarb : We have a pull request for this enhancement. Can you or someone in the team take a look? Thanks.

**Comment by ancasarb** [comment]
hey @samikrc will take a look. thank you for submitting the PR!

**Comment by samikrc** [comment]
Hi @ancasarb, the pull request [https://github.com/combust/mleap/pull/536] has been ready for sometime. Can you or someone please take a look and see if things are alright?

**Comment by ancasarb** [comment]
sorry, yes I will take a look over the weekend.

**Comment by ancasarb** [comment]
support for LinearSVC model has been added, closing issue.
