### ISSUE TITLE
Unable to load persisted PipelineModel containing mleap Imputer: Column imputeValue must be old Vector type to be converted to new type but got DoubleType

### ISSUE THREAD

**Issue by bleskowsky** [combust/mleap#441]
We've been experiencing this issue when trying to load a saved PipelineModel that contains the mleap Imputer implementation as one of its stages. I have a simplified program here that replicates the issue on my local environment. This is using **Spark 2.3.0** and **mleap 0.12.0**.

Sample program:
```scala
import org.apache.spark.ml.mleap.feature.Imputer
import org.apache.spark.ml.{Pipeline, PipelineModel}
import org.apache.spark.sql.SparkSession

case class Datapoint(id: Int, score: Option[Double])

object MLeapExample {
  def main(args: Array[String]): Unit = {

    val spark = SparkSession
      .builder()
      .appName("MLeap Export")
      .master("local")
      .getOrCreate()

    import spark.implicits._

    // some sample training data (score is nullable)
    val p1 = Datapoint(1, Some(1.0))
    val p2 = Datapoint(2, null)
    val p3 = Datapoint(3, Some(9.0))

    val training = List(p1, p2, p3).toDF

    training.show()

    val imputer = new Imputer()
      .setInputCol("score")
      .setOutputCol("imputed_score")
      .setStrategy("median")

    val pipeline = new Pipeline()
      .setStages(Array(imputer))

    val model = pipeline.fit(training)

    model.write.overwrite().save("trained_model")

    val loaded_model = PipelineModel.load("trained_model")

  }
}
```
The input training data looks as follows:
```
+---+-----+
| id|score|
+---+-----+
|  1|  1.0|
|  2| null|
|  3|  9.0|
+---+-----+
```
This is a very tiny sample of a column in our data that we would typically attempt to impute a value for (score with strategy median). The type of the column to impute is either a double or null. 

Running this example via IntelliJ and spark-submit i.e.

`spark-submit --class MLeapExample --packages ml.combust.mleap:mleap-spark-base_2.11:0.12.0,ml.combust.mleap:mleap-spark_2.11:0.12.0,ml.combust.mleap:mleap-spark-extension_2.11:0.12.0 mleap-export_2.11-0.1.jar`

leads to the following stacktrace:
```
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Column imputeValue must be old Vector type to be converted to new type but got DoubleType.
        at scala.Predef$.require(Predef.scala:224)
        at org.apache.spark.mllib.util.MLUtils$$anonfun$4.apply(MLUtils.scala:299)
        at org.apache.spark.mllib.util.MLUtils$$anonfun$4.apply(MLUtils.scala:293)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
        at org.apache.spark.mllib.util.MLUtils$.convertVectorColumnsToML(MLUtils.scala:293)
        at org.apache.spark.ml.mleap.feature.ImputerModel$ImputerReader.load(Imputer.scala:222)
        at org.apache.spark.ml.mleap.feature.ImputerModel$ImputerReader.load(Imputer.scala:213)
        at org.apache.spark.ml.util.DefaultParamsReader$.loadParamsInstance(ReadWrite.scala:453)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:274)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$$anonfun$4.apply(Pipeline.scala:272)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
        at org.apache.spark.ml.Pipeline$SharedReadWrite$.load(Pipeline.scala:272)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:348)
        at org.apache.spark.ml.PipelineModel$PipelineModelReader.load(Pipeline.scala:342)
        at org.apache.spark.ml.util.MLReadable$class.load(ReadWrite.scala:223)
        at org.apache.spark.ml.PipelineModel$.load(Pipeline.scala:332)
        at MLeapExample$.main(MLeapExample.scala:41)
        at MLeapExample.main(MLeapExample.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Comment by ancasarb** [comment]
Fixed in https://github.com/combust/mleap/pull/681.
