### ISSUE TITLE
java.lang.NoClassDefFoundError: ml/combust/bundle/HasBundleRegistry

### ISSUE THREAD

**Issue by cchung100m** [combust/mleap#442]
Hi all,

Doing the official tutorial of ["Create and Export a Spark Pipeline"](https://github.com/combust/mleap), I encounter the classNoFound issue **ml/combust/bundle/HasBundleRegistry** when I am trying to transform the pipeline, however I am sure that I download the related packages from maven repo, can you share the experience on solving this kind of problem, thank you.

System infromation:
> OS: CentOS Linux release 7.4.1708
> Spark version: 2.3.0.2.6.5.0-292
> Scala version: 2.11.8
> Java version: 1.8.0_131

```
./spark-shell  --packages ml.combust.mleap:mleap-spark_2.11:0.12.0,ml.combust.bundle:bundle-ml_2.11:0.12.0,com.jsuereth:scala-arm_2.11:2.0

scala> spark.sparkContext.listJars.foreach(println)
spark://localhost:33245/jars/ml.combust.bundle_bundle-ml_2.11-0.12.0.jar
spark://localhost:33245/jars/ml.combust.mleap_mleap-spark_2.11-0.12.0.jar
spark://localhost:33245/jars/com.jsuereth_scala-arm_2.11-2.0.jar

scala> import ml.combust.bundle.BundleFile
import ml.combust.bundle.BundleFile

scala> import ml.combust.mleap.spark.SparkSupport._
import ml.combust.mleap.spark.SparkSupport._

scala> import org.apache.spark.ml.Pipeline
import org.apache.spark.ml.Pipeline

scala> import org.apache.spark.ml.bundle.SparkBundleContext
import org.apache.spark.ml.bundle.SparkBundleContext

scala> import org.apache.spark.ml.feature.{Binarizer, StringIndexer}
import org.apache.spark.ml.feature.{Binarizer, StringIndexer}

scala> import org.apache.spark.sql._
import org.apache.spark.sql._

scala> import org.apache.spark.sql.functions._
import org.apache.spark.sql.functions._

scala> import resource._
import resource._

scala> import ml.combust.bundle.{BundleContext, HasBundleRegistry}
import ml.combust.bundle.{BundleContext, HasBundleRegistry}

scala> val datasetName = "/tmp/spark-demo.csv"
datasetName: String = /tmp/spark-demo.csv

scala> val dataframe: DataFrame = spark.sqlContext.read.format("csv").option("header", true).load(datasetName).withColumn("test_double", col("test_double").cast("double"))
dataframe: org.apache.spark.sql.DataFrame = [test_string: string, test_double: double]

scala> val stringIndexer = new StringIndexer().setInputCol("test_string").setOutputCol("test_index")
stringIndexer: org.apache.spark.ml.feature.StringIndexer = strIdx_cc9febc9b258

scala> val binarizer = new Binarizer().setThreshold(0.5).setInputCol("test_double").setOutputCol("test_bin")
binarizer: org.apache.spark.ml.feature.Binarizer = binarizer_48e3bdfc1375

scala> val pipelineEstimator = new Pipeline().setStages(Array(stringIndexer, binarizer))
pipelineEstimator: org.apache.spark.ml.Pipeline = pipeline_9f2e5ca74c10

scala> val pipeline = pipelineEstimator.fit(dataframe)
pipeline: org.apache.spark.ml.PipelineModel = pipeline_9f2e5ca74c10

scala> val sbc = SparkBundleContext().withDataset(pipeline.transform(dataframe))
java.lang.NoClassDefFoundError: ml/combust/bundle/HasBundleRegistry
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at java.lang.Class.getDeclaredMethods0(Native Method)
  at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
  at java.lang.Class.privateGetPublicMethods(Class.java:2902)
  at java.lang.Class.getMethods(Class.java:1615)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.evalMethod(IMain.scala:848)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:781)
  at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1047)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)
  at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
  at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:637)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:569)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
  at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:807)
  at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:681)
  at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:395)
  at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:415)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:923)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
  at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
  at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
  at org.apache.spark.repl.Main$.doMain(Main.scala:76)
  at org.apache.spark.repl.Main$.main(Main.scala:56)
  at org.apache.spark.repl.Main.main(Main.scala)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
  at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:906)
  at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
  at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
  at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
  at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: ml.combust.bundle.HasBundleRegistry
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 50 more`
```

**Comment by cchung100m** [comment]
Hi all,

I got the same error "java.lang.NoClassDefFoundError: ml/combust/bundle/HasBundleRegistry" even though I changed the version of bundle-ml package, can you help to share some tips for this? thanks.

`./spark-shell --packages ml.combust.mleap:mleap-spark_2.11:0.12.0,ml.combust.mleap:mleap-spark-extension_2.11:0.12.0,ml.combust.mleap:mleap-runtime_2.11:0.12.0,ml.combust.bundle:bundle-ml_2.11:0.11.0,com.jsuereth:scala-arm_2.11:2.0,com.databricks:spark-avro_2.11:3.0.1`

**Comment by adityasinghcdacnoida** [comment]
please help me with this error




scala> val sbc = SparkBundleContext().withDataset(sparkPipelineLr.transform(datasetImputedFiltered))
java.lang.NoClassDefFoundError: ml/combust/bundle/HasBundleRegistry
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at java.lang.Class.getDeclaredMethods0(Native Method)
  at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
  at java.lang.Class.privateGetPublicMethods(Class.java:2902)
  at java.lang.Class.getMethods(Class.java:1615)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.evalMethod(IMain.scala:848)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:781)
  at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1047)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)
  at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
  at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:637)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:569)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
  at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:807)
  at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:681)
  at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:395)
  at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:415)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:923)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
  at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
  at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
  at org.apache.spark.repl.Main$.doMain(Main.scala:76)
  at org.apache.spark.repl.Main$.main(Main.scala:56)
  at org.apache.spark.repl.Main.main(Main.scala)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
  at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
  at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
  at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
  at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
  at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: ml.combust.bundle.HasBundleRegistry
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 50 more

**Comment by therajko** [comment]
@cchung100m Were you able to find the solution?

**Comment by Daniel8hen** [comment]
@cchung100m  did u find a solution?
