### ISSUE TITLE
 Error during processing of request: 'bundle.json'. Completing with 500 Internal Server Error response

### ISSUE THREAD

**Issue by wguo123** [combust/mleap#452]
Hi, can someone let me know how to solve this issue? I do have a bundle.json in my model.zip file.

:~/tmp/models$ curl -XPUT -H "content-type: application/json" -d '{"path":"/models/gbt_v1.zip"}' http://localhost:65327/model
[ERROR] [11/24/2018 23:51:08.467] [MleapServing-akka.actor.default-dispatcher-5] [MleapResource] error with request
java.nio.file.NoSuchFileException: bundle.json
        at com.sun.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:636)
        at com.sun.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:739)
        at com.sun.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:255)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.Files.readAllBytes(Files.java:3152)
        at ml.combust.bundle.BundleFile$$anonfun$readInfo$1.apply(BundleFile.scala:59)
        at ml.combust.bundle.BundleFile$$anonfun$readInfo$1.apply(BundleFile.scala:59)
        at scala.util.Try$.apply(Try.scala:192)
        at ml.combust.bundle.BundleFile.readInfo(BundleFile.scala:59)
        at ml.combust.bundle.serializer.BundleSerializer.read(BundleSerializer.scala:49)
        at ml.combust.bundle.BundleFile.load(BundleFile.scala:84)
        at ml.combust.mleap.runtime.MleapSupport$MleapBundleFileOps.loadMleapBundle(MleapSupport.scala:22)
        at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$2.apply(MleapService.scala:29)
        at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2$$anonfun$apply$2.apply(MleapService.scala:28)
        at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
        at scala.util.control.Exception$Catch.apply(Exception.scala:103)
        at scala.util.control.Exception$Catch.either(Exception.scala:125)
        at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
        at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
        at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
        at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
        at scala.util.Try$.apply(Try.scala:192)
        at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
        at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:30)
        at ml.combust.mleap.serving.MleapService$$anonfun$loadModel$2.apply(MleapService.scala:30)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [11/24/2018 23:51:08.479] [MleapServing-akka.actor.default-dispatcher-5] [akka.actor.ActorSystemImpl(MleapServing)] Error during processing of request: 'bundle.json'. Completing with 500 Internal Server Error response.
There was an internal server error.weig@weigubuntu1123:~/tmp/models$  Error during processing of request: 'bundle.json'. Completing with 500 Internal Server Error response

**Comment by RayTsui** [comment]
Hi, I think when you create bundle.ml, the resulting .zip is missing bundle.json. I suppose you can check your code on final part, or read the reference http://mleap-docs.combust.ml/troubleshooting.html, which can help to create a complete bundle.ml .zip package.

**Comment by ancasarb** [comment]
@wguo123 is this still an issue? 

We've re-implemented the serving layer, using either grpc or http (spring boot). You can take a look at the new serving layer, using the links below. 

https://github.com/combust/mleap/tree/master/mleap-serving
https://github.com/combust/mleap/tree/master/mleap-executor
https://github.com/combust/mleap/tree/master/mleap-spring-boot

Thank you!

**Comment by ancasarb** [comment]
Closing this, please re-open if it's still an issue.
