### ISSUE TITLE
Create DenseTensor in Java

### ISSUE THREAD

**Issue by wzhe06** [combust/mleap#456]
These is one field which type is tensor in LeapFrame schema. So I need to create a DenseTensor in Java(my api server is written in Java) as one field of LeapFrame input for my model.
But I found it's not possible to create a DenseTensor in Java through a convenient way.

After I create a DenseTensor like this
`new DenseTensor(userEmbedding, support.createTensorDimensions(dims).get(), scala.reflect.ClassTag$.MODULE$.apply(DenseTensor.class))`

It throws a ClassCastException in the transform stage.
`Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.Double; cannot be cast to [D
	at ml.combust.mleap.core.feature.VectorAssemblerModel$$anonfun$apply$3.apply(VectorAssemblerModel.scala:46)
	at ml.combust.mleap.core.feature.VectorAssemblerModel$$anonfun$apply$3.apply(VectorAssemblerModel.scala:37)
	at scala.collection.immutable.Stream.foreach(Stream.scala:555)
	at ml.combust.mleap.core.feature.VectorAssemblerModel.apply(VectorAssemblerModel.scala:37)
	at ml.combust.mleap.runtime.transformer.feature.VectorAssembler$$anonfun$1.apply(VectorAssembler.scala:18)
	at ml.combust.mleap.runtime.transformer.feature.VectorAssembler$$anonfun$1.apply(VectorAssembler.scala:18)
	at ml.combust.mleap.runtime.frame.Row$class.udfValue(Row.scala:241)
	at ml.combust.mleap.runtime.frame.ArrayRow.udfValue(ArrayRow.scala:17)` 

I think it's cause by I use java.lang.Double instead of scala.Double in the userEmbedding array. It will cost more redundancy code to solve this problem

So I don't know if there is some convenient way to create a Double DenseTensor in Java?

**Comment by ancasarb** [comment]
@wzhe06 I have raised https://github.com/combust/mleap/pull/459 to make it possible to pass dense/sparse vectors when creating rows in Java, which are then translated to tensors.

**Comment by ancasarb** [comment]
Closing this as PR #459 has been merged, please feel free to reopen if you see any issues, thank you!
