### ISSUE TITLE
java.lang.ClassCastException: java.math.BigDecimal cannot be cast to scala.math.BigDecimal

### ISSUE THREAD

**Issue by marsbible** [combust/mleap#462]
Hi team,
  I tried to run notebook https://github.com/combust/mleap-demo/blob/master/notebooks/airbnb-price-regression.ipynb on the latest mleap version 0.13, it failed when i execute "sparkDataframe.select("bedrooms", "bathrooms", "price", "price_prediction").show(10)", is this a bug?

--------------------------------------log------------------------------------------------------------------------
Name: org.apache.spark.SparkException
Message: Job aborted due to stage failure: Task 0 in stage 59.0 failed 1 times, most recent failure: Lost task 0.0 in stage 59.0 (TID 1366, localhost, executor driver): java.lang.ClassCastException: java.math.BigDecimal cannot be cast to scala.math.BigDecimal
	at org.apache.spark.sql.mleap.TypeConverters$$anonfun$sparkToMleapValue$1.apply(TypeConverters.scala:30)
	at org.apache.spark.sql.mleap.TypeConverters$$anonfun$sparkToMleapValue$1.apply(TypeConverters.scala:30)
	at ml.combust.mleap.spark.SparkSupport$SparkDataFrameOps$$anonfun$4$$anonfun$5.apply(SparkSupport.scala:55)
	at ml.combust.mleap.spark.SparkSupport$SparkDataFrameOps$$anonfun$4$$anonfun$5.apply(SparkSupport.scala:54)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)

**Comment by ancasarb** [comment]
Closing as PR #497 was merged and will be released in the new mleap version.
