### ISSUE TITLE
Migrating Pyspark Pipeline to Scala not Working

### ISSUE THREAD

**Issue by mtsol** [combust/mleap#543]
Hi, my requirement is that I want to save a pyspark pipeline from python, and use it in scala. For this, I adopted Mleap. And now, when I save pipeline in python code, and load it in scala by using mleap library. it gives me transformation error. I'm using LeapFrames in scala and spark dataframe in pyspark (python).  The exception is:
Exception in thread "main" java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at ml.combust.mleap.runtime.frame.Row.udfValue(Row.scala:241)
	at ml.combust.mleap.runtime.frame.Row.udfValue$(Row.scala:236)
	at ml.combust.mleap.runtime.frame.ArrayRow.udfValue(ArrayRow.scala:17)
	at ml.combust.mleap.runtime.frame.Row.withValue(Row.scala:221)
	at ml.combust.mleap.runtime.frame.Row.withValue$(Row.scala:220)
	at ml.combust.mleap.runtime.frame.ArrayRow.withValue(ArrayRow.scala:17)
	at ml.combust.mleap.runtime.frame.DefaultLeapFrame.$anonfun$withColumn$3(DefaultLeapFrame.scala:54)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at ml.combust.mleap.runtime.frame.DefaultLeapFrame.$anonfun$withColumn$2(DefaultLeapFrame.scala:54)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at ml.combust.mleap.runtime.frame.DefaultLeapFrame.$anonfun$withColumn$1(DefaultLeapFrame.scala:53)
	at scala.util.Success.flatMap(Try.scala:247)
	at ml.combust.mleap.runtime.frame.DefaultLeapFrame.withColumn(DefaultLeapFrame.scala:49)
	at ml.combust.mleap.runtime.transformer.feature.StringIndexer.transform(StringIndexer.scala:27)
	at ml.combust.mleap.runtime.transformer.Pipeline.$anonfun$transform$3(Pipeline.scala:28)
	at scala.util.Success.flatMap(Try.scala:247)
	at ml.combust.mleap.runtime.transformer.Pipeline.$anonfun$transform$2(Pipeline.scala:28)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at ml.combust.mleap.runtime.transformer.Pipeline.transform(Pipeline.scala:28)
	at Testing$.main(Testing.scala:117)
	at Testing.main(Testing.scala)
(you can skip the reason of the error)

the issue is, I cannot find any documentation which explains about taking a model from pyspark to scala mleap. Referring to combust-docs http://mleap-docs.combust.ml/py-spark/ this guides about storing and reading pipeline in pyspark(python) and after serialization, I want to deserialize it in scala, use it. Referring to combust-docs, http://mleap-docs.combust.ml/mleap-runtime/transform-leap-frame.html this link guides about creating a pipeline in scala. Tell me what is the use of mleap if I need to re-code pipeline model in scala. Can you tell any suitable way of importing pyspark(python) pipeline to scala using mleap. As it is not well documented.

**Comment by ancasarb** [comment]
What are the transformers involved in your pipeline? Serializing a pipeline in Spark and simply deserializing in Scala is definitely possible. I can help take a look if you have a sample pipeline to reproduce the error.

**Comment by mtsol** [comment]
Thank you very much, I resolved the issue
