### ISSUE TITLE
Mleap model not working with continuous and categorical features

### ISSUE THREAD

**Issue by mtsol** [combust/mleap#547]
I have the following pyspark pipeline that i want to serialize and after that, I want to use this pipeline in scala for prediction:
string_indexer=StringIndexer(inputCol="DayOfWeek",outputCol="DayIndex")
string_indexer=string_indexer.fit(train_df)
string_indexer3=StringIndexer(inputCol="PdDistrict",outputCol="PdIndexed")
string_indexer3=string_indexer3.fit(train_df)
string_indexer2 = StringIndexer(inputCol="Category",outputCol="CategoryIndex")
string_indexer2 = string_indexer2.fit(train_df)
train_df = string_indexer2.transform(train_df)
assembler=VectorAssembler(inputCols=["DayIndex", "X", "Y", "PdIndexed"],outputCol="features")
rf = RandomForestClassifier(labelCol="CategoryIndex",featuresCol="features",numTrees=20)
feature_modle_pipeline=Pipeline(stages=[string_indexer, string_indexer3, assembler, rf])
feature_modle_pipeline.serializeToBundle("file:/tmp/4_string_indexers_pyspark.example.zip", model.transform(train_df))
The model gets exported, but when I import this model in scala using the following code, it gives an exception:
import ml.combust.bundle.BundleFile	
import ml.combust.mleap.runtime.MleapContext.defaultContext	
import ml.combust.mleap.runtime.MleapSupport._	
import ml.combust.mleap.runtime.serialization.FrameReader	
import ml.combust.mleap.runtime.frame.{DefaultLeapFrame, Row}
import ml.combust.mleap.core.types._
import ml.combust.mleap.runtime.frame.{LeapFrame, Row}

object Testing2 {
  def main(args: Array[String]) {
    println("Hello Scala sdfsadf!!")
    
    val mleapPipeline = {
      val bundle = BundleFile("file:/tmp/1320news_pipeline-json.zip")
      try {
        bundle.loadMleapBundle().get.root
      } finally {
        bundle.close()
      }
    }

    val working = StructType(StructField("device_type", ScalarType.String),
        StructField("is_pin_based", ScalarType.String),
        StructField("amount_processed_usd", ScalarType.Double),
        StructField("amount_requested_usd", ScalarType.Double),
        StructField("trans_day_of_week", ScalarType.String),
        StructField("trans_month", ScalarType.String)).get
    val data = Seq(Row("CR", "Y", 1.2d, 1.2d, "Friday", "December"))
    
    val dframe2 = DefaultLeapFrame(working, data)
    
    val frameTransformed = mleapPipeline.transform(dframe2).get
    val predictions = frameTransformed.select("prediction").get.dataset
    
    println(predictions)
    
  }
}

The Exception is:
Exception in thread "main" java.util.NoSuchElementException: key not found: 4.0
at scala.collection.immutable.Map$Map4.apply(Map.scala:187)
at ml.combust.mleap.core.feature.VectorIndexerModel.$anonfun$predict$2(VectorIndexerModel.scala:26)
at ml.combust.mleap.core.feature.VectorIndexerModel.$anonfun$predict$2$adapted(VectorIndexerModel.scala:25)
at scala.collection.immutable.Map$Map4.foreach(Map.scala:210)
at ml.combust.mleap.core.feature.VectorIndexerModel.predict(VectorIndexerModel.scala:25)
at ml.combust.mleap.core.feature.VectorIndexerModel.apply(VectorIndexerModel.scala:18)
at ml.combust.mleap.runtime.transformer.feature.VectorIndexer.$anonfun$exec$1(VectorIndexer.scala:16)
at ml.combust.mleap.runtime.frame.Row.udfValue(Row.scala:241)
at ml.combust.mleap.runtime.frame.Row.udfValue$(Row.scala:236)
at ml.combust.mleap.runtime.frame.ArrayRow.udfValue(ArrayRow.scala:17)
at ml.combust.mleap.runtime.frame.Row.withValue(Row.scala:221)
at ml.combust.mleap.runtime.frame.Row.withValue$(Row.scala:220)
at ml.combust.mleap.runtime.frame.ArrayRow.withValue(ArrayRow.scala:17)
at ml.combust.mleap.runtime.frame.DefaultLeapFrame.$anonfun$withColumn$3(DefaultLeapFrame.scala:54)
at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
at scala.collection.immutable.List.foreach(List.scala:389)
at scala.collection.TraversableLike.map(TraversableLike.scala:234)
at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
at scala.collection.immutable.List.map(List.scala:295)
at ml.combust.mleap.runtime.frame.DefaultLeapFrame.$anonfun$withColumn$2(DefaultLeapFrame.scala:54)
at scala.util.Success.$anonfun$map$1(Try.scala:251)
at scala.util.Success.map(Try.scala:209)
at ml.combust.mleap.runtime.frame.DefaultLeapFrame.$anonfun$withColumn$1(DefaultLeapFrame.scala:53)
at scala.util.Success.flatMap(Try.scala:247)
at ml.combust.mleap.runtime.frame.DefaultLeapFrame.withColumn(DefaultLeapFrame.scala:49)
at ml.combust.mleap.runtime.frame.SimpleTransformer.transform(Transformer.scala:112)
at ml.combust.mleap.runtime.frame.SimpleTransformer.transform$(Transformer.scala:111)
at ml.combust.mleap.runtime.transformer.feature.VectorIndexer.transform(VectorIndexer.scala:13)
at ml.combust.mleap.runtime.transformer.Pipeline.$anonfun$transform$3(Pipeline.scala:28)
at scala.util.Success.flatMap(Try.scala:247)
at ml.combust.mleap.runtime.transformer.Pipeline.$anonfun$transform$2(Pipeline.scala:28)
at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
at scala.collection.immutable.List.foldLeft(List.scala:86)
at ml.combust.mleap.runtime.transformer.Pipeline.transform(Pipeline.scala:28)
at Testing2$.main(Testing2.scala:32)
at Testing2.main(Testing2.scala)

**Comment by ancasarb** [comment]
@mtsol I've tried your example

```
from mleap import pyspark
from pyspark.ml.linalg import Vectors
from mleap.pyspark.spark_support import SimpleSparkSerializer
from pyspark.ml.feature import VectorAssembler, StandardScaler, OneHotEncoder, StringIndexer
from pyspark.ml import Pipeline, PipelineModel
from pyspark.ml.classification import RandomForestClassifier
from pyspark.sql import Row

string_indexer=StringIndexer(inputCol="DayOfWeek",outputCol="DayIndex")
string_indexer2=StringIndexer(inputCol="Category",outputCol="CategoryIndex")
string_indexer3=StringIndexer(inputCol="PdDistrict",outputCol="PdIndexed")
assembler=VectorAssembler(inputCols=["DayIndex", "CategoryIndex", "PdIndexed"],outputCol="features")
rf = RandomForestClassifier(labelCol="CategoryIndex",featuresCol="features",numTrees=20)
feature_modle_pipeline=Pipeline(stages=[string_indexer, string_indexer2, string_indexer3, assembler, rf])
model = feature_modle_pipeline.fit(train_df)
model.serializeToBundle("jar:file:/tmp/4_string_indexers_pyspark.example.zip", model.transform(train_df))
```

and I could serialize the model and deserialize and transform with it in Scala without issues. 

In the stack trace you posted

```
The Exception is:
Exception in thread "main" java.util.NoSuchElementException: key not found: 4.0
at scala.collection.immutable.Map$Map4.apply(Map.scala:187)
at ml.combust.mleap.core.feature.VectorIndexerModel.$anonfun$predict$2(VectorIndexerModel.scala:26)
at ml.combust.mleap.core.feature.VectorIndexerModel.$anonfun$predict$2$adapted(VectorIndexerModel.scala:25)
at scala.collection.immutable.Map$Map4.foreach(Map.scala:210)
at ml.combust.mleap.core.feature.VectorIndexerModel.predict(VectorIndexerModel.scala:25)
at ml.combust.mleap.core.feature.VectorIndexerModel.apply(VectorIndexerModel.scala:18)
```

I can see a VectorIndexer transformer, but I don't see any vector indexers in the pipeline with 4 string indexers, is that from the same pipeline? 

Looking at that error makes me think that you probably need to set the strategy for handleInvalid, which works similarly for vector indexers as it does for string indexers. It looks like it's found a label not seen during training, at scoring time.

**Comment by mtsol** [comment]
You are right, I've resolved the issue, my training data was very small so that some unseen data was occurring during prediction phase

Meanwhile, I'm having trouble writing custom mleap transformers, as a requirement, I want my Spark custom transformer in python.

**Comment by ancasarb** [comment]
Closing this, as there's another issue open for the Spark custom transformer in python.  https://github.com/combust/mleap/issues/552
