### ISSUE TITLE
Deserialization with multiple input_features fail

### ISSUE THREAD

**Issue by lucagiovagnoli** [combust/mleap#560]
I haven't manage to deserialize a scikit Logistic node with multiple input_features such as
```python
input_features = ['long_feature', 'double_feature']
```

Reading from python using deserialize_from_bundle [here](https://github.com/combust/mleap/blob/d276c1c800277a1edcf30dda6e8559c7413b21f8/python/mleap/sklearn/logistic.py#L37) I get:

```python
x = ['long_feature', 'double_feature']

    @staticmethod
    def _node_features_format(x):
>       if isinstance(x, str) or isinstance(x, unicode):
E       NameError: name 'unicode' is not defined
```

while reading using PySpark (going through Scala):
```java
E                   py4j.protocol.Py4JJavaError: An error occurred while calling o53.deserializeFromBundle.
E                   : spray.json.DeserializationException: Expected String as JsString, but got ["long_feature","double_feature"]
E                   	at spray.json.package$.deserializationError(package.scala:23)
E                   	at spray.json.ProductFormats$class.fromField(ProductFormats.scala:62)
E                   	at spray.json.DefaultJsonProtocol$.fromField(DefaultJsonProtocol.scala:30)
E                   	at spray.json.ProductFormatsInstances$$anon$2.read(ProductFormatsInstances.scala:56)
E                   	at spray.json.ProductFormatsInstances$$anon$2.read(ProductFormatsInstances.scala:46)
E                   	at spray.json.JsValue.convertTo(JsValue.scala:31)
E                   	at ml.combust.bundle.serializer.JsonFormatNodeSerializer$.read(NodeSerializer.scala:52)
E                   	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$1.apply(NodeSerializer.scala:100)
E                   	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$1.apply(NodeSerializer.scala:100)
E                   	at scala.util.Try$.apply(Try.scala:192)
E                   	at ml.combust.bundle.serializer.NodeSerializer.read(NodeSerializer.scala:100)
E                   	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$readNode$2.apply(GraphSerializer.scala:57)
E                   	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$readNode$2.apply(GraphSerializer.scala:57)
E                   	at scala.util.Success.flatMap(Try.scala:231)
E                   	at ml.combust.bundle.serializer.GraphSerializer.readNode(GraphSerializer.scala:56)
E                   	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$read$1.apply(GraphSerializer.scala:44)
E                   	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$read$1.apply(GraphSerializer.scala:44)
E                   	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
E                   	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
E                   	at scala.collection.immutable.List.foreach(List.scala:381)
E                   	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
E                   	at scala.collection.immutable.List.map(List.scala:285)
E                   	at ml.combust.bundle.serializer.GraphSerializer.read(GraphSerializer.scala:44)
E                   	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.load(PipelineOp.scala:27)
E                   	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.load(PipelineOp.scala:14)
E                   	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:106)
E                   	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$readWithModel$2.apply(ModelSerializer.scala:104)
E                   	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
E                   	at scala.util.Try$.apply(Try.scala:192)
E                   	at scala.util.Success.map(Try.scala:237)
E                   	at ml.combust.bundle.serializer.ModelSerializer.readWithModel(ModelSerializer.scala:103)
E                   	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$2.apply(NodeSerializer.scala:102)
E                   	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$read$2.apply(NodeSerializer.scala:101)
E                   	at scala.util.Success.flatMap(Try.scala:231)
E                   	at ml.combust.bundle.serializer.NodeSerializer.read(NodeSerializer.scala:100)
E                   	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$read$2.apply(BundleSerializer.scala:55)
E                   	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$read$2.apply(BundleSerializer.scala:49)
E                   	at scala.util.Success.flatMap(Try.scala:231)
E                   	at ml.combust.bundle.serializer.BundleSerializer.read(BundleSerializer.scala:49)
E                   	at ml.combust.bundle.BundleFile.load(BundleFile.scala:123)
E                   	at ml.combust.mleap.spark.SparkSupport$SparkBundleFileOps.loadSparkBundle(SparkSupport.scala:29)
E                   	at ml.combust.mleap.spark.SimpleSparkSerializer$$anonfun$deserializeFromBundle$2.apply(SimpleSparkSerializer.scala:34)
E                   	at ml.combust.mleap.spark.SimpleSparkSerializer$$anonfun$deserializeFromBundle$2.apply(SimpleSparkSerializer.scala:33)
E                   	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)
E                   	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
E                   	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)
E                   	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
E                   	at scala.util.control.Exception$Catch.either(Exception.scala:125)
E                   	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)
E                   	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
E                   	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
E                   	at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
E                   	at scala.util.Try$.apply(Try.scala:192)
E                   	at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
E                   	at ml.combust.mleap.spark.SimpleSparkSerializer.deserializeFromBundle(SimpleSparkSerializer.scala:35)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                   	at java.lang.reflect.Method.invoke(Method.java:498)
E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
E                   	at py4j.Gateway.invoke(Gateway.java:282)
E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E                   	at py4j.GatewayConnection.run(GatewayConnection.java:238)
E                   	at java.lang.Thread.run(Thread.java:745)
```

Seems that both expect that field to be a single string ?

**Comment by lucagiovagnoli** [comment]
What are we expected to pass in `input_features` ? 
Any deserializer expects a string to be there, what should I put for multiple features ?

**Comment by lucagiovagnoli** [comment]
For future reference, it seems that the [FeatureExtractor](https://github.com/combust/mleap/blob/30c1ce2c7e5ca81492514e1eadd79a8ec1b10a7a/python/mleap/sklearn/preprocessing/data.py#L195) step from the [docs](http://mleap-docs.combust.ml/scikit-learn/) solves this.
