### ISSUE TITLE
java.nio.file.FileSystemNotFoundException: Provider "hdfs" not installed when loadMleapBundle

### ISSUE THREAD

**Issue by yilongl** [combust/mleap#563]
Hi Experts,
Is it possible to load the model saved in hdfs? When I tried using the following code:
val mleapPipeline = (for(bf <- managed(BundleFile("jar:hdfs:///tmp/pipeline.zip"))) yield {
  bf.loadMleapBundle().get.root
}).tried.get

I got the following error:
java.nio.file.FileSystemNotFoundException: Provider "hdfs" not installed
  at java.nio.file.Paths.get(Paths.java:147)
  at com.sun.nio.zipfs.ZipFileSystemProvider.uriToPath(ZipFileSystemProvider.java:85)
  at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:107)
  at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
  at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
  at ml.combust.bundle.BundleFile$.apply(BundleFile.scala:70)
  at ml.combust.bundle.BundleFile$.apply(BundleFile.scala:40)
  at $anonfun$1.apply(<console>:95)
  at $anonfun$1.apply(<console>:95)
  at resource.DefaultManagedResource.open(AbstractManagedResource.scala:110)
  at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:87)
  at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
  at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
  at resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
  at scala.util.Try$.apply(Try.scala:192)
  at resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
  ... 69 elided

**Comment by ancasarb** [comment]
@yilongl looks like issue this is similar to https://github.com/combust/mleap/issues/420, let's use #420 to track this issue.

**Comment by FredYao** [comment]
Loading from HDFS is supported since PR https://github.com/combust/mleap/pull/415. Here is a toy example for how to do that in Scala:
`
import java.net.URI
import ml.combust.mleap.spark.SparkSupport._
import org.apache.spark.ml.bundle.SparkBundleContext
import ml.bundle.hdfs.HadoopBundleFileSystem
import org.apache.hadoop.conf.Configuration
import org.apache.hadoop.fs.FileSystem
import ml.combust.mleap.runtime.MleapContext
...

val fs = FileSystem.get(new Configuration())
val bundleFS = new HadoopBundleFileSystem(fs)
val modelPath = "/path/to/your/model_zip"   // assume a path on HDFS

val tmp = bundleFS.load(new URI(modelPath)).get
val model = (for(bf <- managed(BundleFile(s"jar:file:${tmp.getAbsolutePath}"))) yield bf.loadSparkBundle()}).tried.get
`
