### ISSUE TITLE
Support python 3

### ISSUE THREAD

**Issue by lucagiovagnoli** [combust/mleap#566]
I tried to run tests using python 3.6 and 12 failed.

```
test_word2vec (mleap.gensim.tests.TransformerTests) ... ok
imputer_ext_test (mleap.sklearn.extensions.tests.ExtensionsTests) ... ok
test_countvectorizer_serializer (mleap.sklearn.feature_extraction.tests.TransformerTests) ... ERROR
test_tfidf_vectorizer_serializer_idf_part (mleap.sklearn.feature_extraction.tests.TransformerTests) ... ERROR
test_tfidf_vectorizer_serializer_pipeline_part (mleap.sklearn.feature_extraction.tests.TransformerTests) ... ERROR
test_tfidf_vectorizer_serializer_tf_part (mleap.sklearn.feature_extraction.tests.TransformerTests) ... ERROR
binarizer_deserializer_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
binarizer_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
feature_extractor_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
imputer_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
label_encoder_deserializer_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
label_encoder_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... ERROR
math_binary_deserialize_add_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... /Users/luca/pg/mleap/python/mleap/sklearn/preprocessing/data.py:1011: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  x = y.ix[:,0]
/Users/luca/pg/mleap/python/mleap/sklearn/preprocessing/data.py:1012: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  y = y.ix[:,1]
FAIL
math_binary_divide_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... FAIL
math_binary_multiply_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... FAIL
math_binary_subtract_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... FAIL
math_binary_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... FAIL
math_unary_deserialize_exp_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
math_unary_exp_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
math_unary_sin_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
one_hot_encoder_deserializer_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
one_hot_encoder_serializer_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
polynomial_expansion_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... /Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:1263: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  for c in combinations)
ok
string_map_deserializer_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... ERROR
string_map_test (mleap.sklearn.preprocessing.tests.TransformerTests) ... ERROR
test_min_max_scaler_deserializer (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
test_min_max_scaler_multi_deserializer (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
test_min_max_scaler_serializer (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
test_standard_scaler_deserializer (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
test_standard_scaler_multi_deserializer (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
test_standard_scaler_serializer (mleap.sklearn.preprocessing.tests.TransformerTests) ... ok
test_decision_tree_classifier (mleap.sklearn.tree.tests.TransformerTests) ... ok
test_decision_tree_classifier_with_iris_dataset (mleap.sklearn.tree.tests.TransformerTests) ... ok
test_linear_regression_deserializer (mleap.sklearn.base_tests.TransformerTests) ... ok
test_linear_regression_serializer (mleap.sklearn.base_tests.TransformerTests) ... ok
test_logistic_regression_cv_deserializer (mleap.sklearn.base_tests.TransformerTests) ... /Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
ok
test_logistic_regression_cv_serializer (mleap.sklearn.base_tests.TransformerTests) ... ok
test_logistic_regression_deserializer (mleap.sklearn.base_tests.TransformerTests) ... ok
test_logistic_regression_serializer (mleap.sklearn.base_tests.TransformerTests) ... ok

======================================================================
ERROR: test_countvectorizer_serializer (mleap.sklearn.feature_extraction.tests.TransformerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/tests.py", line 28, in setUp
    self.tfidf.serialize_to_bundle(self.tmp_dir, self.tfidf.name)
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/text.py", line 35, in serialize_to_bundle
    return serializer.serialize_to_bundle(self, path, model_name)
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/text.py", line 85, in serialize_to_bundle
    serializer.serialize_to_bundle(transformer, path, model_name)
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/text.py", line 129, in serialize_to_bundle
    for term, termidx in transformer.vocabulary_.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

======================================================================
ERROR: test_tfidf_vectorizer_serializer_idf_part (mleap.sklearn.feature_extraction.tests.TransformerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/tests.py", line 28, in setUp
    self.tfidf.serialize_to_bundle(self.tmp_dir, self.tfidf.name)
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/text.py", line 35, in serialize_to_bundle
    return serializer.serialize_to_bundle(self, path, model_name)
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/text.py", line 85, in serialize_to_bundle
    serializer.serialize_to_bundle(transformer, path, model_name)
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/text.py", line 129, in serialize_to_bundle
    for term, termidx in transformer.vocabulary_.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

======================================================================
ERROR: test_tfidf_vectorizer_serializer_pipeline_part (mleap.sklearn.feature_extraction.tests.TransformerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/tests.py", line 28, in setUp
    self.tfidf.serialize_to_bundle(self.tmp_dir, self.tfidf.name)
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/text.py", line 35, in serialize_to_bundle
    return serializer.serialize_to_bundle(self, path, model_name)
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/text.py", line 85, in serialize_to_bundle
    serializer.serialize_to_bundle(transformer, path, model_name)
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/text.py", line 129, in serialize_to_bundle
    for term, termidx in transformer.vocabulary_.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

======================================================================
ERROR: test_tfidf_vectorizer_serializer_tf_part (mleap.sklearn.feature_extraction.tests.TransformerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/tests.py", line 28, in setUp
    self.tfidf.serialize_to_bundle(self.tmp_dir, self.tfidf.name)
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/text.py", line 35, in serialize_to_bundle
    return serializer.serialize_to_bundle(self, path, model_name)
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/text.py", line 85, in serialize_to_bundle
    serializer.serialize_to_bundle(transformer, path, model_name)
  File "/Users/luca/pg/mleap/python/mleap/sklearn/feature_extraction/text.py", line 129, in serialize_to_bundle
    for term, termidx in transformer.vocabulary_.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

======================================================================
ERROR: label_encoder_test (mleap.sklearn.preprocessing.tests.TransformerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/luca/pg/mleap/python/mleap/sklearn/preprocessing/tests.py", line 333, in label_encoder_test
    self.assertEqual('nullable_input', model['attributes'].keys()[0])
TypeError: 'dict_keys' object is not subscriptable

======================================================================
ERROR: string_map_deserializer_test (mleap.sklearn.preprocessing.tests.TransformerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/luca/pg/mleap/python/mleap/sklearn/preprocessing/tests.py", line 952, in string_map_deserializer_test
    string_map.serialize_to_bundle(self.tmp_dir, string_map.name)
  File "/Users/luca/pg/mleap/python/mleap/sklearn/preprocessing/data.py", line 1114, in serialize_to_bundle
    self.serialize(self, path, model_name, attributes, inputs, outputs)
  File "/Users/luca/pg/mleap/python/mleap/bundle/serialize.py", line 160, in serialize
    json.dump(self.get_mleap_model(transformer, attributes), outfile, indent=3)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dict_values is not JSON serializable

======================================================================
ERROR: string_map_test (mleap.sklearn.preprocessing.tests.TransformerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/luca/pg/mleap/python/mleap/sklearn/preprocessing/tests.py", line 917, in string_map_test
    string_map_tf.serialize_to_bundle(self.tmp_dir, string_map_tf.name)
  File "/Users/luca/pg/mleap/python/mleap/sklearn/preprocessing/data.py", line 1114, in serialize_to_bundle
    self.serialize(self, path, model_name, attributes, inputs, outputs)
  File "/Users/luca/pg/mleap/python/mleap/bundle/serialize.py", line 160, in serialize
    json.dump(self.get_mleap_model(transformer, attributes), outfile, indent=3)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dict_values is not JSON serializable

======================================================================
FAIL: math_binary_deserialize_add_test (mleap.sklearn.preprocessing.tests.TransformerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/luca/pg/mleap/python/mleap/sklearn/preprocessing/tests.py", line 791, in math_binary_deserialize_add_test
    assert_frame_equal(pd.DataFrame(self.df.a + self.df.b, columns=['a']), Xres)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 1372, in assert_frame_equal
    obj="{obj}.columns".format(obj=obj),
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 635, in assert_index_equal
    _check_types(left, right, obj=obj)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 611, in _check_types
    assert_class_equal(l, r, exact=exact, obj=obj)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 728, in assert_class_equal
    raise_assert_detail(obj, msg, repr_class(left), repr_class(right))
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 932, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.columns are different

DataFrame.columns classes are not equivalent
[left]:  Index(['a'], dtype='object')
[right]: RangeIndex(start=0, stop=1, step=1)

======================================================================
FAIL: math_binary_divide_test (mleap.sklearn.preprocessing.tests.TransformerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/luca/pg/mleap/python/mleap/sklearn/preprocessing/tests.py", line 877, in math_binary_divide_test
    assert_frame_equal(pd.DataFrame(self.df.a / self.df.b, columns=['a']), Xres)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 1372, in assert_frame_equal
    obj="{obj}.columns".format(obj=obj),
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 635, in assert_index_equal
    _check_types(left, right, obj=obj)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 611, in _check_types
    assert_class_equal(l, r, exact=exact, obj=obj)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 728, in assert_class_equal
    raise_assert_detail(obj, msg, repr_class(left), repr_class(right))
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 932, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.columns are different

DataFrame.columns classes are not equivalent
[left]:  Index(['a'], dtype='object')
[right]: RangeIndex(start=0, stop=1, step=1)

======================================================================
FAIL: math_binary_multiply_test (mleap.sklearn.preprocessing.tests.TransformerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/luca/pg/mleap/python/mleap/sklearn/preprocessing/tests.py", line 843, in math_binary_multiply_test
    assert_frame_equal(pd.DataFrame(self.df.a * self.df.b, columns=['a']), Xres)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 1372, in assert_frame_equal
    obj="{obj}.columns".format(obj=obj),
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 635, in assert_index_equal
    _check_types(left, right, obj=obj)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 611, in _check_types
    assert_class_equal(l, r, exact=exact, obj=obj)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 728, in assert_class_equal
    raise_assert_detail(obj, msg, repr_class(left), repr_class(right))
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 932, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.columns are different

DataFrame.columns classes are not equivalent
[left]:  Index(['a'], dtype='object')
[right]: RangeIndex(start=0, stop=1, step=1)

======================================================================
FAIL: math_binary_subtract_test (mleap.sklearn.preprocessing.tests.TransformerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/luca/pg/mleap/python/mleap/sklearn/preprocessing/tests.py", line 809, in math_binary_subtract_test
    assert_frame_equal(pd.DataFrame(self.df.a - self.df.b, columns=['a']), Xres)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 1372, in assert_frame_equal
    obj="{obj}.columns".format(obj=obj),
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 635, in assert_index_equal
    _check_types(left, right, obj=obj)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 611, in _check_types
    assert_class_equal(l, r, exact=exact, obj=obj)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 728, in assert_class_equal
    raise_assert_detail(obj, msg, repr_class(left), repr_class(right))
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 932, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.columns are different

DataFrame.columns classes are not equivalent
[left]:  Index(['a'], dtype='object')
[right]: RangeIndex(start=0, stop=1, step=1)

======================================================================
FAIL: math_binary_test (mleap.sklearn.preprocessing.tests.TransformerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/luca/pg/mleap/python/mleap/sklearn/preprocessing/tests.py", line 757, in math_binary_test
    assert_frame_equal(pd.DataFrame(self.df.a + self.df.b, columns=['a']), Xres)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 1372, in assert_frame_equal
    obj="{obj}.columns".format(obj=obj),
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 635, in assert_index_equal
    _check_types(left, right, obj=obj)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 611, in _check_types
    assert_class_equal(l, r, exact=exact, obj=obj)
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 728, in assert_class_equal
    raise_assert_detail(obj, msg, repr_class(left), repr_class(right))
  File "/Users/luca/pg/mleap/venv3/lib/python3.7/site-packages/pandas/util/testing.py", line 932, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.columns are different

DataFrame.columns classes are not equivalent
[left]:  Index(['a'], dtype='object')
[right]: RangeIndex(start=0, stop=1, step=1)

----------------------------------------------------------------------
Ran 39 tests in 1.574s

FAILED (errors=7, failures=5)
```

**Comment by ancasarb** [comment]
@lucagiovagnoli Sorry, merging the PR closed this issue automatically, was there anything else required for this issue?

**Comment by lucagiovagnoli** [comment]
No that's perfect. Thanks!
