### ISSUE TITLE
Can't Serialize Pipeline Model to Bundle.ML

### ISSUE THREAD

**Issue by LDH007** [combust/mleap#577]
my env:
spark version:2.4.4
scala version:2.11.12

first start spark
./bin/spark-shell --jars config-1.3.4.jar,scala-arm_2.12-2.0.jar,scala-library-2.12.8.jar,scala-util_2.12-1.13.6.jar,bundle-ml_2.11-0.1.1.jar --packages ml.combust.mleap:mleap-spark_2.11:0.14.0 --master local[*]
 then the code is 

import ml.combust.mleap.spark.SparkSupport._
import ml.combust.bundle.BundleFile
import org.apache.spark.ml.bundle.SparkBundleContext
import org.apache.spark.ml.feature.{FeatureHasher,VectorAssembler}
import org.apache.spark.ml.{Pipeline,PipelineModel}
import org.apache.spark.{SparkContext,SparkConf}
import resource._
import org.apache.spark.ml.classification.LogisticRegression
import org.apache.spark.ml.mleap.SparkUtil

val trainDf=spark.read.(........)
val lrModel = PipelineModel.load("./spark_scala_pipe.model")

val sbc = SparkBundleContext().withDataset(lrModel.transform(trainDf))
!!!!!!!! when i run the last code ,get error like this , don't know how to solve this 

java.lang.NoClassDefFoundError: ml/bundle/hdfs/HadoopBundleFileSystem
  at org.apache.spark.ml.bundle.SparkBundleContext.withDataset(SparkBundleContext.scala:32)
  at org.apache.spark.ml.bundle.SparkBundleContext.withDataset(SparkBundleContext.scala:27)
  ... 53 elided
Caused by: java.lang.ClassNotFoundException: ml.bundle.hdfs.HadoopBundleFileSystem
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 55 more

**Comment by Alucardmini** [comment]
Hi, I meet the same problem, Can you tell me how to make it work?
