### ISSUE TITLE
Azure Databricks Pyspark - java.nio.file.NoSuchFileException

### ISSUE THREAD

**Issue by lucmascia** [combust/mleap#609]
Hey everyone,

I'm trying to implement MLeap on my Azure Databricks pyspark notebook to export my pipeline model to our hystory zone on our azure datalake gen 2 - which is mounted to my databricks - and, later on, import on another notebook. However, when i run the command **serializeToBundle** an error is raised. I have searched everywhere and tried my best to look at all the issues here already created, but no luck. Help please

`fittedPipelineModel.serializeToBundle("jar:file:{}.zip".format(dirPipelines), dataset=predictionsData)`

The following error is raised:
```
java.nio.file.NoSuchFileException: /mnt/historyzone/Brazil/Algorithm/ProjectOA/Pipelines/201911/PipelineModel_3c1b42d2eb70.zip

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-1445515191982005> in <module>
     18 print('Exportando PIPELINE para History Zone....')
     19 print("jar:file:{}.zip".format(dirPipelines))
---> 20 fittedPipelineModel.serializeToBundle("jar:file:{}.zip".format(dirPipelines), dataset=predictionsData)
     21 
     22 # predictionsData = fittedPipelineModel.transform(testData)

/databricks/python/lib/python3.7/site-packages/mleap/pyspark/spark_support.py in serializeToBundle(self, path, dataset)
     23 def serializeToBundle(self, path, dataset=None):
     24     serializer = SimpleSparkSerializer()
---> 25     serializer.serializeToBundle(self, path, dataset=dataset)
     26 
     27 

/databricks/python/lib/python3.7/site-packages/mleap/pyspark/spark_support.py in serializeToBundle(self, transformer, path, dataset)
     40 
     41     def serializeToBundle(self, transformer, path, dataset):
---> 42         self._java_obj.serializeToBundle(transformer._to_java(), path, dataset._jdf)
     43 
     44     def deserializeFromBundle(self, path):

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o24697.serializeToBundle.
: java.nio.file.NoSuchFileException: /mnt/historyzone/Brazil/Algorithm/ProjectOA/Pipelines/201911/PipelineModel_3c1b42d2eb70.zip
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:116)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276)
	at ml.combust.bundle.BundleFile$.apply(BundleFile.scala:70)
	at ml.combust.bundle.BundleFile$.apply(BundleFile.scala:40)
	at ml.combust.mleap.spark.SimpleSparkSerializer$$anonfun$serializeToBundleWithFormat$1.apply(SimpleSparkSerializer.scala:25)
	at ml.combust.mleap.spark.SimpleSparkSerializer$$anonfun$serializeToBundleWithFormat$1.apply(SimpleSparkSerializer.scala:25)
	at ml.combust.mleap.shaded.resource.DefaultManagedResource.open(AbstractManagedResource.scala:110)
	at ml.combust.mleap.shaded.resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:87)
	at ml.combust.mleap.shaded.resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)
	at ml.combust.mleap.shaded.resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)
	at ml.combust.mleap.shaded.resource.DeferredExtractableManagedResource$$anonfun$tried$1.apply(AbstractManagedResource.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.mleap.shaded.resource.DeferredExtractableManagedResource.tried(AbstractManagedResource.scala:33)
	at ml.combust.mleap.spark.SimpleSparkSerializer.serializeToBundleWithFormat(SimpleSparkSerializer.scala:27)
	at ml.combust.mleap.spark.SimpleSparkSerializer.serializeToBundle(SimpleSparkSerializer.scala:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

My pipeline is built like this:
```
stagesList = []

for col in varsCategoricas:
    indexer = StringIndexer(inputCol = col,
                            outputCol = col + 'Indexed')
    encoder = OneHotEncoderEstimator(inputCols = [indexer.getOutputCol()],
                                     outputCols = [col + "classVec"])
    stagesList += [indexer, encoder]

for col in cols_valoresFaltantes:
    imputer = Imputer(strategy='median'
                      ,inputCols = [col]
                      ,outputCols = [col + '_imputed'])
    stagesList += [imputer]

assemblerInputs = [c + "classVec" for c in varsCategoricas] + [c + "_imputed" for c in cols_valoresFaltantes] + varsCalculadas
assembler = VectorAssembler(inputCols=assemblerInputs,
                            outputCol="featuresVec")

scalar = Normalizer(inputCol = assembler.getOutputCol(),
                    outputCol="features")

stagesList += [imputer, assembler, scalar]

objModel = RandomForestClassifier(labelCol="label_churn_cerveja", featuresCol="features", seed=randomSeed)

paramGrid = ParamGridBuilder() \
    .addGrid(objModel.numTrees, [250]) \
    .addGrid(objModel.impurity, ['entropy']) \
    .build()

objEvaluator = BinaryClassificationEvaluator(labelCol = "label_churn_cerveja", rawPredictionCol = "prediction", metricName = "areaUnderPR")

numFolds = 5
parll = 8

crossVal = CrossValidator(
              estimator = objModel
              ,estimatorParamMaps = paramGrid
              ,evaluator = objEvaluator
              ,numFolds = numFolds
              ,seed = randomSeed
              ,parallelism = parll)

stagesList += [crossVal]

objPipeline = Pipeline(stages=stagesList)

fittedPipelineModel = objPipeline.fit(trainingData)
predictionsData = fittedPipelineModel.transform(testData)

fittedPipelineModel.serializeToBundle("jar:file:{}.zip".format(dirPipelines), dataset=predictionsData)
```

I'm running the following:

**- Configs -**
Databricks 6.0 ML
Spark 2.4.3 (also tryed 2.4.4 but same error)
Scala 2.11
Python 3

**- Libraries installed -**
PyPI - mleap
PyPI - jip
Maven - com.trueaccord.lenses:lenses_2.12:0.4.12
Maven - ml.combust.mleap:mleap-base_2.12:0.15.0
Maven - ml.combust.mleap:mleap-core_2.12:0.15.0
Maven - ml.combust.mleap:mleap-executor_2.12:0.15.0
Maven - ml.combust.mleap:mleap-runtime_2.12:0.15.0
Maven - ml.combust.mleap:mleap-serving_2.12:0.15.0
Maven - ml.combust.mleap:mleap-spark-extension_2.12:0.15.0
Maven - ml.combust.mleap:mleap-spark_2.12:0.15.0
Maven - ml.combust.mleap:mleap-spring-boot_2.12:0.15.0

**Comment by ancasarb** [comment]
I am not too sure about your setup, but maybe you could try to serialize it to /tmp as in Step 8 in the example here https://github.com/ancasarb/mleap-demo/blob/master/notebooks/PySpark%20-%20AirBnb.ipynb and see if that works?

**Comment by ancasarb** [comment]
@lucmascia To be able to get this working, you need to first save the zipped bundle to a local file and then move it for e.g.

```
fittedPipeline.serializeToBundle("jar:file:/tmp/003pyspark.example-anca.zip", fittedPipeline.transform(df2))
dbutils.fs.put("/mnt/test/003pyspark.example-anca.zip", "/tmp/003pyspark.example-anca.zip")
```

Hope this helps! 

I am going to close this in preparation of releasing mleap version 0.16.0, please re-open if you are still having issues. Thank you!
