### ISSUE TITLE
Error running custom transformer model in spring-boot

### ISSUE THREAD

**Issue by femibyte** [combust/mleap#610]
I'm getting an error while trying to run my serialized model on spring-boot. 
```
curl --header "Content-Type: application/json" --request POST --data "$LEAP_FRAME" \
http://localhost:${PORT}/models/mymodel/transform
```

The stack trace looks like this:
```
09:05:32 ERROR LeapFrameScoringController {ml.combust.mleap.springboot.LeapFrameScoringController ml$combust$mleap$springboot$LeapFrameScoringController$$handleTransformFailure} - Transform error due to
scala.MatchError: 8 (of class java.lang.Integer)
	at ml.combust.mleap.runtime.frame.Row$class.udfValue(Row.scala:237)
	at ml.combust.mleap.runtime.frame.ArrayRow.udfValue(ArrayRow.scala:17)
	at ml.combust.mleap.runtime.frame.Row$class.withValues(Row.scala:225)
	at ml.combust.mleap.runtime.frame.ArrayRow.withValues(ArrayRow.scala:17)
	at ml.combust.mleap.runtime.frame.DefaultLeapFrame$$anonfun$withColumns$1$$anonfun$apply$3$$anonfun$4.apply(DefaultLeapFrame.scala:79)
	at ml.combust.mleap.runtime.frame.DefaultLeapFrame$$anonfun$withColumns$1$$anonfun$apply$3$$anonfun$4.apply(DefaultLeapFrame.scala:79)
...
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at ml.combust.mleap.runtime.frame.DefaultLeapFrame$$anonfun$withColumns$1.apply(DefaultLeapFrame.scala:77)
	at ml.combust.mleap.runtime.frame.DefaultLeapFrame$$anonfun$withColumns$1.apply(DefaultLeapFrame.scala:72)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.mleap.runtime.frame.DefaultLeapFrame.withColumns(DefaultLeapFrame.scala:71)
	at ml.combust.mleap.runtime.frame.MultiTransformer$class.transform(Transformer.scala:139)
	at com.MyModelMleapTransformer.transform(MyModelMleapTransformer.scala:16)
	at ml.combust.mleap.runtime.frame.Transformer$class.transformAsync(Transformer.scala:101)
	at com.MyModelMleapTransformer.transformAsync(MyModelMleapTransformer.scala:16)
```

Can anyone suggest how I can debug this ? I call a udf as follows :
`override val exec: UserDefinedFunction = (columns: Seq[String]) => model(columns)`

**Comment by femibyte** [comment]
Come to think of it, I haven't seen any mleap transformers where there are multiple input columns. Is that the problem ? @ancasarb
