### ISSUE TITLE
No configuration setting found for key 'ml.combust.mleap.spark'

### ISSUE THREAD

**Issue by dreambird323** [combust/mleap#656]
Hi, I am using the `gradle` and `jar` plugin to package my uber jar, I got the below exception, very similar to https://github.com/combust/mleap/issues/252, like below

```
20/03/23 19:12:09 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'ml.combust.mleap.spark'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:145)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:172)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:258)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:264)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:37)
	at ml.combust.bundle.BundleRegistry$.apply(BundleRegistry.scala:35)
	at ml.combust.bundle.BundleRegistry$.apply(BundleRegistry.scala:28)
	at org.apache.spark.ml.bundle.SparkBundleContext$.apply(SparkBundleContext.scala:21)
	at org.apache.spark.ml.bundle.SparkBundleContext$.apply(SparkBundleContext.scala:17)
```	

However, I do have the reference.conf which kind of have the content, though a little bit more than 
https://github.com/combust/mleap/blob/master/mleap-spark/src/main/resources/reference.conf

as below
```
ml.combust.mleap.spark.registry.builtin-ops = [
  "org.apache.spark.ml.bundle.ops.classification.DecisionTreeClassifierOp",
  "org.apache.spark.ml.bundle.ops.classification.NaiveBayesClassifierOp",
  "org.apache.spark.ml.bundle.ops.classification.MultiLayerPerceptronClassifierOp",
  "org.apache.spark.ml.bundle.ops.classification.OneVsRestOp",
  "org.apache.spark.ml.bundle.ops.classification.RandomForestClassifierOp",

  "org.apache.spark.ml.bundle.ops.clustering.GaussianMixtureOp",
  "org.apache.spark.ml.bundle.ops.clustering.KMeansOp",
  "org.apache.spark.ml.bundle.ops.clustering.BisectingKMeansOp",
  "org.apache.spark.ml.bundle.ops.clustering.LDAModelOp",

  "org.apache.spark.ml.bundle.ops.feature.BinarizerOp",
  "org.apache.spark.ml.bundle.ops.feature.BucketizerOp",
  "org.apache.spark.ml.bundle.ops.feature.ChiSqSelectorOp",
  "org.apache.spark.ml.bundle.ops.feature.CountVectorizerOp",
  "org.apache.spark.ml.bundle.ops.feature.DCTOp",
  "org.apache.spark.ml.bundle.ops.feature.ElementwiseProductOp",
  "org.apache.spark.ml.bundle.ops.feature.HashingTermFrequencyOp",
  "org.apache.spark.ml.bundle.ops.feature.IDFOp",
  "org.apache.spark.ml.bundle.ops.feature.InteractionOp",
  "org.apache.spark.ml.bundle.ops.feature.MaxAbsScalerOp",
  "org.apache.spark.ml.bundle.ops.feature.MinMaxScalerOp",
  "org.apache.spark.ml.bundle.ops.feature.NGramOp",
  "org.apache.spark.ml.bundle.ops.feature.NormalizerOp",
  "org.apache.spark.ml.bundle.ops.feature.PcaOp",
  "org.apache.spark.ml.bundle.ops.feature.PolynomialExpansionOp",
  "org.apache.spark.ml.bundle.ops.feature.ReverseStringIndexerOp",
  "org.apache.spark.ml.bundle.ops.feature.StandardScalerOp",
  "org.apache.spark.ml.bundle.ops.feature.StopWordsRemoverOp",
  "org.apache.spark.ml.bundle.ops.feature.TokenizerOp",
  "org.apache.spark.ml.bundle.ops.feature.VectorAssemblerOp",
  "org.apache.spark.ml.bundle.ops.feature.VectorIndexerOp",
  "org.apache.spark.ml.bundle.ops.feature.VectorSlicerOp",
  "org.apache.spark.ml.bundle.ops.feature.WordToVectorOp",
  "org.apache.spark.ml.bundle.ops.feature.RegexTokenizerOp",

  "org.apache.spark.ml.bundle.ops.regression.AFTSurvivalRegressionOp",
  "org.apache.spark.ml.bundle.ops.regression.DecisionTreeRegressionOp",
  "org.apache.spark.ml.bundle.ops.regression.GBTRegressionOp",
  "org.apache.spark.ml.bundle.ops.regression.GeneralizedLinearRegressionOp",
  "org.apache.spark.ml.bundle.ops.regression.IsotonicRegressionOp",
  "org.apache.spark.ml.bundle.ops.regression.LinearRegressionOp",
  "org.apache.spark.ml.bundle.ops.regression.RandomForestRegressionOp",

  "org.apache.spark.ml.bundle.ops.recommendation.ALSOp",

  "org.apache.spark.ml.bundle.ops.tuning.CrossValidatorOp",
  "org.apache.spark.ml.bundle.ops.tuning.TrainValidationSplitOp",

  "org.apache.spark.ml.bundle.ops.feature.MinHashLSHOp",
  "org.apache.spark.ml.bundle.ops.feature.BucketedRandomProjectionLSHOp",
  "org.apache.spark.ml.bundle.ops.classification.GBTClassifierOp",
  "org.apache.spark.ml.bundle.ops.classification.LogisticRegressionOp",
  "org.apache.spark.ml.bundle.ops.feature.FeatureHasherOp",
  "org.apache.spark.ml.bundle.ops.feature.StringIndexerOp",
  "org.apache.spark.ml.bundle.ops.feature.OneHotEncoderOp",

  "org.apache.spark.ml.bundle.ops.PipelineOp"
]

ml.combust.mleap.spark.registry.default.ops += "ml.combust.mleap.spark.registry.builtin-ops"

ml.combust.mleap.registry.builtin-ops = [
  "ml.combust.mleap.bundle.ops.classification.DecisionTreeClassifierOp",
  "ml.combust.mleap.bundle.ops.classification.GBTClassifierOp",
  "ml.combust.mleap.bundle.ops.classification.LogisticRegressionOp",
  "ml.combust.mleap.bundle.ops.classification.NaiveBayesClassifierOp",
  "ml.combust.mleap.bundle.ops.classification.MultiLayerPerceptronClassifierOp",
  "ml.combust.mleap.bundle.ops.classification.OneVsRestOp",
  "ml.combust.mleap.bundle.ops.classification.RandomForestClassifierOp",
  "ml.combust.mleap.bundle.ops.classification.SupportVectorMachineOp",

  "ml.combust.mleap.bundle.ops.clustering.GaussianMixtureOp",
  "ml.combust.mleap.bundle.ops.clustering.KMeansOp",
  "ml.combust.mleap.bundle.ops.clustering.BisectingKMeansOp",
  "ml.combust.mleap.bundle.ops.clustering.LDAModelOp",

  "ml.combust.mleap.bundle.ops.feature.BinarizerOp",
  "ml.combust.mleap.bundle.ops.sklearn.BinarizerOp",
  "ml.combust.mleap.bundle.ops.feature.BucketedRandomProjectionLSHOp",
  "ml.combust.mleap.bundle.ops.feature.BucketizerOp",
  "ml.combust.mleap.bundle.ops.feature.ChiSqSelectorOp",
  "ml.combust.mleap.bundle.ops.feature.CoalesceOp",
  "ml.combust.mleap.bundle.ops.feature.CountVectorizerOp",
  "ml.combust.mleap.bundle.ops.feature.DCTOp",
  "ml.combust.mleap.bundle.ops.feature.ElementwiseProductOp",
  "ml.combust.mleap.bundle.ops.feature.FeatureHasherOp",
  "ml.combust.mleap.bundle.ops.feature.HashingTermFrequencyOp",
  "ml.combust.mleap.bundle.ops.feature.IDFOp",
  "ml.combust.mleap.bundle.ops.feature.ImputerOp",
  "ml.combust.mleap.bundle.ops.feature.InteractionOp",
  "ml.combust.mleap.bundle.ops.feature.MathBinaryOp",
  "ml.combust.mleap.bundle.ops.feature.MathUnaryOp",
  "ml.combust.mleap.bundle.ops.feature.MaxAbsScalerOp",
  "ml.combust.mleap.bundle.ops.feature.MinHashLSHOp",
  "ml.combust.mleap.bundle.ops.feature.MinMaxScalerOp",
  "ml.combust.mleap.bundle.ops.feature.MultinomialLabelerOp",
  "ml.combust.mleap.bundle.ops.feature.NGramOp",
  "ml.combust.mleap.bundle.ops.feature.NormalizerOp",
  "ml.combust.mleap.bundle.ops.feature.OneHotEncoderOp",
  "ml.combust.mleap.bundle.ops.feature.PcaOp",
  "ml.combust.mleap.bundle.ops.feature.PolynomialExpansionOp",
  "ml.combust.mleap.bundle.ops.sklearn.PolynomialFeaturesOp",
  "ml.combust.mleap.bundle.ops.feature.ReverseStringIndexerOp",
  "ml.combust.mleap.bundle.ops.feature.StandardScalerOp",
  "ml.combust.mleap.bundle.ops.feature.StopWordsRemoverOp",
  "ml.combust.mleap.bundle.ops.feature.StringIndexerOp",
  "ml.combust.mleap.bundle.ops.feature.StringMapOp",
  "ml.combust.mleap.bundle.ops.feature.TokenizerOp",
  "ml.combust.mleap.bundle.ops.feature.VectorAssemblerOp",
  "ml.combust.mleap.bundle.ops.feature.VectorIndexerOp",
  "ml.combust.mleap.bundle.ops.feature.VectorSlicerOp",
  "ml.combust.mleap.bundle.ops.feature.WordToVectorOp",
  "ml.combust.mleap.bundle.ops.feature.RegexTokenizerOp",
  "ml.combust.mleap.bundle.ops.feature.RegexIndexerOp",
  "ml.combust.mleap.bundle.ops.feature.WordLengthFilterOp",

  "ml.combust.mleap.bundle.ops.regression.AFTSurvivalRegressionOp",
  "ml.combust.mleap.bundle.ops.regression.DecisionTreeRegressionOp",
  "ml.combust.mleap.bundle.ops.regression.GBTRegressionOp",
  "ml.combust.mleap.bundle.ops.regression.GeneralizedLinearRegressionOp",
  "ml.combust.mleap.bundle.ops.regression.IsotonicRegressionOp",
  "ml.combust.mleap.bundle.ops.regression.LinearRegressionOp",
  "ml.combust.mleap.bundle.ops.regression.RandomForestRegressionOp",

  "ml.combust.mleap.bundle.ops.ensemble.CategoricalDrilldownOp",

  "ml.combust.mleap.bundle.ops.recommendation.ALSOp",

  "ml.combust.mleap.bundle.ops.PipelineOp"
]

ml.combust.mleap.registry.default.ops += "ml.combust.mleap.registry.builtin-ops"

// Configure a default HDFS bundle file system
ml.combust.mleap.hdfs.default = {
  class = ml.bundle.hdfs.HadoopBundleFileSystem

  test {
    "hello.there" = "mang"
  }

  // Configure the registered schemes that point to this
  // Bundle file system. This is useful if you have the
  // HDFS and S3 file systems configured with Hadoop
  // And want to use both of them
  //
  // schemes = ["hdfs", "s3"]

  // This is used to configure the Hadoop Configuration
  // This is only needed if the default configuration
  // won't work for some reason
  //
  // Configuration options found here:
  //   https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/ClusterSetup.html
  //
  // options {
  //   "fs.defaultFS" = "hdfs://defaultfs:1234/"
  // }
}

// Register the default FS with the default bundle registry
ml.combust.mleap.registry.default.file-systems += ${ml.combust.mleap.hdfs.default}
```

I actually tried the `shadowJar` plugin in gradle and use the transformer like below
```
    transform(com.github.jengelman.gradle.plugins.shadow.transformers.AppendingTransformer) {
        resource = 'reference.conf'
    }
```

but the content is the same, also I have other difficulty to work with `shadowJar` with other plugin, so it will be better if I can just stick to the `jar` plugin

appreciate the help, thanks in advance !

**Comment by dreambird323** [comment]
I am using mleap 0.14.0 and spark 2.4.0 and scala 2.11

**Comment by dreambird323** [comment]
so the additional `ml.combust.mleap.registry.builtin-ops` and `ml.combust.mleap.hdfs.default` section shouldn't be a concern, is it ?

**Comment by dreambird323** [comment]
I did a line by line comparison, one section is different

instead of 
```
  "org.apache.spark.ml.bundle.ops.feature.MinHashLSHOp",
  "org.apache.spark.ml.bundle.ops.feature.BucketedRandomProjectionLSHOp",
  "org.apache.spark.ml.bundle.ops.classification.GBTClassifierOp",
  "org.apache.spark.ml.bundle.ops.classification.LogisticRegressionOp",
  "org.apache.spark.ml.classification.bundle.ops.LinearSVCOp",
  "org.apache.spark.ml.bundle.ops.feature.FeatureHasherOp",
  "org.apache.spark.ml.bundle.ops.feature.StringIndexerOp",
  "org.apache.spark.ml.bundle.ops.feature.OneHotEncoderOp",
```

I have below, is that the reason ? since the whole `ml.combust.mleap.spark.registry` has been registered, not sure whether this diff is related to the exception
```
  "org.apache.spark.ml.bundle.ops.feature.MinHashLSHOp",
  "org.apache.spark.ml.bundle.ops.feature.BucketedRandomProjectionLSHOp",
  "org.apache.spark.ml.bundle.ops.classification.GBTClassifierOp",
  "org.apache.spark.ml.bundle.ops.classification.LogisticRegressionOp",
  "org.apache.spark.ml.bundle.ops.feature.FeatureHasherOp",
  "org.apache.spark.ml.bundle.ops.feature.StringIndexerOp",
  "org.apache.spark.ml.bundle.ops.feature.OneHotEncoderOp",
```

**Comment by dreambird323** [comment]
also, other place may be wrong is my `jar` plugin filter out some content, maybe this is related

```
jar {
    zip64 = true
    baseName = "${uber_jar_prefix}"
    from { (configurations.runtime).collect { it.isDirectory() ? it : zipTree(it) } } {
        exclude 'META-INF/*.RSA', 'META-INF/*.SF', 'META-INF/*.DSA'
    }
}
```

**Comment by dreambird323** [comment]
I just found I have 3 `reference.conf` in the jar, is the why append transformer is needed ?

**Comment by dreambird323** [comment]
shadowJar resolved it
