### ISSUE TITLE
Failed to execute mleap-spring-boot jar file

### ISSUE THREAD

**Issue by prafulrana21** [combust/mleap#657]
Hi @hollinwilkins , I am trying to create a single executable jar of mleap spring-boot application for development. 
And Tried these steps: 
1. sbt compile
2. sbt mleap-spring-boot/package
3. scala mleap-spring-boot_2.11-0.16.0-SNAPSHOT.jar 
but getting this error while execiting this jar file 
```
java.lang.ClassNotFoundException: scala.App$class
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at ml.combust.mleap.springboot.Starter$.<init>(Starter.scala:3)
        at ml.combust.mleap.springboot.Starter$.<clinit>(Starter.scala)
        at ml.combust.mleap.springboot.Starter.main(Starter.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala.reflect.internal.util.ScalaClassLoader.$anonfun$run$2(ScalaClassLoader.scala:105)
        at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:40)
        at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:130)
        at scala.reflect.internal.util.ScalaClassLoader.run(ScalaClassLoader.scala:105)
        at scala.reflect.internal.util.ScalaClassLoader.run$(ScalaClassLoader.scala:97)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:130)
        at scala.tools.nsc.CommonRunner.run(ObjectRunner.scala:29)
        at scala.tools.nsc.CommonRunner.run$(ObjectRunner.scala:28)
        at scala.tools.nsc.JarRunner$.run(MainGenericRunner.scala:17)
        at scala.tools.nsc.CommonRunner.runAndCatch(ObjectRunner.scala:35)
        at scala.tools.nsc.CommonRunner.runAndCatch$(ObjectRunner.scala:34)
        at scala.tools.nsc.JarRunner$.runJar(MainGenericRunner.scala:17)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:76)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by ancasarb** [comment]
to build the executable/fat jar, you need to use `sbt mleap-spring-boot/assembly` vs. `sbt mleap-spring-boot/package`. that will build the executable jar that you need.

you may need to specify an assembly strategy for that, something similar (but maybe not exactly the same) as 

```
assemblyMergeStrategy in assembly := {
  case PathList("META-INF", "spring.factories", xs@_*) => MergeStrategy.concat
  case PathList("META-INF", xs @ _*) => MergeStrategy.discard
  case x => MergeStrategy.first
}
```

if you're still facing issues, feel free to re-open the issue. thanks!
