### ISSUE TITLE
Constructor public ml.combust.mleap.spark.SimpleSparkSerializer() is not whitelisted.

### ISSUE THREAD

**Issue by devbas** [combust/mleap#658]
When working with MLeap on a high concurrency cluster on Azure Databricks with a mounted ADLS volume, the following error occurs when I try to write a model with `mlflow.mleap.log_model()` to a volume: 

```
Traceback (most recent call last):
  File "/databricks/python/lib/python3.7/site-packages/mlflow/mleap.py", line 151, in add_to_model
    dataset=dataset)
  File "/databricks/python/lib/python3.7/site-packages/mleap/pyspark/spark_support.py", line 24, in serializeToBundle
    serializer = SimpleSparkSerializer()
  File "/databricks/python/lib/python3.7/site-packages/mleap/pyspark/spark_support.py", line 39, in __init__
    self._java_obj = _jvm().ml.combust.mleap.spark.SimpleSparkSerializer()
  File "/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1525, in __call__
    answer, self._gateway_client, None, self._fqn)
  File "/databricks/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))

py4j.protocol.Py4JError: An error occurred while calling None.ml.combust.mleap.spark.SimpleSparkSerializer. Trace:
py4j.security.Py4JSecurityException: Constructor public ml.combust.mleap.spark.SimpleSparkSerializer() is not whitelisted.
	at py4j.security.WhitelistingPy4JSecurityManager.checkConstructor(WhitelistingPy4JSecurityManager.java:377)
	at py4j.Gateway.invoke(Gateway.java:249)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

To Azure Databricks, this is a [known issue](https://docs.microsoft.com/en-us/azure/databricks/data/data-sources/azure/adls-passthrough): 

"This exception is thrown when you have accessed a method that Azure Databricks has not explicitly marked as safe for Azure Data Lake Storage credential passthrough clusters. In most cases, this means that the method could allow a user on a Azure Data Lake Storage credential passthrough cluster to access another user’s credentials."

**Comment by ancasarb** [comment]
@WeichenXu123 Do you have an idea what we need to do to get this to work? Is the change needed on mleap side or mlflow or databricks part? Thank you!

**Comment by ancasarb** [comment]
@devbas I think it would be best to open this issue / question on mlflow project since it involves `mlflow.mleap.log_model()`. If there are any changes required on mleap side, happy to do so once we know what needs addressing.

Closing for now, please reopen once we have more details. Thank you!
