### ISSUE TITLE
Failed to find a default value for splits

### ISSUE THREAD

**Issue by marvinxu-free** [combust/mleap#676]
i trying to save my pipeline model with mleap,while get this error:
`Failed to find a default value for splits`.
detail error message is : 

```
2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - Exception in thread "main" java.util.NoSuchElementException: Failed to find a default value for splits

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.ml.param.Params$$anonfun$getOrDefault$2.apply(params.scala:780)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.ml.param.Params$$anonfun$getOrDefault$2.apply(params.scala:780)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.Option.getOrElse(Option.scala:121)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.ml.param.Params$class.getOrDefault(params.scala:779)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.ml.PipelineStage.getOrDefault(Pipeline.scala:42)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.ml.param.Params$class.$(params.scala:786)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.ml.PipelineStage.$(Pipeline.scala:42)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.ml.feature.Bucketizer.getSplits(Bucketizer.scala:77)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.ml.bundle.ops.feature.BucketizerOp$$anon$1.store(BucketizerOp.scala:21)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.ml.bundle.ops.feature.BucketizerOp$$anon$1.store(BucketizerOp.scala:14)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:87)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:83)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.util.Try$.apply(Try.scala:192)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:83)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:85)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:81)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.util.Try$.apply(Try.scala:192)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:81)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:34)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:30)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.util.Try$.apply(Try.scala:192)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.GraphSerializer.writeNode(GraphSerializer.scala:30)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.GraphSerializer.write(GraphSerializer.scala:20)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:21)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:14)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:87)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:83)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.util.Try$.apply(Try.scala:192)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:83)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:85)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:81)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.util.Try$.apply(Try.scala:192)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:81)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:34)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:30)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.util.Try$.apply(Try.scala:192)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.GraphSerializer.writeNode(GraphSerializer.scala:30)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.GraphSerializer.write(GraphSerializer.scala:20)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:21)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:14)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:87)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:83)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.util.Try$.apply(Try.scala:192)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:83)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:85)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:81)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.util.Try$.apply(Try.scala:192)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:81)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:34)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:29)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.util.Try$.apply(Try.scala:192)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.serializer.BundleSerializer.write(BundleSerializer.scala:29)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at ml.combust.bundle.BundleWriter.save(BundleWriter.scala:31)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at com.zenmen.wkread.pipeline.serving.mleap.serialization.ModelSerializer$$anonfun$serializeModel$2.apply(ModelSerializer.scala:22)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at com.zenmen.wkread.pipeline.serving.mleap.serialization.ModelSerializer$$anonfun$serializeModel$2.apply(ModelSerializer.scala:20)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at resource.AbstractManagedResource$$anonfun$5.apply(AbstractManagedResource.scala:88)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.util.control.Exception$Catch.apply(Exception.scala:103)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at scala.util.control.Exception$Catch.either(Exception.scala:125)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at resource.AbstractManagedResource.acquireFor(AbstractManagedResource.scala:88)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at resource.ManagedResourceOperations$class.apply(ManagedResourceOperations.scala:26)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at resource.AbstractManagedResource.apply(AbstractManagedResource.scala:50)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at resource.ManagedResourceOperations$class.acquireAndGet(ManagedResourceOperations.scala:25)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at resource.AbstractManagedResource.acquireAndGet(AbstractManagedResource.scala:50)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at resource.ManagedResourceOperations$class.foreach(ManagedResourceOperations.scala:53)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at resource.AbstractManagedResource.foreach(AbstractManagedResource.scala:50)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at com.zenmen.wkread.pipeline.serving.mleap.serialization.ModelSerializer.serializeModel(ModelSerializer.scala:20)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at com.zenmen.wkread.pipeline.models.ModelSelect$.modelSelect(ModelSelect.scala:344)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at com.zenmen.wkread.pipeline.models.ModelSelect$.doRun(ModelSelect.scala:78)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at com.zenmen.wkread.utils.RunUtils.main(RunUtils.scala:31)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at com.zenmen.wkread.pipeline.models.ModelSelect.main(ModelSelect.scala)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at java.lang.reflect.Method.invoke(Method.java:498)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:879)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)

2020-05-08 15:22:03 - Spark-job - Spark.run - INFO - line:110 - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by ancasarb** [comment]
@marvinxu-free May I please ask which version of mleap you are using? I can see the splits being set correctly in master https://github.com/combust/mleap/blob/master/mleap-spark/src/main/scala/org/apache/spark/ml/bundle/ops/feature/BucketizerOp.scala.

**Comment by marvinxu-free** [comment]
> @marvinxu-free May I please ask which version of mleap you are using? I can see the splits being set correctly in master https://github.com/combust/mleap/blob/master/mleap-spark/src/main/scala/org/apache/spark/ml/bundle/ops/feature/BucketizerOp.scala.

i have resolved this problem, the reason is i used old api to save mleap model, i remember is `SparkBundle` to get context, which is not correct for the 1.3 version.

**Comment by marvinxu-free** [comment]
> @marvinxu-free May I please ask which version of mleap you are using? I can see the splits being set correctly in master https://github.com/combust/mleap/blob/master/mleap-spark/src/main/scala/org/apache/spark/ml/bundle/ops/feature/BucketizerOp.scala.

my mleap version is :
```
        <dependency>
            <groupId>ml.combust.mleap</groupId>
            <artifactId>mleap-spark_2.11</artifactId>
            <version>0.13.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/ml.combust.mleap/mleap-runtime -->
        <dependency>
            <groupId>ml.combust.mleap</groupId>
            <artifactId>mleap-runtime_2.11</artifactId>
            <version>0.13.0</version>
        </dependency>
```

when i used this code to save mleap, it will report this problem:
```
// Use your Spark ML Pipeline to transform the Spark DataFrame
val transformedDataset = sparkTransformer.transform(sparkDataset)

// Create a custom SparkBundleContext and provide the transformed DataFrame
implicit val sbc = SparkBundleContext().withDataset(transformedDataset)

// Serialize the pipeline as you would normally
(for(bf <- managed(BundleFile(file))) yield {
  sparkTransformer.writeBundle.save(bf).get
}).tried.get
```

when I used code like this, this error will disappear, while can not load mleap zip file for serveing ,:
```
package com.zenmen.wkread.pipeline.serving.mleap.serialization

import ml.combust.bundle.BundleFile
import ml.combust.mleap.spark.SparkSupport._
import org.apache.spark.ml.PipelineModel
import org.apache.spark.ml.bundle.SparkBundleContext
import ml.combust.bundle.serializer.SerializationFormat
import org.apache.spark.sql.DataFrame
import resource._
import org.slf4j.LoggerFactory

class ModelSerializer {
  private val logger = LoggerFactory.getLogger("dataBaseLogger")

  def serializeModel(pipelineModel: PipelineModel,
                     modelSavePath: String,
                     transformedData: DataFrame): Unit = {

    implicit val context = SparkBundleContext().withDataset(transformedData)
    (for (modelFile <- managed(BundleFile(modelSavePath))) yield {
      logger.info(s"bf: ${modelFile.toString}")
      pipelineModel.writeBundle
        .format(SerializationFormat.Json)
        .save(modelFile)(context)
    }).tried.get

  }

}

```
with report error like this:
`c.z.n.c.r.m.MLeapFMClickV2ModelManager - updateMLeapFMClickV2Model error java.nio.file.NoSuchFileException: bundle.json`.

I can not find bundle.json in zip file, but in my local program , i can find bundle.json, and model serving is success. i don't know why, my local spark and spark cluster version is 2.3.0, and scala is 2.11.8.

**Comment by marvinxu-free** [comment]
i found the reason why mleap save model failed, this code can recurrent error:
```
  test("testFM2.3") {
    val data0 = spark
      .createDataFrame(
        Seq(
          (Array("1"), 17, 1.0, Map("a" -> 0.1, "b" -> 0.2, "c" -> 0.3), 1),
          (Array("2"), 10, 10.0, Map("d" -> 0.1, "e" -> 0.2, "c" -> 0.3), 0),
          (Array("3"), 20, 20.0, Map("x" -> 0.1, "a" -> 0.2, "b" -> 0.3), 0),
          (Array("4"), 15, 15.0, Map("c" -> 0.1, "b" -> 0.2, "w" -> 0.3), 0),
          (Array("5"), 182, 18.0, Map("c" -> 0.1, "b" -> 0.2, "w" -> 0.3), 0),
          (Array("6"), 825, 25.0, Map("c" -> 0.1, "b" -> 0.2, "w" -> 0.3), 1),
          (Array("6"), 50, 5.0, Map("a" -> 0.1, "b" -> 0.2, "d" -> 0.3), 0),
          (Array("7"), 320, 30.0, Map("c" -> 0.1, "b" -> 0.2, "w" -> 0.3), 0)
        )
      )
      .toDF("book_id", "uv", "pv", "myInputCol0", "label")

    val data = data0
      .withColumn("myInputCol", keyUdf(functions.col("myInputCol0")))
      .drop("myInputCol0")

    data.show(10)
    data.printSchema()

    val pipelineStage = new ArrayBuffer[PipelineStage]()

    val bookFiter = new CountVectorizer()
      .setInputCol("book_id")
      .setOutputCol("book_id_vec")
      .setMinDF(1)
      .setMinTF(1)
      .setBinary(true)
    pipelineStage += bookFiter

    val doubleDiscretizer = new QuantileDiscretizer()
      .setInputCols(Array("uv", "pv"))
      .setOutputCols(Array("uv_bucket", "pv_bucket"))
      .setNumBucketsArray(Array(3, 3))
    pipelineStage += doubleDiscretizer

    val buckCountVec = new OneHotEncoderEstimator()
      .setInputCols(Array("uv_bucket", "pv_bucket"))
      .setOutputCols(Array("uv_bucket_onehot", "pv_bucket_onehot"))
    pipelineStage += buckCountVec

    val myFiter = new CountVectorizer()
      .setInputCol("myInputCol")
      .setOutputCol("myInputCol1_vec")
      .setMinDF(1)
      .setMinTF(1)
      .setBinary(true)
    pipelineStage += myFiter

    val vectorAsCols = Array(
      "uv_bucket_onehot",
      "pv_bucket_onehot",
      "book_id_vec",
      "myInputCol1_vec"
    )

    val vectorAssembler = new VectorAssembler()
      .setInputCols(vectorAsCols)
      .setOutputCol("scaledFeatures")
    pipelineStage += vectorAssembler

    //    val scaler = new Normalizer()
    //      .setInputCol("vectorFeature")
    //      .setOutputCol("scaledFeatures")
    //    pipelineStage += scaler

    val featurePipeline = new Pipeline().setStages(pipelineStage.toArray)
    val pipeLineModel = featurePipeline.fit(data)

    val trainData = pipeLineModel.transform(data)
    trainData.show()

    File(s"${dataOutPath}/fm2/mleap/fm.model.mleap.zip").delete()
    val mleapModel = new ModelSerializer()
    mleapModel.serializeModel(
      pipeLineModel,
      s"jar:file:${dataOutPath}/fm2/mleap/fm.model.mleap.zip",
      trainData
    )

    val fm = new FM()
      .setFeaturesCol("scaledFeatures")
      .setLabelCol("label")
      .setFitIntercept(true)
      .setMaxIter(5)
      .setRank(2)

    val fmModel = fm.fit(trainData)
    fmModel.write.overwrite().save(s"${dataOutPath}/fm2/model")
    val predict = fmModel.transform(trainData)
    //    predict.show()
    val evaluator = new Evaluator
    evaluator.evaluate(predict)
    println(evaluator.auc)
    println(evaluator.pr)

    val dataFinal = predict.select(
      Seq(
        functions.concat_ws(",", functions.col("book_id")),
        functions.col("pv"),
        functions.concat_ws(",", functions.col("myInputCol")),
        getProb1(functions.col("probability")).alias("prob1")
      ): _*
    )
    dataFinal.show()

    
  }
```
the reason is mleap do not support QuantileDiscretizer with inputCols, which means you can not do QuantileDiscretizer for array and save the pipeline model by mleap.
