### ISSUE TITLE
Mleap gRPC request fails with java.lang.ClassNotFoundException: ml.combust.mleap.pb.json.DefaultFrameReader

### ISSUE THREAD

**Issue by TamilN** [combust/mleap#730]
Hi, i have loaded a mleap model in mleap serving 0.16 / 0.17 when tried to perform Transform using gRPC, it fails with java.lang.ClassNotFoundException: ml.combust.mleap.pb.json.DefaultFrameReader

Please find the snippet of log on the mleap serving server

```
Exception in thread "grpc-default-executor-45" java.lang.Error: java.lang.ClassNotFoundException: ml.combust.mleap.pb.json.DefaultFrameReader
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: ml.combust.mleap.pb.json.DefaultFrameReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at ml.combust.mleap.runtime.serialization.FrameReader$.apply(FrameReader.scala:20)
	at ml.combust.mleap.grpc.server.GrpcServer.transform(GrpcServer.scala:86)
	at ml.combust.mleap.pb.MleapGrpc$$anon$9.invoke(MleapGrpc.scala:291)
	at ml.combust.mleap.pb.MleapGrpc$$anon$9.invoke(MleapGrpc.scala:289)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:272)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:653)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	... 2 more

please find the gRPC request using `grpcurl`

grpcurl -v -connect-timeout 30 -max-time 30 -plaintext -proto grpc.proto -proto mleap.proto -proto bundle.proto -d "$jsp" 9.30.108.176:65328 ml.combust.mleap.pb.Mleap/Transform

Resolved method descriptor:
rpc Transform ( .ml.combust.mleap.pb.TransformFrameRequest ) returns ( .ml.combust.mleap.pb.TransformFrameResponse );

Request metadata to send:
(empty)

Response headers received:
(empty)

Response trailers received:
(empty)
Sent 1 request and received 0 responses
ERROR:
  Code: DeadlineExceeded
  Message: context deadline exceeded

```

payload used

`{ "modelName":"airbnb", "format":"ml.combust.mleap.pb.json", "initTimeout":"35000", "tag":0, "frame":"eyJzY2hlbWEiOnsiZmllbGRzIjpbeyJuYW1lIjoic3RhdGUiLCJ0eXBlIjoic3RyaW5nIn0seyJuYW1lIjoiYmF0aHJvb21zIiwidHlwZSI6ImRvdWJsZSJ9LHsibmFtZSI6InNxdWFyZV9mZWV0IiwidHlwZSI6ImRvdWJsZSJ9LHsibmFtZSI6ImJlZHJvb21zIiwidHlwZSI6ImRvdWJsZSJ9LHsibmFtZSI6InNlY3VyaXR5X2RlcG9zaXQiLCJ0eXBlIjoiZG91YmxlIn0seyJuYW1lIjoiY2xlYW5pbmdfZmVlIiwidHlwZSI6ImRvdWJsZSJ9LHsibmFtZSI6ImV4dHJhX3Blb3BsZSIsInR5cGUiOiJkb3VibGUifSx7Im5hbWUiOiJudW1iZXJfb2ZfcmV2aWV3cyIsInR5cGUiOiJkb3VibGUifSx7Im5hbWUiOiJyZXZpZXdfc2NvcmVzX3JhdGluZyIsInR5cGUiOiJkb3VibGUifSx7Im5hbWUiOiJyb29tX3R5cGUiLCJ0eXBlIjoic3RyaW5nIn0seyJuYW1lIjoiaG9zdF9pc19zdXBlcmhvc3QiLCJ0eXBlIjoic3RyaW5nIn0seyJuYW1lIjoiY2FuY2VsbGF0aW9uX3BvbGljeSIsInR5cGUiOiJzdHJpbmcifSx7Im5hbWUiOiJpbnN0YW50X2Jvb2thYmxlIiwidHlwZSI6InN0cmluZyJ9XX0sInJvd3MiOltbIk5ZIiwyLDEyNTAsMyw1MCwzMCwyLDU2LDkwLCJFbnRpcmUgaG9tZS9hcHQiLCIxLjAiLCJzdHJpY3QiLCIxLjAiXV19Cg==" }`

Also do you have example for Transform using gRPC on python / scala

Thanks for looking into this issue.

**Comment by TamilN** [comment]
i get same error when tried following python from jupyter notebook

```
import grpc
import grpc_pb2_grpc
import mleap_pb2

import json
import pandas
data= json.load(open('frame.airbnb.json'))
bytes = json.dumps(data).encode('utf-8') 

infer_client = grpc_pb2_grpc.MleapStub(channel)

request=mleap_pb2.TransformFrameRequest(model_name='airbnb',frame=bytes,format="ml.combust.mleap.pb.json")
results=infer_client.Transform(request)
```

**Comment by TamilN** [comment]
We had to try with proto due to refection not supported, thats the reason not able to use `ml.combust.mleap.json`

`grpcurl -v -connect-timeout 30 -max-time 30 -plaintext -d "$jsp" <server> ml.combust.mleap.pb.Mleap/Transform`
Error invoking method "ml.combust.mleap.pb.Mleap/Transform": failed to query for service descriptor "ml.combust.mleap.pb.Mleap": server does not support the reflection API

**Comment by TamilN** [comment]
i believe the actual issue is https://github.com/combust/mleap/issues/730#issuecomment-740596806

**Comment by TamilN** [comment]
its working now after including `options` in the payload, thanks

{
  "modelName": "airbnb",
  "format": "ml.combust.mleap.json",
  "frame": "eyJzY2hlbWEiOnsiZmllbGRzIjpbeyJuYW1lIjoic3RhdGUiLCJ0eXBlIjoic3RyaW5nIn0seyJuYW1lIjoiYmF0aHJvb21zIiwidHlwZSI6ImRvdWJsZSJ9LHsibmFtZSI6InNxdWFyZV9mZWV0IiwidHlwZSI6ImRvdWJsZSJ9LHsibmFtZSI6ImJlZHJvb21zIiwidHlwZSI6ImRvdWJsZSJ9LHsibmFtZSI6InNlY3VyaXR5X2RlcG9zaXQiLCJ0eXBlIjoiZG91YmxlIn0seyJuYW1lIjoiY2xlYW5pbmdfZmVlIiwidHlwZSI6ImRvdWJsZSJ9LHsibmFtZSI6ImV4dHJhX3Blb3BsZSIsInR5cGUiOiJkb3VibGUifSx7Im5hbWUiOiJudW1iZXJfb2ZfcmV2aWV3cyIsInR5cGUiOiJkb3VibGUifSx7Im5hbWUiOiJyZXZpZXdfc2NvcmVzX3JhdGluZyIsInR5cGUiOiJkb3VibGUifSx7Im5hbWUiOiJyb29tX3R5cGUiLCJ0eXBlIjoic3RyaW5nIn0seyJuYW1lIjoiaG9zdF9pc19zdXBlcmhvc3QiLCJ0eXBlIjoic3RyaW5nIn0seyJuYW1lIjoiY2FuY2VsbGF0aW9uX3BvbGljeSIsInR5cGUiOiJzdHJpbmcifSx7Im5hbWUiOiJpbnN0YW50X2Jvb2thYmxlIiwidHlwZSI6InN0cmluZyJ9XX0sInJvd3MiOltbIk5ZIiwyLDEyNTAsMyw1MCwzMCwyLDU2LDkwLCJFbnRpcmUgaG9tZS9hcHQiLCIxLjAiLCJzdHJpY3QiLCIxLjAiXV19Cg==",
  "options": {
    "select": [],
    "selectMode": "SELECT_MODE_STRICT"
  }
}
