### ISSUE TITLE
Cloud not load xgboost model into spring boot service

### ISSUE THREAD

**Issue by BDon-Tan** [combust/mleap#785]
hi, 
     I have serialized a xgboost-spark pipeline model in bundle format, but I could not load it into spring boot service because of "xgboost.classifier" op is not supported. I found that mleap-xgboost-runtime is released now. It seems loading xgboost-spark pipeline should be accessible. Would you help me about how to add dependency of mleap-xgboost-runtime into mleap-spring-boot ? Or update the docker with xgboost model support?

**Comment by zgcheng82725411** [comment]
hi, I have add it as a dependency in our build.sbt, but it does not work,
project mleap-runtime build.sbt:

import ml.combust.mleap.{Dependencies, Common}
Common.defaultMleapSettings
Common.defaultMleapXgboostSparkSettings
Dependencies.runtime(scalaVersion)

The error is “Exception in thread "main" java.util.NoSuchElementException: key not found: xgboost.classifier
	at scala.collection.MapLike.default(MapLike.scala:235)”

**Comment by zgcheng82725411** [comment]
hi, I have add it as a dependency in our build.sbt, but it does not work,
project mleap-runtime build.sbt:

import ml.combust.mleap.{Dependencies, Common}
Common.defaultMleapSettings
Common.defaultMleapXgboostSparkSettings
Dependencies.runtime(scalaVersion)

The error is “Exception in thread "main" java.util.NoSuchElementException: key not found: xgboost.classifier
	at scala.collection.MapLike.default(MapLike.scala:235)”

**Comment by jsleight** [comment]
Can you provide a more complete stacktrace?

My only thought right now is that the mleap runtime can't find the correct op used to load the bundle.  This could occur if you have a resources.conf file in your project and aren't having mleap's reference.conf appended to your project's reference.conf.  E.g., if you are using sbt-assembly plugin, then you might need
```
assemblyMergeStrategy in assembly := {
  case "reference.conf" => MergeStrategy.concat
  case _ => MergeStrategy.first
}
```

But a complete stacktrace will help to confirm/deny this.
