### ISSUE TITLE
Need Help on Contributing towards Mleap for 2.13

### ISSUE THREAD

**Issue by prashil1996** [combust/mleap#869]
Hi Developers,

I've recently forked the main MLeap repository with the intention of contributing to support Scala 2.13. However, I'm unfamiliar with the build process and prerequisites. Could you please provide guidance on the necessary steps to make local changes and build MLeap with Scala 2.13 compatibility?

Thank you for your assistance.
Prashil

**Comment by jsleight** [comment]
Use the make targets in the repo root to build and run tests.  Once you have a build that you think works locally, then can commit and push to origin to create a PR.  That will trigger a full build on our CI system.

Specifically regarding scala 2.13 compatibility, please aim for cross compiling to support both scala 2.12 and 2.13.  sbt has native support for this and the repo should already be set up correctly to utilize it.

**Comment by prashil1996** [comment]
@jsleight Thanks for replying, also what are the different requirements for compiling the build locally? 
Scala, Java, SBT? 

I tried building it locally but I was getting some error. Can you help me with some steps? Any wiki? 

The following were encountered after running make on the root repo: 
```

[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] file:/Users/prashil/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar: not found: /Users/prashil/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
[error] 
[error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:365)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:82)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$NotFound: not found: /Users/prashil/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader.$anonfun$checkFileExists$1(Downloader.scala:590)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[error] (mleap-core / update) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] file:/Users/prashil/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar: not found: /Users/prashil/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
[error] Total time: 1 s, completed 14-Oct-2023, 5:19:48 pm
```

**Comment by jsleight** [comment]
Ah
- sbt v1.9.4 
- java 11
- spark 3.4
(fyi: the `/project` directory of sbt projects usually has all these details.)

The libxgboost4j being missing is a known thing when trying to build on mac.  XGBoost's java libraries don't support mac.  iirc tensorflow libraries might have this problem too.
